import moment from "moment";

/**
 * Map all aihwform record fields for full detail view.
 */
export function transformConsents(record) {
  return {
    // Identifiers
fformResponseID:record.formResponseID,
formIdentifier:record.formIdentifier,
subjectID:record.subjectID,
groupID:record.groupID,
familyID:record.familyID,
responseSetID:record.responseSetID,
formID:record.formID,
collectionTypeID:record.collectionTypeID,
subjectTypeID:record.subjectTypeID,
collectionID:record.collectionID,
responseCreatedDate:record.responseCreatedDate ? moment(record.responseCreatedDate).format("DD/MM/YYYY") : null,
programID:record.programID,
auditStaffID:record.auditStaffID,
auditDate:record.auditDate ? moment(record.auditDate).format("DD/MM/YYYY") : null,
dataEnteredByID:record.dataEnteredByID,
draftSavedOn:record.draftSavedOn,
removedDate:record.removedDate ? moment(record.removedDate).format("DD/MM/YYYY") : null,
micahTeam_25224:record.micahTeam_25224,
consenttorecordstoreinformationIunderstandthatcertaininformationcollectedbyMicahProjectsoranaf_25226:record.consenttorecordstoreinformationIunderstandthatcertaininformationcollectedbyMicahProjectsoranaf_25226,
consenttorecordstoreinformationIunderstandthatcertaininformationcollectedbyMicahProjectsoranaf_25226_ResponseChoiceID:record.consenttorecordstoreinformationIunderstandthatcertaininformationcollectedbyMicahProjectsoranaf_25226_ResponseChoiceID,
igiveconsentfordeidentifiedinformationtobeusedforadvocacypurposes_25227:record.igiveconsentfordeidentifiedinformationtobeusedforadvocacypurposes_25227,
igiveconsentfordeidentifiedinformationtobeusedforadvocacypurposes_25227_ResponseChoiceID:record.igiveconsentfordeidentifiedinformationtobeusedforadvocacypurposes_25227_ResponseChoiceID,
iconsenttoallowMicahProjectstoprovidemewithservicesasrequestedandrequiredIunderstandIamabletoa_25228:record.iconsenttoallowMicahProjectstoprovidemewithservicesasrequestedandrequiredIunderstandIamabletoa_25228,
iconsenttoallowMicahProjectstoprovidemewithservicesasrequestedandrequiredIunderstandIamabletoa_25228_ResponseChoiceID:record.iconsenttoallowMicahProjectstoprovidemewithservicesasrequestedandrequiredIunderstandIamabletoa_25228_ResponseChoiceID,
iunderstandandgiveconsentforMicahProjectstoprovidemypersonalinformationtootherrelevantpersonso_25229:record.iunderstandandgiveconsentforMicahProjectstoprovidemypersonalinformationtootherrelevantpersonso_25229,
iunderstandandgiveconsentforMicahProjectstoprovidemypersonalinformationtootherrelevantpersonso_25229_ResponseChoiceID:record.iunderstandandgiveconsentforMicahProjectstoprovidemypersonalinformationtootherrelevantpersonso_25229_ResponseChoiceID,
iconsenttoMicahProjectsemployeesaccessingtheTICAdatabaseonmybehalf_25230:record.iconsenttoMicahProjectsemployeesaccessingtheTICAdatabaseonmybehalf_25230,
iconsenttoMicahProjectsemployeesaccessingtheTICAdatabaseonmybehalf_25230_ResponseChoiceID:record.iconsenttoMicahProjectsemployeesaccessingtheTICAdatabaseonmybehalf_25230_ResponseChoiceID,
idonotconsenttomypersonalinformationbeingdisclosedtothepersonoragencieslistedbelow_25231:record.idonotconsenttomypersonalinformationbeingdisclosedtothepersonoragencieslistedbelow_25231,
listedbelowthechildrenandoradultswithimpaireddecisionmakingcapacity_25232:record.listedbelowthechildrenandoradultswithimpaireddecisionmakingcapacity_25232,
iunderstandthattheconsentIhaveprovidedhereformyselfwillalsoapplytothefollowingchildrenandoradu_25233:record.iunderstandthattheconsentIhaveprovidedhereformyselfwillalsoapplytothefollowingchildrenandoradu_25233,
iunderstandthattheconsentIhaveprovidedhereformyselfwillalsoapplytothefollowingchildrenandoradu_25233_ResponseChoiceID:record.iunderstandthattheconsentIhaveprovidedhereformyselfwillalsoapplytothefollowingchildrenandoradu_25233_ResponseChoiceID,
iacknowledgethatMicahProjectshasadvisedmeoftheWorkingTogetherwithMicahProjectsfactsheetwhichin_25235:record.iacknowledgethatMicahProjectshasadvisedmeoftheWorkingTogetherwithMicahProjectsfactsheetwhichin_25235,
iacknowledgethatMicahProjectshasadvisedmeoftheWorkingTogetherwithMicahProjectsfactsheetwhichin_25235_ResponseChoiceID:record.iacknowledgethatMicahProjectshasadvisedmeoftheWorkingTogetherwithMicahProjectsfactsheetwhichin_25235_ResponseChoiceID,
iunderstandthattherearesomeexceptionswheremyconsentisnotrequiredtoshareinformationwithothersTh_25238:record.iunderstandthattherearesomeexceptionswheremyconsentisnotrequiredtoshareinformationwithothersTh_25238,
iunderstandthattherearesomeexceptionswheremyconsentisnotrequiredtoshareinformationwithothersTh_25238_ResponseChoiceID:record.iunderstandthattherearesomeexceptionswheremyconsentisnotrequiredtoshareinformationwithothersTh_25238_ResponseChoiceID,
inabilitytogainconsentWorkertocomplete_25239:record.inabilitytogainconsentWorkertocomplete_25239,
inabilitytogainconsentWorkertocomplete_25239_ResponseChoiceID:record.inabilitytogainconsentWorkertocomplete_25239_ResponseChoiceID,
reasonforrefusalwithdrawal_25240:record.reasonforrefusalwithdrawal_25240,
signedbypersonfamily_25241:record.signedbypersonfamily_25241,
signedbypersonfamily_25241_Signee:record.signedbypersonfamily_25241_Signee,
signedbypersonfamily_25241_Image:record.signedbypersonfamily_25241_Image,
dateofSignature_25242:record.dateofSignature_25242 ? moment(record.dateofSignature_25242).format("DD/MM/YYYY") : null,
workerSignature_25243:record.workerSignature_25243 ? moment(record.workerSignature_25243).format("DD/MM/YYYY") : null,
workerSignature_25243_Signee:record.workerSignature_25243_Signee,
workerSignature_25243_Image:record.workerSignature_25243_Image,
workerDatesigned_25244:record.workerDatesigned_25244,
verbalConsentprovided_25246:record.verbalConsentprovided_25246,
verbalConsentprovided_25246_ResponseChoiceID:record.verbalConsentprovided_25246_ResponseChoiceID,
uploadScannedDocumenthereClickonUploadNavigatetofileandselectSelectandthenOpenfilewillautomati_25247:record.uploadScannedDocumenthereClickonUploadNavigatetofileandselectSelectandthenOpenfilewillautomati_25247,
consentstatus_25257:record.consentstatus_25257,
consentstatus_25257_ResponseChoiceID:record.consentstatus_25257_ResponseChoiceID,
workersignature_25274:record.workersignature_25274,
workersignature_25274_Signee:record.workersignature_25274_Signee,
workersignature_25274_Image:record.workersignature_25274_Image,
iunderstandthatpersonalinformationwillbemanagedinaccordancewiththeInformationPrivacyAct2009QLD_29320:record.iunderstandthatpersonalinformationwillbemanagedinaccordancewiththeInformationPrivacyAct2009QLD_29320,
iunderstandthatpersonalinformationwillbemanagedinaccordancewiththeInformationPrivacyAct2009QLD_29320_ResponseChoiceID:record.iunderstandthatpersonalinformationwillbemanagedinaccordancewiththeInformationPrivacyAct2009QLD_29320_ResponseChoiceID,
iconsenttobeinginvitedtoparticipateinresearchendorsedbyMicahProjectsIfIaminvitedtheprojectwill_29321:record.iconsenttobeinginvitedtoparticipateinresearchendorsedbyMicahProjectsIfIaminvitedtheprojectwill_29321,
iconsenttobeinginvitedtoparticipateinresearchendorsedbyMicahProjectsIfIaminvitedtheprojectwill_29321_ResponseChoiceID:record.iconsenttobeinginvitedtoparticipateinresearchendorsedbyMicahProjectsIfIaminvitedtheprojectwill_29321_ResponseChoiceID,
iconsentforMicahtostoremyhousekeysindesignatedkeystorage_30828:record.iconsentforMicahtostoremyhousekeysindesignatedkeystorage_30828,
iconsentforMicahtostoremyhousekeysindesignatedkeystorage_30828_ResponseChoiceID:record.iconsentforMicahtostoremyhousekeysindesignatedkeystorage_30828_ResponseChoiceID,
programName:record.programName,


  };
}


export function transformconsent(records) {
  const minimalKeys = [
    "programName",
    "auditDate",    
    "workerDatesigned_25244",
    "consentstatus_25257",
    "dateofSignature_25242"    
  ];
  
    

  // Map all records to frontend format first
  const mapped = records.map(transformConsents);

  // Then extract minimal information from mapped records
  const minimal = mapped.map(rec =>
    ({
      ...Object.fromEntries(
        minimalKeys.map(key => [key, rec[key]])
      ),
      StaffName: `${rec.fName || ''} ${rec.lName || ''}`.trim(),
    })
  );

  return {
    minimal,
    full: mapped
  };
}