import moment from "moment";

function transformLotusNotes(input) {
  return {
    formResponseID: input.formResponseID ?? null,
    formIdentifier: input.formIdentifier ?? null,
    subjectID: input.subjectID ?? null,
    groupID: input.groupID ?? null,
    familyID: input.familyID ?? null,
    responseSetID: input.responseSetID ?? null,
    formID: input.formID ?? null,
    collectionTypeID: input.collectionTypeID ?? null,
    subjectTypeID: input.subjectTypeID ?? null,
    collectionID: input.collectionID ?? null,
    responseCreatedDate:  input.responseCreatedDate ? moment(input.responseCreatedDate).format("DD/MM/YYYY") : "",
    programID: input.programID ?? null,
    auditStaffID: input.auditStaffID ?? null,
    auditDate: input.auditDate ? moment(input.auditDate).format("DD/MM/YYYY") : "",
    dataEnteredByID: input.dataEnteredByID ?? null,
    draftSavedOn: input.draftSavedOn ?? null,
    removedDate: input.removedDate ?? null,
    contactMethod_27348: input.contactMethod_27348 ?? null,
    contactMethod_27348_ResponseChoiceID: input.contactMethod_27348_ResponseChoiceID ?? null,
    contactLocation_27349: input.contactLocation_27349 ?? null,
    contactLocation_27349_ResponseChoiceID: input.contactLocation_27349_ResponseChoiceID ?? null,
    howmanystaffdidthistogetherAtmost4_27350: input.howmanystaffdidthistogetherAtmost4_27350 ?? null,
    timespentwithparticipantPerstaffmember_27351: input.timespentwithparticipantPerstaffmember_27351 ?? null,
    timespentonbehalfofparticipantPerstaffmember_27352: input.timespentonbehalfofparticipantPerstaffmember_27352 ?? null,
    timespenttravellingNotwithparticipantPerstaffmember_27353: input.timespenttravellingNotwithparticipantPerstaffmember_27353 ?? null,
    totaltimespentwithparticipant_27354: input.totaltimespentwithparticipant_27354 ?? null,
    totaltimespentonbehalfofparticipant_27355: input.totaltimespentonbehalfofparticipant_27355 ?? null,
    totaltimespenttravelling_27356: input.totaltimespenttravelling_27356 ?? null,
    totalefforttimeforparticipant_27357: input.totalefforttimeforparticipant_27357 ?? null,
    selectyourname_27358: input.selectyourname_27358 ?? null,
    micahTeam_27359: input.micahTeam_27359 ?? null,
    selectthe2ndstaffperson_27360: input.selectthe2ndstaffperson_27360 ?? null,
    whatotherteamassisted_27361: input.whatotherteamassisted_27361 ?? null,
    serviceType_27366: input.serviceType_27366 ?? null,
    serviceType_27366_ResponseChoiceID: input.serviceType_27366_ResponseChoiceID ?? null,
    serviceSetting_27367: input.serviceSetting_27367 ?? null,
    serviceSetting_27367_ResponseChoiceID: input.serviceSetting_27367_ResponseChoiceID ?? null,
    interpreterPresent_27368: input.interpreterPresent_27368 ?? null,
    interpreterPresent_27368_ResponseChoiceID: input.interpreterPresent_27368_ResponseChoiceID ?? null,
    notes_27369: input.notes_27369 ?? null,
    disabilityimpairmentorconditionindicator_27372: input.disabilityimpairmentorconditionindicator_27372 ?? null,
    disabilityimpairmentorconditionindicator_27372_ResponseChoiceID: input.disabilityimpairmentorconditionindicator_27372_ResponseChoiceID ?? null,
    selectallofthereasonsforseekingassistance_27378: input.selectallofthereasonsforseekingassistance_27378 ?? null,
    selectallofthereasonsforseekingassistance_27378_ResponseChoiceID: input.selectallofthereasonsforseekingassistance_27378_ResponseChoiceID ?? null,
    selectDomain_27386: input.selectDomain_27386 ?? null,
    selectDomain_27386_ResponseChoiceID: input.selectDomain_27386_ResponseChoiceID ?? null,
    selectthemainreasonforseekingassistanceNotethemainreasonmustbeoneofthereasonstickedabove_27408: input.selectthemainreasonforseekingassistanceNotethemainreasonmustbeoneofthereasonstickedabove_27408 ?? null,
    selectthemainreasonforseekingassistanceNotethemainreasonmustbeoneofthereasonstickedabove_27408_ResponseChoiceID: input.selectthemainreasonforseekingassistanceNotethemainreasonmustbeoneofthereasonstickedabove_27408_ResponseChoiceID ?? null,
    selectyourlocation_27412: input.selectyourlocation_27412 ?? null,
    selectyourlocation_27412_ResponseChoiceID: input.selectyourlocation_27412_ResponseChoiceID ?? null,
    startTime_27430: input.startTime_27430 ?? null,
    endTimeoptional_27431: input.endTimeoptional_27431 ?? null,
    contactCategory_27854: input.contactCategory_27854 ?? null,
    contactCategory_27854_ResponseChoiceID: input.contactCategory_27854_ResponseChoiceID ?? null,
    contactDomain_27855: input.contactDomain_27855 ?? null,
    contactDomain_27855_ResponseChoiceID: input.contactDomain_27855_ResponseChoiceID ?? null,
    whatWDYNwasthisactioninresponseto_27856: input.whatWDYNwasthisactioninresponseto_27856 ?? null,
    whatWDYNwasthisactioninresponseto_27856_SourceFormID: input.whatWDYNwasthisactioninresponseto_27856_SourceFormID ?? null,
    whatWDYNwasthisactioninresponseto_27856_DisplayStr: input.whatWDYNwasthisactioninresponseto_27856_DisplayStr ?? null,
    contactLocation_28145: input.contactLocation_28145 ?? null,
    contactLocation_28145_ResponseChoiceID: input.contactLocation_28145_ResponseChoiceID ?? null,
    program_28235: input.program_28235 ?? null,
    program_28235_ResponseChoiceID: input.program_28235_ResponseChoiceID ?? null,
    typeofNote_28236: input.typeofNote_28236 ?? null,
    typeofNote_28236_ResponseChoiceID: input.typeofNote_28236_ResponseChoiceID ?? null,
    checkallfurtherassessmentsthatneedtobecompleted_29024: input.checkallfurtherassessmentsthatneedtobecompleted_29024 ?? null,
    checkallfurtherassessmentsthatneedtobecompleted_29024_ResponseChoiceID: input.checkallfurtherassessmentsthatneedtobecompleted_29024_ResponseChoiceID ?? null,
    scoreassessedby_29027: input.scoreassessedby_29027 ?? null,
    scoreassessedby_29027_ResponseChoiceID: input.scoreassessedby_29027_ResponseChoiceID ?? null,
    isthisthefirstpreorlastpostscore_29028: input.isthisthefirstpreorlastpostscore_29028 ?? null,
    isthisthefirstpreorlastpostscore_29028_ResponseChoiceID: input.isthisthefirstpreorlastpostscore_29028_ResponseChoiceID ?? null,
    domainGoals_29029: input.domainGoals_29029 ?? null,
    domainGoals_29029_ResponseChoiceID: input.domainGoals_29029_ResponseChoiceID ?? null,
    changedbehavioursScore1Noprogressinchangingbehavioursinareasrelevanttoclientsneedsandcircumsta_29032: input.changedbehavioursScore1Noprogressinchangingbehavioursinareasrelevanttoclientsneedsandcircumsta_29032 ?? null,
    changedbehavioursScore1Noprogressinchangingbehavioursinareasrelevanttoclientsneedsandcircumsta_29032_ResponseChoiceID: input.changedbehavioursScore1Noprogressinchangingbehavioursinareasrelevanttoclientsneedsandcircumsta_29032_ResponseChoiceID ?? null,
    changedimmediatecrisisScore1NoprogressinreducingthenegativeimpactoftheimmediatecrisisScore2Lim_29033: input.changedimmediatecrisisScore1NoprogressinreducingthenegativeimpactoftheimmediatecrisisScore2Lim_29033 ?? null,
    changedimmediatecrisisScore1NoprogressinreducingthenegativeimpactoftheimmediatecrisisScore2Lim_29033_ResponseChoiceID: input.changedimmediatecrisisScore1NoprogressinreducingthenegativeimpactoftheimmediatecrisisScore2Lim_29033_ResponseChoiceID ?? null,
    changedknowledgeandaccesstoinformationScore1Noprogressinincreasingaccesstoinformationandknowle_29103: input.changedknowledgeandaccesstoinformationScore1Noprogressinincreasingaccesstoinformationandknowle_29103 ?? null,
    changedknowledgeandaccesstoinformationScore1Noprogressinincreasingaccesstoinformationandknowle_29103_ResponseChoiceID: input.changedknowledgeandaccesstoinformationScore1Noprogressinincreasingaccesstoinformationandknowle_29103_ResponseChoiceID ?? null,
    changedSkillsScore1NoprogressinincreasingskillsinareasrelevanttoclientsneedsandcircumstancesSc_29104: input.changedSkillsScore1NoprogressinincreasingskillsinareasrelevanttoclientsneedsandcircumstancesSc_29104 ?? null,
    changedSkillsScore1NoprogressinincreasingskillsinareasrelevanttoclientsneedsandcircumstancesSc_29104_ResponseChoiceID: input.changedSkillsScore1NoprogressinincreasingskillsinareasrelevanttoclientsneedsandcircumstancesSc_29104_ResponseChoiceID ?? null,
    empowermentchoiceandcontroltomakeowndecisionsScore1Noprogressinincreasingconfidenceandexercisi_29105: input.empowermentchoiceandcontroltomakeowndecisionsScore1Noprogressinincreasingconfidenceandexercisi_29105 ?? null,
    empowermentchoiceandcontroltomakeowndecisionsScore1Noprogressinincreasingconfidenceandexercisi_29105_ResponseChoiceID: input.empowermentchoiceandcontroltomakeowndecisionsScore1Noprogressinincreasingconfidenceandexercisi_29105_ResponseChoiceID ?? null,
    engagementwithrelevantsupportservicesScore1Noprogressinincreasingengagementwithsupportservices_29106: input.engagementwithrelevantsupportservicesScore1Noprogressinincreasingengagementwithsupportservices_29106 ?? null,
    engagementwithrelevantsupportservicesScore1Noprogressinincreasingengagementwithsupportservices_29106_ResponseChoiceID: input.engagementwithrelevantsupportservicesScore1Noprogressinincreasingengagementwithsupportservices_29106_ResponseChoiceID ?? null,
    domainCircumstances_29107: input.domainCircumstances_29107 ?? null,
    domainCircumstances_29107_ResponseChoiceID: input.domainCircumstances_29107_ResponseChoiceID ?? null,
    ageappropriatedevelopmentScore1Significantnegativeimpactofpoorageappropriatedevelopmentonindep_29109: input.ageappropriatedevelopmentScore1Significantnegativeimpactofpoorageappropriatedevelopmentonindep_29109 ?? null,
    ageappropriatedevelopmentScore1Significantnegativeimpactofpoorageappropriatedevelopmentonindep_29109_ResponseChoiceID: input.ageappropriatedevelopmentScore1Significantnegativeimpactofpoorageappropriatedevelopmentonindep_29109_ResponseChoiceID ?? null,
    communityparticipationnetworksScore1Significantnegativeimpactofpoorcommunityparticipationnetwo_29110: input.communityparticipationnetworksScore1Significantnegativeimpactofpoorcommunityparticipationnetwo_29110 ?? null,
    communityparticipationnetworksScore1Significantnegativeimpactofpoorcommunityparticipationnetwo_29110_ResponseChoiceID: input.communityparticipationnetworksScore1Significantnegativeimpactofpoorcommunityparticipationnetwo_29110_ResponseChoiceID ?? null,
    educationandskillstrainingScore1Significantnegativeimpactoflackofengagementwitheducationandtra_29111: input.educationandskillstrainingScore1Significantnegativeimpactoflackofengagementwitheducationandtra_29111 ?? null,
    educationandskillstrainingScore1Significantnegativeimpactoflackofengagementwitheducationandtra_29111_ResponseChoiceID: input.educationandskillstrainingScore1Significantnegativeimpactoflackofengagementwitheducationandtra_29111_ResponseChoiceID ?? null,
    employmentScore1Significantnegativeimpactoflackofemploymentonindependenceparticipationandwellb_29112: input.employmentScore1Significantnegativeimpactoflackofemploymentonindependenceparticipationandwellb_29112 ?? null,
    employmentScore1Significantnegativeimpactoflackofemploymentonindependenceparticipationandwellb_29112_ResponseChoiceID: input.employmentScore1Significantnegativeimpactoflackofemploymentonindependenceparticipationandwellb_29112_ResponseChoiceID ?? null,
    familyFunctioningScore1Significantnegativeimpactofpoorfamilyfunctioningonindependenceparticipa_29113: input.familyFunctioningScore1Significantnegativeimpactofpoorfamilyfunctioningonindependenceparticipa_29113 ?? null,
    familyFunctioningScore1Significantnegativeimpactofpoorfamilyfunctioningonindependenceparticipa_29113_ResponseChoiceID: input.familyFunctioningScore1Significantnegativeimpactofpoorfamilyfunctioningonindependenceparticipa_29113_ResponseChoiceID ?? null,
    financialresilienceScore1Significantnegativeimpactofpoorfinancialresilienceonindependenceparti_29114: input.financialresilienceScore1Significantnegativeimpactofpoorfinancialresilienceonindependenceparti_29114 ?? null,
    financialresilienceScore1Significantnegativeimpactofpoorfinancialresilienceonindependenceparti_29114_ResponseChoiceID: input.financialresilienceScore1Significantnegativeimpactofpoorfinancialresilienceonindependenceparti_29114_ResponseChoiceID ?? null,
    housingScore1Significantnegativeimpactofpoorhousingonindependenceparticipationandwellbeingegro_29115: input.housingScore1Significantnegativeimpactofpoorhousingonindependenceparticipationandwellbeingegro_29115 ?? null,
    housingScore1Significantnegativeimpactofpoorhousingonindependenceparticipationandwellbeingegro_29115_ResponseChoiceID: input.housingScore1Significantnegativeimpactofpoorhousingonindependenceparticipationandwellbeingegro_29115_ResponseChoiceID ?? null,
    materialwellbeingandbasicnecessitiesScore1Significantnegativeimpactoflackofbasicmaterialresour_29116: input.materialwellbeingandbasicnecessitiesScore1Significantnegativeimpactoflackofbasicmaterialresour_29116 ?? null,
    materialwellbeingandbasicnecessitiesScore1Significantnegativeimpactoflackofbasicmaterialresour_29116_ResponseChoiceID: input.materialwellbeingandbasicnecessitiesScore1Significantnegativeimpactoflackofbasicmaterialresour_29116_ResponseChoiceID ?? null,
    mentalhealthwellbeingandselfcareScore1Significantnegativeimpactofpoormentalhealthwellbeingands_29117: input.mentalhealthwellbeingandselfcareScore1Significantnegativeimpactofpoormentalhealthwellbeingands_29117 ?? null,
    mentalhealthwellbeingandselfcareScore1Significantnegativeimpactofpoormentalhealthwellbeingands_29117_ResponseChoiceID: input.mentalhealthwellbeingandselfcareScore1Significantnegativeimpactofpoormentalhealthwellbeingands_29117_ResponseChoiceID ?? null,
    personalsafetyScore1Significantnegativeimpactofpoorpersonalandfamilysafetyonindependencepartic_29118: input.personalsafetyScore1Significantnegativeimpactofpoorpersonalandfamilysafetyonindependencepartic_29118 ?? null,
    personalsafetyScore1Significantnegativeimpactofpoorpersonalandfamilysafetyonindependencepartic_29118_ResponseChoiceID: input.personalsafetyScore1Significantnegativeimpactofpoorpersonalandfamilysafetyonindependencepartic_29118_ResponseChoiceID ?? null,
    physicalhealthScore1Significantnegativeimpactofpoorphysicalhealthonindependenceparticipationan_29119: input.physicalhealthScore1Significantnegativeimpactofpoorphysicalhealthonindependenceparticipationan_29119 ?? null,
    physicalhealthScore1Significantnegativeimpactofpoorphysicalhealthonindependenceparticipationan_29119_ResponseChoiceID: input.physicalhealthScore1Significantnegativeimpactofpoorphysicalhealthonindependenceparticipationan_29119_ResponseChoiceID ?? null,
    domainSatisfaction_29120: input.domainSatisfaction_29120 ?? null,
    domainSatisfaction_29120_ResponseChoiceID: input.domainSatisfaction_29120_ResponseChoiceID ?? null,
    iambetterabletodealwithissuesthatsoughthelpwith_29122: input.iambetterabletodealwithissuesthatsoughthelpwith_29122 ?? null,
    iambetterabletodealwithissuesthatsoughthelpwith_29122_ResponseChoiceID: input.iambetterabletodealwithissuesthatsoughthelpwith_29122_ResponseChoiceID ?? null,
    iamsatisfiedwiththeservicesIhavereceived_29123: input.iamsatisfiedwiththeservicesIhavereceived_29123 ?? null,
    iamsatisfiedwiththeservicesIhavereceived_29123_ResponseChoiceID: input.iamsatisfiedwiththeservicesIhavereceived_29123_ResponseChoiceID ?? null,
    theservicelistenedtomeandunderstoodmyissues_29124: input.theservicelistenedtomeandunderstoodmyissues_29124 ?? null,
    theservicelistenedtomeandunderstoodmyissues_29124_ResponseChoiceID: input.theservicelistenedtomeandunderstoodmyissues_29124_ResponseChoiceID ?? null,
    partofthisengagementwasareferraldone_29458: input.partofthisengagementwasareferraldone_29458 ?? null,
    partofthisengagementwasareferraldone_29458_ResponseChoiceID: input.partofthisengagementwasareferraldone_29458_ResponseChoiceID ?? null,
    referredto_29459: input.referredto_29459 ?? null,
    scoring_31496: input.scoring_31496 ?? null,
    programName: input.programName ?? null,
    entityName: input.entityName ?? null,
    fName: input.fName ?? null,
    lName: input.lName ?? null
  };
}


export function transformAllLotusNotes(records) {
  const minimalKeys = [
    "formResponseID",
    "responseCreatedDate",
    "auditDate",
    "entityName",
    "scoring_31496"
  ];

  // Map all records to frontend format first
  const mapped = records.map(transformLotusNotes);

  console.log(mapped);

  const minimal = mapped.map(rec =>
    ({
      ...Object.fromEntries(
        minimalKeys.map(key => [key, rec[key]])
      ),
      StaffName: `${rec.fName || ''} ${rec.lName || ''}`.trim(),
    })
  );

  return {
    minimal,
    full: mapped
  };
}