import moment from "moment";

/**
 * Map all aihwform record fields for full detail view.
 */
export function transformMSU(record) {
  return {
    // Identifiers
formResponseID:record.formResponseID,
formIdentifier:record.formIdentifier,
subjectID:record.subjectID,
groupID:record.groupID,
familyID:record.familyID,
responseSetID:record.responseSetID,
formID:record.formID,
collectionTypeID:record.collectionTypeID,
subjectTypeID:record.subjectTypeID,
collectionID:record.collectionID,
responseCreatedDate:record.responseCreatedDate,
programID:record.programID,
auditStaffID:record.auditStaffID,
auditDate:record.auditDate,
dataEnteredByID:record.dataEnteredByID,
draftSavedOn:record.draftSavedOn,
removedDate:record.removedDate,
dwellingType_16392:record.dwellingType_16392,
dwellingType_16392_ResponseChoiceID:record.dwellingType_16392_ResponseChoiceID,
episodeOfHomelessness_16393:record.episodeOfHomelessness_16393,
episodeOfHomelessness_16393_ResponseChoiceID:record.episodeOfHomelessness_16393_ResponseChoiceID,
ifTheParticipantIsUnderTheAgeOf18AndHasACareOrProtectionOrderWhatWereTheirCareArrangements_16394:record.ifTheParticipantIsUnderTheAgeOf18AndHasACareOrProtectionOrderWhatWereTheirCareArrangements_16394,
ifTheParticipantIsUnderTheAgeOf18AndHasACareOrProtectionOrderWhatWereTheirCareArrangements_16394_ResponseChoiceID:record.ifTheParticipantIsUnderTheAgeOf18AndHasACareOrProtectionOrderWhatWereTheirCareArrangements_16394_ResponseChoiceID,
livingArrangements_16395:record.livingArrangements_16395,
livingArrangements_16395_ResponseChoiceID:record.livingArrangements_16395_ResponseChoiceID,
conditionsOfOccupancy_16396:record.conditionsOfOccupancy_16396,
conditionsOfOccupancy_16396_ResponseChoiceID:record.conditionsOfOccupancy_16396_ResponseChoiceID,
labourForceStatus_16397:record.labourForceStatus_16397,
labourForceStatus_16397_ResponseChoiceID:record.labourForceStatus_16397_ResponseChoiceID,
ifTheParticipantIs15yrsWhatIsTheirEmploymentStatus_16398:record.ifTheParticipantIs15yrsWhatIsTheirEmploymentStatus_16398,
ifTheParticipantIs15yrsWhatIsTheirEmploymentStatus_16398_ResponseChoiceID:record.ifTheParticipantIs15yrsWhatIsTheirEmploymentStatus_16398_ResponseChoiceID,
mainSourceOfIncome_16399:record.mainSourceOfIncome_16399,
mainSourceOfIncome_16399_ResponseChoiceID:record.mainSourceOfIncome_16399_ResponseChoiceID,
isTheParticipantCurrentlyRegisteredForAGovernmentBenefitPensionOrAllowanceButAwaitingTheFirstP_16400:record.isTheParticipantCurrentlyRegisteredForAGovernmentBenefitPensionOrAllowanceButAwaitingTheFirstP_16400,
isTheParticipantCurrentlyRegisteredForAGovernmentBenefitPensionOrAllowanceButAwaitingTheFirstP_16400_ResponseChoiceID:record.isTheParticipantCurrentlyRegisteredForAGovernmentBenefitPensionOrAllowanceButAwaitingTheFirstP_16400_ResponseChoiceID,
isTheParticipantUndertakingFormalStudyOrTrainingEgSchoolUniversityVocationalStudiesSuchAsTafe_16401:record.isTheParticipantUndertakingFormalStudyOrTrainingEgSchoolUniversityVocationalStudiesSuchAsTafe_16401,
isTheParticipantUndertakingFormalStudyOrTrainingEgSchoolUniversityVocationalStudiesSuchAsTafe_16401_ResponseChoiceID:record.isTheParticipantUndertakingFormalStudyOrTrainingEgSchoolUniversityVocationalStudiesSuchAsTafe_16401_ResponseChoiceID,
tenure_16402:record.tenure_16402,
tenure_16402_ResponseChoiceID:record.tenure_16402_ResponseChoiceID,
doesThePublicTrusteeAdministerTheParticipantsPersonalFinancesMp_16420:record.doesThePublicTrusteeAdministerTheParticipantsPersonalFinancesMp_16420,
doesThePublicTrusteeAdministerTheParticipantsPersonalFinancesMp_16420_ResponseChoiceID:record.doesThePublicTrusteeAdministerTheParticipantsPersonalFinancesMp_16420_ResponseChoiceID,
whatTypeOfEducationtrainingIsTheParticipantEnrolledIn_16426:record.whatTypeOfEducationtrainingIsTheParticipantEnrolledIn_16426,
whatTypeOfEducationtrainingIsTheParticipantEnrolledIn_16426_ResponseChoiceID:record.whatTypeOfEducationtrainingIsTheParticipantEnrolledIn_16426_ResponseChoiceID,
micahTeam_16473:record.micahTeam_16473,
selectYourName_16475:record.selectYourName_16475,
atIntakeThisCareArrangementsQuestionWasAnsweredAs_16477:record.atIntakeThisCareArrangementsQuestionWasAnsweredAs_16477,
atIntakeThisCareArrangementsQuestionWasAnsweredAs_16477_DisplayStr:record.atIntakeThisCareArrangementsQuestionWasAnsweredAs_16477_DisplayStr,
atIntakeThisHomelessnessQuestionWasAnsweredAs_16478:record.atIntakeThisHomelessnessQuestionWasAnsweredAs_16478,
atIntakeThisHomelessnessQuestionWasAnsweredAs_16478_DisplayStr:record.atIntakeThisHomelessnessQuestionWasAnsweredAs_16478_DisplayStr,
atIntakeThisPublicGuardianQuestionWasAnsweredAs_16479:record.atIntakeThisPublicGuardianQuestionWasAnsweredAs_16479,
atIntakeThisPublicGuardianQuestionWasAnsweredAs_16479_DisplayStr:record.atIntakeThisPublicGuardianQuestionWasAnsweredAs_16479_DisplayStr,
atIntakeThisPublicTrusteeQuestionWasAnsweredAs_16480:record.atIntakeThisPublicTrusteeQuestionWasAnsweredAs_16480,
atIntakeThisPublicTrusteeQuestionWasAnsweredAs_16480_DisplayStr:record.atIntakeThisPublicTrusteeQuestionWasAnsweredAs_16480_DisplayStr,
atIntakeLivingArrangementsWasAnsweredAs_16481:record.atIntakeLivingArrangementsWasAnsweredAs_16481,
atIntakeLivingArrangementsWasAnsweredAs_16481_DisplayStr:record.atIntakeLivingArrangementsWasAnsweredAs_16481_DisplayStr,
atIntakeDwellingTypeWasAnsweredAs_16482:record.atIntakeDwellingTypeWasAnsweredAs_16482,
atIntakeDwellingTypeWasAnsweredAs_16482_DisplayStr:record.atIntakeDwellingTypeWasAnsweredAs_16482_DisplayStr,
atIntakeTenureWasAnsweredAs_16483:record.atIntakeTenureWasAnsweredAs_16483,
atIntakeTenureWasAnsweredAs_16483_DisplayStr:record.atIntakeTenureWasAnsweredAs_16483_DisplayStr,
atIntakeConditionOfOccupancyWasAnsweredAs_16484:record.atIntakeConditionOfOccupancyWasAnsweredAs_16484,
atIntakeConditionOfOccupancyWasAnsweredAs_16484_DisplayStr:record.atIntakeConditionOfOccupancyWasAnsweredAs_16484_DisplayStr,
atIntakeLabourForceStatusWasAnsweredAs_16485:record.atIntakeLabourForceStatusWasAnsweredAs_16485,
atIntakeLabourForceStatusWasAnsweredAs_16485_DisplayStr:record.atIntakeLabourForceStatusWasAnsweredAs_16485_DisplayStr,
atIntakeEmploymentStatusWasAnsweredAs_16486:record.atIntakeEmploymentStatusWasAnsweredAs_16486,
atIntakeEmploymentStatusWasAnsweredAs_16486_DisplayStr:record.atIntakeEmploymentStatusWasAnsweredAs_16486_DisplayStr,
atIntakeMainSourceOfIncomeWasAnsweredAs_16487:record.atIntakeMainSourceOfIncomeWasAnsweredAs_16487,
atIntakeMainSourceOfIncomeWasAnsweredAs_16487_DisplayStr:record.atIntakeMainSourceOfIncomeWasAnsweredAs_16487_DisplayStr,
atIntakeCurrentlyRegisteredAndAwaitingFirstPaymentWasAnsweredAs_16488:record.atIntakeCurrentlyRegisteredAndAwaitingFirstPaymentWasAnsweredAs_16488,
atIntakeCurrentlyRegisteredAndAwaitingFirstPaymentWasAnsweredAs_16488_DisplayStr:record.atIntakeCurrentlyRegisteredAndAwaitingFirstPaymentWasAnsweredAs_16488_DisplayStr,
atIntakeUndertakingFormalTrainingWasAnsweredAs_16489:record.atIntakeUndertakingFormalTrainingWasAnsweredAs_16489,
atIntakeUndertakingFormalTrainingWasAnsweredAs_16489_DisplayStr:record.atIntakeUndertakingFormalTrainingWasAnsweredAs_16489_DisplayStr,
atIntakeEnrolledEducationtrainingWasAnsweredAs_16490:record.atIntakeEnrolledEducationtrainingWasAnsweredAs_16490,
atIntakeEnrolledEducationtrainingWasAnsweredAs_16490_DisplayStr:record.atIntakeEnrolledEducationtrainingWasAnsweredAs_16490_DisplayStr,
doyouhaveanappointedsubstitutedecisionmakermp_16498:record.doyouhaveanappointedsubstitutedecisionmakermp_16498,
doyouhaveanappointedsubstitutedecisionmakermp_16498_ResponseChoiceID:record.doyouhaveanappointedsubstitutedecisionmakermp_16498_ResponseChoiceID,
selectwhichgoalmostreflectstheprogressofthesupportmanagementplaniftherearenocurrentgoalsleavet_16500:record.selectwhichgoalmostreflectstheprogressofthesupportmanagementplaniftherearenocurrentgoalsleavet_16500,
selectwhichgoalmostreflectstheprogressofthesupportmanagementplaniftherearenocurrentgoalsleavet_16500_SourceFormID:record.selectwhichgoalmostreflectstheprogressofthesupportmanagementplaniftherearenocurrentgoalsleavet_16500_SourceFormID,
selectwhichgoalmostreflectstheprogressofthesupportmanagementplaniftherearenocurrentgoalsleavet_16500_DisplayStr:record.selectwhichgoalmostreflectstheprogressofthesupportmanagementplaniftherearenocurrentgoalsleavet_16500_DisplayStr,
youindicatedthattherearenocurrentopengoalsforthisparticipantIndicatereason_16501:record.youindicatedthattherearenocurrentopengoalsforthisparticipantIndicatereason_16501,
youindicatedthattherearenocurrentopengoalsforthisparticipantIndicatereason_16501_ResponseChoiceID:record.youindicatedthattherearenocurrentopengoalsforthisparticipantIndicatereason_16501_ResponseChoiceID,
ifotherreasonpleasespecify_16502:record.ifotherreasonpleasespecify_16502,
thinkingaboutthegoalyouselectedandothergoalstowhatextentweretheparticipantsmanagementplangoals_16503:record.thinkingaboutthegoalyouselectedandothergoalstowhatextentweretheparticipantsmanagementplangoals_16503,
thinkingaboutthegoalyouselectedandothergoalstowhatextentweretheparticipantsmanagementplangoals_16503_ResponseChoiceID:record.thinkingaboutthegoalyouselectedandothergoalstowhatextentweretheparticipantsmanagementplangoals_16503_ResponseChoiceID,
wasthereacasemanagementplanfortheparticipant_16504:record.wasthereacasemanagementplanfortheparticipant_16504,
wasthereacasemanagementplanfortheparticipant_16504_ResponseChoiceID:record.wasthereacasemanagementplanfortheparticipant_16504_ResponseChoiceID,
age_16522:record.age_16522,
submitsSHSAIHWreports_21833:record.submitsSHSAIHWreports_21833,
timespentonbehalfofparticipantPerstaffmember_23288:record.timespentonbehalfofparticipantPerstaffmember_23288,
howmanystaffdidthistogetherAtmost4_23289:record.howmanystaffdidthistogetherAtmost4_23289,
totaltimespentonbehalfofparticipant_23290:record.totaltimespentonbehalfofparticipant_23290,
hastheparticipantreturnedhome_28343:record.hastheparticipantreturnedhome_28343,
hastheparticipantreturnedhome_28343_ResponseChoiceID:record.hastheparticipantreturnedhome_28343_ResponseChoiceID,
participantAge_29347:record.participantAge_29347,
totalefforttimeforparticipant_33292:record.totalefforttimeforparticipant_33292
  };
}


export function transformmsu(records) {
  const minimalKeys = [
    "labourForceStatus_16397",
    "micahTeam_16473",    
    "age_16522",
    "totalefforttimeforparticipant_33292"
    
  ];

  // Map all records to frontend format first
  const mapped = records.map(transformMSU);

  // Then extract minimal information from mapped records
  const minimal = mapped.map(rec =>
    ({
      ...Object.fromEntries(
        minimalKeys.map(key => [key, rec[key]])
      ),
      StaffName: `${rec.fName || ''} ${rec.lName || ''}`.trim(),
    })
  );

  return {
    minimal,
    full: mapped
  };
}