using System.Collections.Generic;
using System.Threading.Tasks;
using EtoApi.Models;
using Microsoft.Data.SqlClient;

namespace EtoApi.DataAccess
{
    public class AddressBookRepository
    {
       private readonly ISqlConnectionFactory _connectionFactory;

        public AddressBookRepository(ISqlConnectionFactory connectionFactory)
            {
                _connectionFactory = connectionFactory;
            }

        public async Task<List<AddressBook>> GetAddressBookByIdAsync(int id, int programCode)
        {
             using var connection = await _connectionFactory.CreateOpenConnectionAsync();

            var query = @"
                SELECT
                FormResponseID,
                FormIdentifier,
                SubjectID,
                GroupID,
                FamilyID,
                ResponseSetID,
                FormID,
                CollectionTypeID,
                SubjectTypeID,
                CollectionID,
                ResponseCreatedDate,
                frm.ProgramID,
                frm.AuditStaffID,
                frm.AuditDate,
                DataEnteredByID,
                DraftSavedOn,
                RemovedDate,
                DateThisPersonBecameTheNextOfKin_9372,
                Name_9373,
                Address_9374,
                Relationship_9376,
                Relationship_9376_ResponseChoiceID,
                PermissionToContactNextOfKinIfRequired_9377,
                PermissionToContactNextOfKinIfRequired_9377_ResponseChoiceID,
                Organisation_9444,
                Role_9446,
                ApartmentunitNumber_9458,
                StreetNumber_9459,
                StreetName_9460,
                Suburblocality_9461,
                State_9462,
                IsThisChildInYourFullTimeCare_9467,
                IsThisChildInYourFullTimeCare_9467_ResponseChoiceID,
                Dob_9475,
                Gender_9477,
                Gender_9477_ResponseChoiceID,
                CareDetails_9479,
                ChildRelationship_9505,
                ChildRelationship_9505_ResponseChoiceID,
                WhoseContactDetailsarethese_9521,
                WhoseContactDetailsarethese_9521_ResponseChoiceID,
                MobilePhone_9523,
                WorkPhone_9525,
                HomePhone_9526,
                SelectparticipantinETO_9529,
                DatethispersonceasedbeingNextofKin_9530,
                IsthisthecurrentNextofKin_9533,
                IsthisthecurrentNextofKin_9533_ResponseChoiceID,
                CommentsNotes_9534,
                Email_9535,
                ApartmentUnitNo_10903,
                StreetNumber_10904,
                StreetName_10905,
                Suburb_10906,
                PostCode_10910,
                POBox_10911,
                HousingProvider_11403,
                DatethisbecameHousingProvider_12590,
                DatethisceasedasHousingProvider_12591,
                Whendidtheparticipantbegintoresideatthisaddress_12911,
                WhendidtheparticipantceaseresidingatthisaddressLeaveblankifcurrentaddress_12912,
                SelectGeneralPractitioner_13123,
                DatethisbecameyourGP_13127,
                DatethisceasedbeingyourGP_13128,
                WhatistheState_13303,
                WhatistheState_13303_ResponseChoiceID,
                SafetocallM_13306,
                SafetocallM_13306_ResponseChoiceID,
                SafetocallW_13307,
                SafetocallW_13307_ResponseChoiceID,
                SafetocallH_13308,
                SafetocallH_13308_ResponseChoiceID,
                Notescommentsaboutphonesemail_13309,
                IsthispersonaprivateguardianfortheparticipantappointedbytheQueenslandCivilandAdministrativeTri_16831,
                IsthispersonaprivateguardianfortheparticipantappointedbytheQueenslandCivilandAdministrativeTri_16831_ResponseChoiceID,
                Datethispersonbecameaprivateguardian_16832,
                DatethispersonceasedbeingaPrivateGuardian_16833,
                Isthispersonaninformaldecisionmakeronbehalfoftheparticipant_16834,
                Isthispersonaninformaldecisionmakeronbehalfoftheparticipant_16834_ResponseChoiceID,
                Datethispersonbecameaninformaldecisionmaker_16835,
                Datethispersonceasedbeinganinformaldecisionmaker_16836,
                ContactatPublicGuardian_16851,
                AttorneyunderEnduringPowerofAttorneyorAdvanceHealthDirective_16855,
                StatutoryHealthAttorney_16857,
                DatethisentitybecameaSubstituteDecisionMaker_16865,
                DatethisentityceasedbeingaSubstituteDecisionMakerleaveblankifcurrent_16866,
                SafetoM_16872,
                SafetoM_16872_ResponseChoiceID,
                SafetoW_16873,
                SafetoW_16873_ResponseChoiceID,
                SafetoH_16874,
                SafetoH_16874_ResponseChoiceID,
                SelectHealthSpecialist_17361,
                ProgramName_19776,
                Address1_19777,
                Address2_19779,
                AusSuburbLocality_19780,
                StateAus_19781,
                AusPostalCode_19782,
                AusPhoneNumber_19783,
                Address1_19785,
                Address2_19786,
                AusSuburbLocality_19787,
                StateAus_19788,
                AusPostalCode_19789,
                AusPhoneNumber_19790,
                Address1_19792,
                Address2_19793,
                AusSuburbLocality_19794,
                StateAus_19795,
                AusPostalCode_19796,
                AusPhoneNumber_19797,
                Address1_19799,
                Address2_19800,
                AusSuburbLocality_19801,
                StateAus_19802,
                AusPostalCode_19803,
                AusPhoneNumber_19804,
                PostCodet_20568,
                IsthisthecurrentEmergencyContact_21680,
                IsthisthecurrentEmergencyContact_21680_ResponseChoiceID,
                Addressbookstatus_23962,
                DatethiscontactbecameNoncurrent_25349,
                AccommodationType_27221,
                AccommodationType_27221_ResponseChoiceID,
                IfotherPleasespecify_27223,
                WhichHostelBoardinghouseisit_27224,
                Isthisa_27225,
                Isthisa_27225_ResponseChoiceID,
                UsethisaddressforDRCDEXsubmission_28230,
                UsethisaddressforDRCDEXsubmission_28230_ResponseChoiceID,
                KeyNumber_28234,
                SuburbandPostCode_28290,
                Datethisceasedasserviceprovider_29299
                FROM form.f_236 frm
                Join ClientsXPrograms cp ON cp.CLID = @Id and cp.ProgramID = @programCode
                WHERE frm.SubjectID = (SELECT SubjectID FROM SubjectXClient WHERE CLID = @Id)";

            using var command = new SqlCommand(query, connection);
            command.Parameters.AddWithValue("@Id", id);
            command.Parameters.AddWithValue("@programCode", programCode);

            var addressBooks = new List<AddressBook>();
            using var reader = await command.ExecuteReaderAsync();

            while (await reader.ReadAsync())
{
    addressBooks.Add(new AddressBook
    {
        FormResponseID = reader.IsDBNull(0) ? (int?)null : reader.GetInt32(0),
        FormIdentifier = reader.IsDBNull(1) ? (int?)null : reader.GetInt32(1),
        SubjectID = reader.IsDBNull(2) ? (int?)null : reader.GetInt32(2),
        GroupID = reader.IsDBNull(3) ? (int?)null : reader.GetInt32(3),
        FamilyID = reader.IsDBNull(4) ? (int?)null : reader.GetInt32(4),
        ResponseSetID = reader.IsDBNull(5) ? (int?)null : reader.GetInt32(5),
        FormID = reader.IsDBNull(6) ? (int?)null : reader.GetInt32(6),
        CollectionTypeID = reader.IsDBNull(7) ? (int?)null : reader.GetInt32(7),
        SubjectTypeID = reader.IsDBNull(8) ? (int?)null : reader.GetInt32(8),
        CollectionID = reader.IsDBNull(9) ? (int?)null : reader.GetInt32(9),
        ResponseCreatedDate = reader.IsDBNull(10) ? (DateTime?)null : reader.GetDateTime(10),
        ProgramID = reader.IsDBNull(11) ? (int?)null : reader.GetInt16(11),
        AuditStaffID = reader.IsDBNull(12) ? (int?)null : reader.GetInt32(12),
        AuditDate = reader.IsDBNull(13) ? (DateTime?)null : reader.GetDateTime(13),
        DataEnteredByID = reader.IsDBNull(14) ? (int?)null : reader.GetInt32(14),
        DraftSavedOn = reader.IsDBNull(15) ? (DateTime?)null : reader.GetDateTime(15),
        RemovedDate = reader.IsDBNull(16) ? (DateTime?)null : reader.GetDateTime(16),
        DateThisPersonBecameTheNextOfKin_9372 = reader.IsDBNull(17) ? (DateTime?)null : reader.GetDateTime(17),
        Name_9373 = reader.IsDBNull(18) ? null : reader.GetString(18),
        Address_9374 = reader.IsDBNull(19) ? null : reader.GetString(19),
        Relationship_9376 = reader.IsDBNull(20) ? null : reader.GetString(20),
        Relationship_9376_ResponseChoiceID = reader.IsDBNull(21) ? (int?)null : reader.GetInt32(21),
        PermissionToContactNextOfKinIfRequired_9377 = reader.IsDBNull(22) ? null : reader.GetString(22),
        PermissionToContactNextOfKinIfRequired_9377_ResponseChoiceID = reader.IsDBNull(23) ? (int?)null : reader.GetInt32(23),
        Organisation_9444 = reader.IsDBNull(24) ? (int?)null : reader.GetInt32(24),
        Role_9446 = reader.IsDBNull(25) ? null : reader.GetString(25),
        ApartmentunitNumber_9458 = reader.IsDBNull(26) ? null : reader.GetString(26),
        StreetNumber_9459 = reader.IsDBNull(27) ? null : reader.GetString(27),
        StreetName_9460 = reader.IsDBNull(28) ? null : reader.GetString(28),
        Suburblocality_9461 = reader.IsDBNull(29) ? null : reader.GetString(29),
        State_9462 = reader.IsDBNull(30) ? null : reader.GetString(30),
        IsThisChildInYourFullTimeCare_9467 = reader.IsDBNull(31) ? null : reader.GetString(31),
        IsThisChildInYourFullTimeCare_9467_ResponseChoiceID = reader.IsDBNull(32) ? (int?)null : reader.GetInt32(32),
        Dob_9475 = reader.IsDBNull(33) ? (DateTime?)null : reader.GetDateTime(33),
        Gender_9477 = reader.IsDBNull(34) ? null : reader.GetString(34),
        Gender_9477_ResponseChoiceID = reader.IsDBNull(35) ? (int?)null : reader.GetInt32(35),
        CareDetails_9479 = reader.IsDBNull(36) ? null : reader.GetString(36),
        ChildRelationship_9505 = reader.IsDBNull(37) ? null : reader.GetString(37),
        ChildRelationship_9505_ResponseChoiceID = reader.IsDBNull(38) ? (int?)null : reader.GetInt32(38),
        WhoseContactDetailsarethese_9521 = reader.IsDBNull(39) ? null : reader.GetString(39),
        WhoseContactDetailsarethese_9521_ResponseChoiceID = reader.IsDBNull(40) ? (int?)null : reader.GetInt32(40),
        MobilePhone_9523 = reader.IsDBNull(41) ? null : reader.GetString(41),
        WorkPhone_9525 = reader.IsDBNull(42) ? null : reader.GetString(42),
        HomePhone_9526 = reader.IsDBNull(43) ? null : reader.GetString(43),
        SelectparticipantinETO_9529 = reader.IsDBNull(44) ? (int?)null : reader.GetInt32(44),
        DatethispersonceasedbeingNextofKin_9530 = reader.IsDBNull(45) ? (DateTime?)null : reader.GetDateTime(45),
        IsthisthecurrentNextofKin_9533 = reader.IsDBNull(46) ? null : reader.GetString(46),
        IsthisthecurrentNextofKin_9533_ResponseChoiceID = reader.IsDBNull(47) ? (int?)null : reader.GetInt32(47),
        CommentsNotes_9534 = reader.IsDBNull(48) ? null : reader.GetString(48),
        Email_9535 = reader.IsDBNull(49) ? null : reader.GetString(49),
        ApartmentUnitNo_10903 = reader.IsDBNull(50) ? null : reader.GetString(50),
        StreetNumber_10904 = reader.IsDBNull(51) ? null : reader.GetString(51),
        StreetName_10905 = reader.IsDBNull(52) ? null : reader.GetString(52),
        Suburb_10906 = reader.IsDBNull(53) ? null : reader.GetString(53),
        PostCode_10910 = reader.IsDBNull(54) ? null : reader.GetString(54),
        POBox_10911 = reader.IsDBNull(55) ? null : reader.GetString(55),
        HousingProvider_11403 = reader.IsDBNull(56) ? (int?)null : reader.GetInt32(56),
        DatethisbecameHousingProvider_12590 = reader.IsDBNull(57) ? (DateTime?)null : reader.GetDateTime(57),
        DatethisceasedasHousingProvider_12591 = reader.IsDBNull(58) ? (DateTime?)null : reader.GetDateTime(58),
        Whendidtheparticipantbegintoresideatthisaddress_12911 = reader.IsDBNull(59) ? (DateTime?)null : reader.GetDateTime(59),
        WhendidtheparticipantceaseresidingatthisaddressLeaveblankifcurrentaddress_12912 = reader.IsDBNull(60) ? (DateTime?)null : reader.GetDateTime(60),
        SelectGeneralPractitioner_13123 = reader.IsDBNull(61) ? (int?)null : reader.GetInt32(61),
        DatethisbecameyourGP_13127 = reader.IsDBNull(62) ? (DateTime?)null : reader.GetDateTime(62),
        DatethisceasedbeingyourGP_13128 = reader.IsDBNull(63) ? (DateTime?)null : reader.GetDateTime(63),
        WhatistheState_13303 = reader.IsDBNull(64) ? null : reader.GetString(64),
        WhatistheState_13303_ResponseChoiceID = reader.IsDBNull(65) ? (int?)null : reader.GetInt32(65),
        SafetocallM_13306 = reader.IsDBNull(66) ? null : reader.GetString(66),
        SafetocallM_13306_ResponseChoiceID = reader.IsDBNull(67) ? (int?)null : reader.GetInt32(67),
        SafetocallW_13307 = reader.IsDBNull(68) ? null : reader.GetString(68),
        SafetocallW_13307_ResponseChoiceID = reader.IsDBNull(69) ? (int?)null : reader.GetInt32(69),
        SafetocallH_13308 = reader.IsDBNull(70) ? null : reader.GetString(70),
        SafetocallH_13308_ResponseChoiceID = reader.IsDBNull(71) ? (int?)null : reader.GetInt32(71),
        Notescommentsaboutphonesemail_13309 = reader.IsDBNull(72) ? null : reader.GetString(72),
        IsthispersonaprivateguardianfortheparticipantappointedbytheQueenslandCivilandAdministrativeTri_16831 = reader.IsDBNull(73) ? null : reader.GetString(73),
        IsthispersonaprivateguardianfortheparticipantappointedbytheQueenslandCivilandAdministrativeTri_16831_ResponseChoiceID = reader.IsDBNull(74) ? (int?)null : reader.GetInt32(74),
        Datethispersonbecameaprivateguardian_16832 = reader.IsDBNull(75) ? (DateTime?)null : reader.GetDateTime(75),
        DatethispersonceasedbeingaPrivateGuardian_16833 = reader.IsDBNull(76) ? (DateTime?)null : reader.GetDateTime(76),
        Isthispersonaninformaldecisionmakeronbehalfoftheparticipant_16834 = reader.IsDBNull(77) ? null : reader.GetString(77),
        Isthispersonaninformaldecisionmakeronbehalfoftheparticipant_16834_ResponseChoiceID = reader.IsDBNull(78) ? (int?)null : reader.GetInt32(78),
        Datethispersonbecameaninformaldecisionmaker_16835 = reader.IsDBNull(79) ? (DateTime?)null : reader.GetDateTime(79),
        Datethispersonceasedbeinganinformaldecisionmaker_16836 = reader.IsDBNull(80) ? (DateTime?)null : reader.GetDateTime(80),
        ContactatPublicGuardian_16851 = reader.IsDBNull(81) ? (int?)null : reader.GetInt32(81),
        AttorneyunderEnduringPowerofAttorneyorAdvanceHealthDirective_16855 = reader.IsDBNull(82) ? null : reader.GetString(82),
        StatutoryHealthAttorney_16857 = reader.IsDBNull(83) ? (int?)null : reader.GetInt32(83),
        DatethisentitybecameaSubstituteDecisionMaker_16865 = reader.IsDBNull(84) ? (DateTime?)null : reader.GetDateTime(84),
        DatethisentityceasedbeingaSubstituteDecisionMakerleaveblankifcurrent_16866 = reader.IsDBNull(85) ? (DateTime?)null : reader.GetDateTime(85),
        SafetoM_16872 = reader.IsDBNull(86) ? null : reader.GetString(86),
        SafetoM_16872_ResponseChoiceID = reader.IsDBNull(87) ? (int?)null : reader.GetInt32(87),
        SafetoW_16873 = reader.IsDBNull(88) ? null : reader.GetString(88),
        SafetoW_16873_ResponseChoiceID = reader.IsDBNull(89) ? (int?)null : reader.GetInt32(89),
        SafetoH_16874 = reader.IsDBNull(90) ? null : reader.GetString(90),
        SafetoH_16874_ResponseChoiceID = reader.IsDBNull(91) ? (int?)null : reader.GetInt32(91),
        SelectHealthSpecialist_17361 = reader.IsDBNull(92) ? (int?)null : reader.GetInt32(92),
        ProgramName_19776 = reader.IsDBNull(93) ? null : reader.GetString(93),
        Address1_19777 = reader.IsDBNull(94) ? null : reader.GetString(94),
        Address2_19779 = reader.IsDBNull(95) ? null : reader.GetString(95),
        AusSuburbLocality_19780 = reader.IsDBNull(96) ? null : reader.GetString(96),
        StateAus_19781 = reader.IsDBNull(97) ? null : reader.GetString(97),
        AusPostalCode_19782 = reader.IsDBNull(98) ? null : reader.GetString(98),
        AusPhoneNumber_19783 = reader.IsDBNull(99) ? null : reader.GetString(99),
        Address1_19785 = reader.IsDBNull(100) ? null : reader.GetString(100),
        Address2_19786 = reader.IsDBNull(101) ? null : reader.GetString(101),
        AusSuburbLocality_19787 = reader.IsDBNull(102) ? null : reader.GetString(102),
        StateAus_19788 = reader.IsDBNull(103) ? null : reader.GetString(103),
        AusPostalCode_19789 = reader.IsDBNull(104) ? null : reader.GetString(104),
        AusPhoneNumber_19790 = reader.IsDBNull(105) ? null : reader.GetString(105),
        Address1_19792 = reader.IsDBNull(106) ? null : reader.GetString(106),
        Address2_19793 = reader.IsDBNull(107) ? null : reader.GetString(107),
        AusSuburbLocality_19794 = reader.IsDBNull(108) ? null : reader.GetString(108),
        StateAus_19795 = reader.IsDBNull(109) ? null : reader.GetString(109),
        AusPostalCode_19796 = reader.IsDBNull(110) ? null : reader.GetString(110),
        AusPhoneNumber_19797 = reader.IsDBNull(111) ? null : reader.GetString(111),
        Address1_19799 = reader.IsDBNull(112) ? null : reader.GetString(112),
        Address2_19800 = reader.IsDBNull(113) ? null : reader.GetString(113),
        AusSuburbLocality_19801 = reader.IsDBNull(114) ? null : reader.GetString(114),
        StateAus_19802 = reader.IsDBNull(115) ? null : reader.GetString(115),
        AusPostalCode_19803 = reader.IsDBNull(116) ? null : reader.GetString(116),
        AusPhoneNumber_19804 = reader.IsDBNull(117) ? null : reader.GetString(117),
        PostCodet_20568 = reader.IsDBNull(118) ? null : reader.GetString(118),
        IsthisthecurrentEmergencyContact_21680 = reader.IsDBNull(119) ? null : reader.GetString(119),
        IsthisthecurrentEmergencyContact_21680_ResponseChoiceID = reader.IsDBNull(120) ? (int?)null : reader.GetInt32(120),
        Addressbookstatus_23962 = reader.IsDBNull(121) ? null : reader.GetString(121),
        DatethiscontactbecameNoncurrent_25349 = reader.IsDBNull(122) ? (DateTime?)null : reader.GetDateTime(122),
        AccommodationType_27221 = reader.IsDBNull(123) ? null : reader.GetString(123),
        AccommodationType_27221_ResponseChoiceID = reader.IsDBNull(124) ? (int?)null : reader.GetInt32(124),
        IfotherPleasespecify_27223 = reader.IsDBNull(125) ? null : reader.GetString(125),
        WhichHostelBoardinghouseisit_27224 = reader.IsDBNull(126) ? (int?)null : reader.GetInt32(126),
        Isthisa_27225 = reader.IsDBNull(127) ? null : reader.GetString(127),
        Isthisa_27225_ResponseChoiceID = reader.IsDBNull(128) ? (int?)null : reader.GetInt32(128),
        UsethisaddressforDRCDEXsubmission_28230 = reader.IsDBNull(129) ? null : reader.GetString(129),
        UsethisaddressforDRCDEXsubmission_28230_ResponseChoiceID = reader.IsDBNull(130) ? (int?)null : reader.GetInt32(130),
        KeyNumber_28234 = reader.IsDBNull(131) ? null : reader.GetString(131),
        SuburbandPostCode_28290 = reader.IsDBNull(132) ? (int?)null : reader.GetInt32(132),
        Datethisceasedasserviceprovider_29299 = reader.IsDBNull(133) ? (DateTime?)null : reader.GetDateTime(133)
    });
}
            return addressBooks;
        }
    }
}
