using EtoApi.Models;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Data.SqlClient;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace EtoApi.DataAccess
{
    public class AIHWFormRepository
    {
        
        private readonly ISqlConnectionFactory _connectionFactory;
        
        public AIHWFormRepository(ISqlConnectionFactory connectionFactory)
        {
            _connectionFactory = connectionFactory;
        }
        
        public async Task<List<AIHWFormModel>> GetAIHWFormByIdAsync(int id)
        {
            
            using var connection = await _connectionFactory.CreateOpenConnectionAsync();

            var query = @"
                SELECT
                    frm.FormResponseID,
                    frm.FormIdentifier,
                    frm.SubjectID,
                    frm.GroupID,
                    frm.FamilyID,
                    frm.ResponseSetID,
                    frm.FormID,
                    frm.CollectionTypeID,
                    sub.SubjectTypeID,
                    frm.CollectionID,
                    frm.ResponseCreatedDate,
                    frm.ProgramID,
                    frm.AuditStaffID,
                    frm.AuditDate,
                    frm.DataEnteredByID,
                    frm.DraftSavedOn,
                    frm.RemovedDate,
                    frm.WhatReasonsDoesTheParticipantReportForSeekingAssistance_14662,
                    frm.WhatReasonsDoesTheParticipantReportForSeekingAssistance_14662_ResponseChoiceID,
                    frm.WhatOtherReasonsDoesTheParticipantReportForSeekingAssistance_14663,
                    frm.IfYourSafetyOrThatOfYourFamilyIsAConcernForYouWouldYouLikeHelpToImproveYourSafety_14664,
                    frm.IfYourSafetyOrThatOfYourFamilyIsAConcernForYouWouldYouLikeHelpToImproveYourSafety_14664_ResponseChoiceID,
                    frm.IfThisParticipantHasACareOrProtectionOrderWhatWereTheCareArrangementsTheWeekBeforePresentingFo_14669,
                    frm.IfThisParticipantHasACareOrProtectionOrderWhatWereTheCareArrangementsTheWeekBeforePresentingFo_14669_ResponseChoiceID,
                    frm.IfThisParticipantHasACareOrProtectionOrderWhatWereTheCareArrangementsWhenPresentingForEachFami_14670,
                    frm.IfThisParticipantHasACareOrProtectionOrderWhatWereTheCareArrangementsWhenPresentingForEachFami_14670_ResponseChoiceID,
                    frm.HaveYouBeenInAnyOfTheseInstitutionsOrFacilitiesInTheLast12MonthsforEachFamilyMember_14671,
                    frm.HaveYouBeenInAnyOfTheseInstitutionsOrFacilitiesInTheLast12MonthsforEachFamilyMember_14671_ResponseChoiceID,
                    frm.DoYouHaveAPhysicalHealthConditionDiagnosedByAHealthProfessionalMp_14673,
                    frm.DoYouHaveAPhysicalHealthConditionDiagnosedByAHealthProfessionalMp_14673_ResponseChoiceID,
                    frm.IfYouHaveADiagnosedPhysicalHealthConditionDetailsMp_14674,
                    frm.DoYouHaveAMentalHealthConditionDiagnosedByAHealthProfessional_14675,
                    frm.DoYouHaveAMentalHealthConditionDiagnosedByAHealthProfessional_14675_ResponseChoiceID,
                    frm.HaveYouBeenGivenMedicationToHelpManageYourEmotionsOrVoicesthoughtsCap_14676,
                    frm.HaveYouBeenGivenMedicationToHelpManageYourEmotionsOrVoicesthoughtsCap_14676_ResponseChoiceID,
                    frm.DoYouStruggleWithManagingTheseEmotionsCap_14677,
                    frm.DoYouStruggleWithManagingTheseEmotionsCap_14677_ResponseChoiceID,
                    frm.DoYouStruggleWithHearingVoicesAndorHaveProblemsWithYourThoughtsCap_14678,
                    frm.DoYouStruggleWithHearingVoicesAndorHaveProblemsWithYourThoughtsCap_14678_ResponseChoiceID,
                    frm.OverWhatTimePeriodHaveYouReceivedServicesOrAssistanceForYourMentalHealthIssue_14679,
                    frm.OverWhatTimePeriodHaveYouReceivedServicesOrAssistanceForYourMentalHealthIssue_14679_ResponseChoiceID,
                    frm.IsThereAnyAdditionalInformationFormalOrInformalThatIndicatesTheClientHasAMentalHealthIssue_14680,
                    frm.IsThereAnyAdditionalInformationFormalOrInformalThatIndicatesTheClientHasAMentalHealthIssue_14680_ResponseChoiceID,
                    frm.DoYouHaveAnyReasonToBeConcernedAboutYourOwnSafetyOrIfApplicableTheSafetyOfYourChildren_14684,
                    frm.DoYouHaveAnyReasonToBeConcernedAboutYourOwnSafetyOrIfApplicableTheSafetyOfYourChildren_14684_ResponseChoiceID,
                    frm.IfSomeoneIsInDangerWhoIsIt_14685,
                    frm.IfSomeoneIsInDangerWhoIsIt_14685_ResponseChoiceID,
                    frm.AreYouCurrentlyHomeless_14688,
                    frm.AreYouCurrentlyHomeless_14688_ResponseChoiceID,
                    frm.AreYouCurrentlyAtRiskOfHomelessness_14689,
                    frm.AreYouCurrentlyAtRiskOfHomelessness_14689_ResponseChoiceID,
                    frm.IfYouHaveBeenGivenMedicationDetailsCap_14690,
                    frm.IfYouHaveADiagnosedDisabilityDetails_14694,
                    frm.HaveYouEverUsedAlcoholOrOtherDrugsEgAlcoholIllegalDrugsInhalantsPrescriptionOrOverTheCounterDr_14696,
                    frm.HaveYouEverUsedAlcoholOrOtherDrugsEgAlcoholIllegalDrugsInhalantsPrescriptionOrOverTheCounterDr_14696_ResponseChoiceID,
                    frm.InTheLastThreeMonthsHaveYouFeltThatYouShouldCutDownOrStopDrinkingAlcoholOrUsingDrugsCap_14697,
                    frm.InTheLastThreeMonthsHaveYouFeltThatYouShouldCutDownOrStopDrinkingAlcoholOrUsingDrugsCap_14697_ResponseChoiceID,
                    frm.InTheLastThreeMonthsHasAnyoneAnnoyedYouOrGottenOnYourNervesByTellingYouThatYouShouldCutDownOrS_14698,
                    frm.InTheLastThreeMonthsHasAnyoneAnnoyedYouOrGottenOnYourNervesByTellingYouThatYouShouldCutDownOrS_14698_ResponseChoiceID,
                    frm.InTheLastThreeMonthsHaveYouFeltGuiltyOrBadAboutHowMuchYouAreDrinkingOrUsingDrugsCap_14699,
                    frm.InTheLastThreeMonthsHaveYouFeltGuiltyOrBadAboutHowMuchYouAreDrinkingOrUsingDrugsCap_14699_ResponseChoiceID,
                    frm.InTheLastThreeMonthsHaveYouWokenUpFeelingLikeYouWantDrinkAlcoholOrUseDrugsCap_14700,
                    frm.InTheLastThreeMonthsHaveYouWokenUpFeelingLikeYouWantDrinkAlcoholOrUseDrugsCap_14700_ResponseChoiceID,
                    frm.DoYouNeedHelpsupervisionWithSelfcareEgShoweringOrBathingDressingOrUndressingToiletingOrEatingF_14704,
                    frm.DoYouNeedHelpsupervisionWithSelfcareEgShoweringOrBathingDressingOrUndressingToiletingOrEatingF_14704_ResponseChoiceID,
                    frm.DoYouNeedHelpsupervisionWithMobilityEgMovingAroundTheHouseGettingInAndOutOfAChair_14705,
                    frm.DoYouNeedHelpsupervisionWithMobilityEgMovingAroundTheHouseGettingInAndOutOfAChair_14705_ResponseChoiceID,
                    frm.DoYouNeedHelpsupervisionWithCommunicationEgUnderstandingOrBeingUnderstoodByOtherPeopleIncludin_14706,
                    frm.DoYouNeedHelpsupervisionWithCommunicationEgUnderstandingOrBeingUnderstoodByOtherPeopleIncludin_14706_ResponseChoiceID,
                    frm.LabourForceStatus_14710,
                    frm.LabourForceStatus_14710_ResponseChoiceID,
                    frm.IfTheParticipantIs15yrsWhatIsTheirEmploymentStatus_14711,
                    frm.IfTheParticipantIs15yrsWhatIsTheirEmploymentStatus_14711_ResponseChoiceID,
                    frm.MainSourceOfIncome_14712,
                    frm.MainSourceOfIncome_14712_ResponseChoiceID,
                    frm.IsTheParticipantCurrentlyRegisteredForAGovernmentBenefitPensionOrAllowanceButAwaitingYourFirst_14713,
                    frm.IsTheParticipantCurrentlyRegisteredForAGovernmentBenefitPensionOrAllowanceButAwaitingYourFirst_14713_ResponseChoiceID,
                    frm.IsTheParticipantUndertakingFormalStudyOrTrainingEgSchoolUniversityVocationalStudiesSuchAsTafe_14714,
                    frm.IsTheParticipantUndertakingFormalStudyOrTrainingEgSchoolUniversityVocationalStudiesSuchAsTafe_14714_ResponseChoiceID,
                    frm.WhatTypeOfEducationtrainingIsTheParticipantEnrolledIn_14715,
                    frm.WhatTypeOfEducationtrainingIsTheParticipantEnrolledIn_14715_ResponseChoiceID,
                    frm.LabourForceStatus_14716,
                    frm.LabourForceStatus_14716_ResponseChoiceID,
                    frm.IfTheParticipantIs15yrsWhatIsTheirEmploymentStatus_14717,
                    frm.IfTheParticipantIs15yrsWhatIsTheirEmploymentStatus_14717_ResponseChoiceID,
                    frm.MainSourceOfIncome_14718,
                    frm.MainSourceOfIncome_14718_ResponseChoiceID,
                    frm.IsTheParticipantCurrentlyRegisteredForAGovernmentBenefitPensionOrAllowanceButAwaitingYourFirst_14719,
                    frm.IsTheParticipantCurrentlyRegisteredForAGovernmentBenefitPensionOrAllowanceButAwaitingYourFirst_14719_ResponseChoiceID,
                    frm.IsTheParticipantUndertakingFormalStudyOrTrainingEgSchoolUniversityVocationalStudiesSuchAsTafe_14720,
                    frm.IsTheParticipantUndertakingFormalStudyOrTrainingEgSchoolUniversityVocationalStudiesSuchAsTafe_14720_ResponseChoiceID,
                    frm.WhatTypeOfEducationtrainingIsTheParticipantEnrolledIn_14722,
                    frm.WhatTypeOfEducationtrainingIsTheParticipantEnrolledIn_14722_ResponseChoiceID,
                    frm.WhatIsTheTotalOfYouYourFamilysFortnightlyIncomeCap_14723,
                    frm.DoYouHaveDebtsMp_14725,
                    frm.DoYouHaveDebtsMp_14725_ResponseChoiceID,
                    frm.DoYouHaveASperDebtMp_14726,
                    frm.DoYouHaveASperDebtMp_14726_ResponseChoiceID,
                    frm.HasThisParticipantEverHadPreviousEpisodesOfHomelessnessUnk_14728,
                    frm.HasThisParticipantEverHadPreviousEpisodesOfHomelessnessUnk_14728_ResponseChoiceID,
                    frm.WhatIsTheTotalNumberOfMonthsThatYouHaveEverLivedOnTheStreetsOrInEmergencyAccommodationVispdat_14729,
                    frm.WhatIsTheTotalNumberOfMonthsThatYouHaveEverLivedWithoutStableAccommodationVispdat_14730,
                    frm.EpisodeOfHomelessness_14731,
                    frm.EpisodeOfHomelessness_14731_ResponseChoiceID,
                    frm.EpisodeOfHomelessness_14734,
                    frm.EpisodeOfHomelessness_14734_ResponseChoiceID,
                    frm.HowLongSinceYouHadThisPermanentPlaceToLive_14737,
                    frm.HowLongSinceYouHadThisPermanentPlaceToLive_14737_ResponseChoiceID,
                    frm.WhatWasTheSuburblocalityOfYourMostRecentPermanentPlaceToLive_14738,
                    frm.WhatWasThePostcodeOfYourMostRecentPermanentPlaceToLive_14739,
                    frm.WhatIsTheState_14740,
                    frm.WhatIsTheState_14740_ResponseChoiceID,
                    frm.WhatWasTheSuburbWhereYouResidedLastWeek_14742,
                    frm.WhatWasThePostcodeWhereYouResidedLastWeek_14743,
                    frm.WhatIsTheState_14744,
                    frm.WhatIsTheState_14744_ResponseChoiceID,
                    frm.HowManyTimesHaveYouChangedAddressInThePastThreeYearsVispdat_14746,
                    frm.WouldYouDescribeYourCurrentHousingAsAdequateAndAffordableEgSafeLongTermSuitableLocationAccessT_14747,
                    frm.WouldYouDescribeYourCurrentHousingAsAdequateAndAffordableEgSafeLongTermSuitableLocationAccessT_14747_ResponseChoiceID,
                    frm.IfCurrentHousingIsNotAdequateDetailsCap_14748,
                    frm.HowMuchAreYouPayingWeeklyForHousingCap_14749,
                    frm.DoYouHaveACurrentDepartmentOfHousingDohApplicationMp_14750,
                    frm.DoYouHaveACurrentDepartmentOfHousingDohApplicationMp_14750_ResponseChoiceID,
                    frm.IfYouHaveACurrentDohApplicationWhatIsTheApplicationNumber_14751,
                    frm.OfficeWhereTheDohApplicationWasLodged_14752,
                    frm.Tenure_14754,
                    frm.Tenure_14754_ResponseChoiceID,
                    frm.DwellingType_14755,
                    frm.DwellingType_14755_ResponseChoiceID,
                    frm.LivingArrangements_14756,
                    frm.LivingArrangements_14756_ResponseChoiceID,
                    frm.ConditionsOfOccupancy_14757,
                    frm.ConditionsOfOccupancy_14757_ResponseChoiceID,
                    frm.DwellingType_14758,
                    frm.DwellingType_14758_ResponseChoiceID,
                    frm.LivingArrangements_14759,
                    frm.LivingArrangements_14759_ResponseChoiceID,
                    frm.ConditionsOfOccupancy_14760,
                    frm.ConditionsOfOccupancy_14760_ResponseChoiceID,
                    frm.Tenure_14761,
                    frm.Tenure_14761_ResponseChoiceID,
                    frm.AreYouPregnantOrPlanningToHaveAChildInTheComingYear_14764,
                    frm.AreYouPregnantOrPlanningToHaveAChildInTheComingYear_14764_ResponseChoiceID,
                    frm.IfPregnantWhatIsYourDueDate_14765,
                    frm.HowManyWeeksPregnantAreYou_14766,
                    frm.HowManyChildrenCurrentlyInYourFullTimePrimaryCareWhetherTheyAreParticipantsAtMicahOrNot_14768,
                    frm.HowManyChildrenDoYouHaveWhoAreNotCurrentlyInYourFullTimeCareWhetherTheyAreParticipantsAtMicahO_14769,
                    frm.TotalNumberOfChildrenIncludingThoseInYourfullTimeCareAndThoseNotInFullTimeCare_14770,
                    frm.AreYouCurrentlyReceivingServicesToAssistYouWithYourParenting_14772,
                    frm.AreYouCurrentlyReceivingServicesToAssistYouWithYourParenting_14772_ResponseChoiceID,
                    frm.IfYouAreReceivingSupportFromServicesWhoIsThePrimaryServiceAssistingYou_14773,
                    frm.IfYouAreReceivingSupportFromServicesWhichOtherServiceIsAssistingYouIfApplicable_14774,
                    frm.WhatOtherSupportsFamilyFriendsOtherDoYouHaveToHelpYouWithYourParenting_14775,
                    frm.DoYouHaveAnyCurrentConcernsAboutYourParenting_14776,
                    frm.DoYouHaveAnyCurrentConcernsAboutYourParenting_14776_ResponseChoiceID,
                    frm.WhatDoYouThinkIsWorkingWellInRegardToyourParenting_14777,
                    frm.WhatDoYouThinkIsNotWorkingWellInRegardToYourParenting_14778,
                    frm.WouldYouLikeHelpOrFeelYouNeedSupportInAnyOfTheFollowingAreas_14780,
                    frm.WouldYouLikeHelpOrFeelYouNeedSupportInAnyOfTheFollowingAreas_14780_ResponseChoiceID,
                    frm.HasChildSafetyEverBeenInvolvedWithTheFamilyInThePast_14781,
                    frm.HasChildSafetyEverBeenInvolvedWithTheFamilyInThePast_14781_ResponseChoiceID,
                    frm.IfChildSafetyHasBeenInvolvedInThePastDetails_14782,
                    frm.IfChildSafetyHasBeenInvolvedInThePastDetails_14782_ResponseChoiceID,
                    frm.IsChildSafetyCurrentlyInvolvedWithTheFamily_14783,
                    frm.IsChildSafetyCurrentlyInvolvedWithTheFamily_14783_ResponseChoiceID,
                    frm.IfChildSafetyIsCurrentlyInvolvedWithTheFamilyDetails_14784,
                    frm.IfChildSafetyIsCurrentlyInvolvedWithTheFamilyDetails_14784_ResponseChoiceID,
                    frm.WhichChildSafetyOfficeIsInvolved_14785,
                    frm.WhatIsTheNameOfTheChildSafetyOfficerCso_14786,
                    frm.DoYouAttendRegularPreAndorAntenatalAppointments_14787,
                    frm.DoYouAttendRegularPreAndorAntenatalAppointments_14787_ResponseChoiceID,
                    frm.AreYouReceivingAssistanceWithTheseConcernsFromProfessionalsUnk_14788,
                    frm.AreYouReceivingAssistanceWithTheseConcernsFromProfessionalsUnk_14788_ResponseChoiceID,
                    frm.AreYouReceivingInformalSupportAndAssistanceFromAnyoneUnk_14789,
                    frm.AreYouReceivingInformalSupportAndAssistanceFromAnyoneUnk_14789_ResponseChoiceID,
                    frm.IfYouAreReceivingInformalSupportDetailsUnk_14790,
                    frm.DoesYourUseOfAlcoholOrDrugsContributeToAnyDifficultiesForYouInAnyOfTheFollowingAreasCap_14791,
                    frm.DoesYourUseOfAlcoholOrDrugsContributeToAnyDifficultiesForYouInAnyOfTheFollowingAreasCap_14791_ResponseChoiceID,
                    frm.IfYesByWho_14792,
                    frm.AreYouReceivingAppropriateSupportAndTreatmentForThisCondition_14794,
                    frm.AreYouReceivingAppropriateSupportAndTreatmentForThisCondition_14794_ResponseChoiceID,
                    frm.WouldYouLikeAssistanceAccessingAppropriateCaretreatmentsupportForYourDisability_14795,
                    frm.WouldYouLikeAssistanceAccessingAppropriateCaretreatmentsupportForYourDisability_14795_ResponseChoiceID,
                    frm.OtherNotesAboutCareProtectionIssues_14796,
                    frm.OtherNotesAboutEducationEmploymentAndFinances_14797,
                    frm.OtherNotesAboutHousingIssues_14798,
                    frm.IfThereIsPresenceOfDomesticViolencedisruptionToFamilyRelationshipsAndTheParticipantHasRequeste_14799,
                    frm.IfThereIsPresenceOfDomesticViolencedisruptionToFamilyRelationshipsAndTheParticipantHasRequeste_14799_ResponseChoiceID,
                    frm.IfYesWhatDisabilityDiagnosedByAHealthProfessionalDoYouHaveMp_14800,
                    frm.IfYesWhatDisabilityDiagnosedByAHealthProfessionalDoYouHaveMp_14800_ResponseChoiceID,
                    frm.DoYouHaveADisabilityDiagnosedByAHealthProfessionalMp_14801,
                    frm.DoYouHaveADisabilityDiagnosedByAHealthProfessionalMp_14801_ResponseChoiceID,
                    frm.Age_14803,
                    frm.IfSomeoneIsInDangerWhatType_14806,
                    frm.IfSomeoneIsInDangerWhatType_14806_ResponseChoiceID,
                    frm.IfYesByWhom_14807,
                    frm.DoesYourMentalHealthConditionsContributeToAnyDifficultiesForYouInAnyOfTheFollowingAreasCap_14808,
                    frm.DoesYourMentalHealthConditionsContributeToAnyDifficultiesForYouInAnyOfTheFollowingAreasCap_14808_ResponseChoiceID,
                    frm.Details_14809,
                    frm.AreYouReceivingAppropriateCaretreatmentsupportInRegardToYourDisabilityMp_14810,
                    frm.AreYouReceivingAppropriateCaretreatmentsupportInRegardToYourDisabilityMp_14810_ResponseChoiceID,
                    frm.Details_14811,
                    frm.IfYesDetails_14812,
                    frm.IsTheParticipantChildEnrolledInOneOfTheFollowing_14814,
                    frm.IsTheParticipantChildEnrolledInOneOfTheFollowing_14814_ResponseChoiceID,
                    frm.DoesTheParticipantHaveAccessToThreeHealthyMealsADayEveryDayEgHotMealsForDinnerDietThatIncludes_14816,
                    frm.DoesTheParticipantHaveAccessToThreeHealthyMealsADayEveryDayEgHotMealsForDinnerDietThatIncludes_14816_ResponseChoiceID,
                    frm.WouldYouLikeHelpAccessingFoodForYourFamily_14817,
                    frm.WouldYouLikeHelpAccessingFoodForYourFamily_14817_ResponseChoiceID,
                    frm.Details_14818,
                    frm.IfSoHowOftenDoesTheParticipantChildGetThere_14819,
                    frm.IfSoHowOftenDoesTheParticipantChildGetThere_14819_ResponseChoiceID,
                    frm.WouldTheFamilyLikeHelpWithAccessingSchoolOrKindergartenOrAttendingMoreRegularly_14820,
                    frm.WouldTheFamilyLikeHelpWithAccessingSchoolOrKindergartenOrAttendingMoreRegularly_14820_ResponseChoiceID,
                    frm.Details_14821,
                    frm.AreImmunisationsUpToDate_14823,
                    frm.AreImmunisationsUpToDate_14823_ResponseChoiceID,
                    frm.DoesTheParticipantChildhaveAnyOfTheFollowingDiagnosedconditions_14824,
                    frm.DoesTheParticipantChildhaveAnyOfTheFollowingDiagnosedconditions_14824_ResponseChoiceID,
                    frm.Details_14825,
                    frm.IfYouHaveADiagnosedMentalHealthConditionDetails_14826,
                    frm.OfTheseReasonsWhichDoesTheParticipantReportAsBeingTheMainReasonForSeekingAssistance_14827,
                    frm.OfTheseReasonsWhichDoesTheParticipantReportAsBeingTheMainReasonForSeekingAssistance_14827_ResponseChoiceID,
                    frm.DoesThePublicTrusteeAdministerTheParticipantsPersonalFinancesMp_14829,
                    frm.DoesThePublicTrusteeAdministerTheParticipantsPersonalFinancesMp_14829_ResponseChoiceID,
                    frm.WithinDemographicsMedicareNumberWasAnsweredAs_14837,
                    frm.WithinDemographicsMedicareNoIndividualIdWasAnsweredAs_14838,
                    frm.AtSpdatIndiividualHowManyTimesHaveYouChangedAddressesWasAnsweredAs_14840,
                    frm.AtSpdatIndiividualHowManyTimesHaveYouChangedAddressesWasAnsweredAs_14840_DisplayStr,
                    frm.AsAChildWereYouEverInTheFollowingInstitutions_14841,
                    frm.AsAChildWereYouEverInTheFollowingInstitutions_14841_ResponseChoiceID,
                    frm.AtSpdatIndividualAsAChildWereYouEverInTheFollowingInstitutionsWasAnsweredAsUseResponsesToThisQ_14842,
                    frm.AtSpdatIndividualAsAChildWereYouEverInTheFollowingInstitutionsWasAnsweredAsUseResponsesToThisQ_14842_DisplayStr,
                    frm.AsAnAdultHaveYouEverBeenInTheFollowingInstitutions_14843,
                    frm.AsAnAdultHaveYouEverBeenInTheFollowingInstitutions_14843_ResponseChoiceID,
                    frm.AtSpdatIndividualMainSourceOfIncomeWasAnsweredAs_14846,
                    frm.AtSpdatIndividualMainSourceOfIncomeWasAnsweredAs_14846_DisplayStr,
                    frm.WhatWasTheSchoolEnrolmentAndAttendanceStatusOnPresentation_14847,
                    frm.WhatWasTheSchoolEnrolmentAndAttendanceStatusOnPresentation_14847_ResponseChoiceID,
                    frm.WhatIsTheHighestYearOfSchoolYouCompletedVispdat_14849,
                    frm.WhatIsTheHighestYearOfSchoolYouCompletedVispdat_14849_ResponseChoiceID,
                    frm.MostRecentQhipConsentWasSignedByParticipantOn_14854,
                    frm.MostRecentQhipConsentWasSignedByParticipantOn_14854_DisplayStr,
                    frm.MostRecentMicahStandardConsentWasSignedByParticipantOn_14855,
                    frm.MostRecentMicahStandardConsentWasSignedByParticipantOn_14855_DisplayStr,
                    frm.AtFamilySpdatWhatIsTheTotalLengthOfTimeYouAndYourFamilyHaveNotHadYourOwnTenancyWasAnsweredAs_14857,
                    frm.AtFamilySpdatWhatIsTheTotalLengthOfTimeYouAndYourFamilyHaveNotHadYourOwnTenancyWasAnsweredAs_14857_DisplayStr,
                    frm.AtIndividualSpdatWhatIsTheTotalLengthOfTimeYouHaveLivedOnTheStreetsOrInEmergencyAccommodationW_14858,
                    frm.AtIndividualSpdatWhatIsTheTotalLengthOfTimeYouHaveLivedOnTheStreetsOrInEmergencyAccommodationW_14858_DisplayStr,
                    frm.KeepMeEmpty_14860,
                    frm.VariableAtIndividualSpdatWhatIsTheTotalLengthOfTimeYouHaveLivedOnTheStreetsOrInEmergencyAccomm_14861,
                    frm.VariableAtFamilySpdatWhatIsTheTotalLengthOfTimeYouAndYourFamilyHaveNotHadYourOwnTenancyWasAnsw_14862,
                    frm.VariableAtSpdatIndividualAsAChildWereYouEverInTheFollowingInstitutionsWasAnsweredAs_14865,
                    frm.VariableAtSpdatIndividualAsAnAdultHaveYouBeenInTheFollowingInstitutionsWasAnsweredAs_14866,
                    frm.VariableAtSpdatIndividualDoYouHaveADisabilityDiagnosedByAHealthProfessionalWasAnsweredAs_14867,
                    frm.VariableAtSpdatIndividualMainSourceOfIncomeWasAnsweredAs_14868,
                    frm.VariableAtSpdatFamilyMainSourceOfIncomeWasAnsweredAs_14869,
                    frm.VariableAtSpdatIndividualWhatIsTheHighestYearOfSchoolYouCompletedWasAnsweredAs_14870,
                    frm.VariableAtSpdatFamilyWhatIsTheHighestYearOfSchoolYouCompletedWasAnsweredAs_14871,
                    frm.VariableAtSpdatIndividualWhatWasTheSchoolEnrolmentAndAttendanceStatusOnPresentationWasAnswered_14872,
                    frm.VariableAtSpdatIndividualHowManyTimesHaveYouChangedAddressesWasAnsweredAs_14873,
                    frm.VariableAtSpdatFamilyHowManyTimesHaveYouChangedAddressesWasAnsweredAs_14874,
                    frm.AtSpdatFamilyMainSourceOfIncomeWasAnsweredAs_14876,
                    frm.AtSpdatFamilyMainSourceOfIncomeWasAnsweredAs_14876_DisplayStr,
                    frm.AtSpdatFamilyHowManyTimesHaveYouChangedAddressesWasAnsweredAs_14878,
                    frm.AtSpdatFamilyHowManyTimesHaveYouChangedAddressesWasAnsweredAs_14878_DisplayStr,
                    frm.FrequentPresenterHospitalConsent_14881,
                    frm.FrequentPresenterHospitalConsent_14881_ResponseChoiceID,
                    frm.HospitalUrNumber_14882,
                    frm.HospitalDischargeDate_14883,
                    frm.HospitalDischargeSummary_14884,
                    frm.HospitalDischargeSummary_14884_ResponseChoiceID,
                    frm.SupportiveHousingHopeStreetLowIncomeOrFormerlyHomeless_14885,
                    frm.SupportiveHousingHopeStreetLowIncomeOrFormerlyHomeless_14885_ResponseChoiceID,
                    frm.LeaseSignDate_14886,
                    frm.MoveInDate_14887,
                    frm.AreYouTicaListedMp_14888,
                    frm.AreYouTicaListedMp_14888_ResponseChoiceID,
                    frm.WithinAddressBookGpHasBeenEnteredAs_14891,
                    frm.WithinAddressBookGpHasBeenEnteredAs_14891_DisplayStr,
                    frm.AtIntakeDoYouHaveARegularGpThatYouAttend_14893,
                    frm.AtIntakeDoYouHaveARegularGpThatYouAttend_14893_ResponseChoiceID,
                    frm.Doyouhaveanappointedsubstitutedecisionmakermp_14902,
                    frm.Doyouhaveanappointedsubstitutedecisionmakermp_14902_ResponseChoiceID,
                    frm.SHSTypeOfServiceActivityTxt_15117,
                    frm.Totalefforttimeforparticipant_15588,
                    frm.SHSTypeOfServiceActivityNum_16051,
                    frm.HowmanystaffdidthistogetherAtmost4_16157,
                    frm.Selectyourname_16158,
                    e.EntityName,
                    frm.Start_16161,
                    frm.Endoptional_16162,
                    frm.Selectthe2ndstaffperson_16163,
                    frm.Whatotherteamassisted_16164,
                    frm.WasthisaPATpersonalvisit_16165,
                    frm.WasthisaPATpersonalvisit_16165_ResponseChoiceID,
                    frm.TimespentonbehalfofparticipantPerstaffmember_16166,
                    frm.TimespenttravellingNotwithparticipantPerstaffmember_16167,
                    frm.TimespentwithparticipantPerstaffmember_16168,
                    frm.WastheparticipantfamilypresentduringthisactivityAnswerYesifconversingwithParticipantFamilyonph_16169,
                    frm.WastheparticipantfamilypresentduringthisactivityAnswerYesifconversingwithParticipantFamilyonph_16169_ResponseChoiceID,
                    frm.ContactLocation_16170,
                    frm.ContactLocation_16170_ResponseChoiceID,
                    frm.ContactMethod_16171,
                    frm.ContactMethod_16171_ResponseChoiceID,
                    frm.Ifcontactlocationisotherpleasespecify_16172,
                    frm.PhoneContactType_16173,
                    frm.PhoneContactType_16173_ResponseChoiceID,
                    frm.Totaltimespentonbehalfofparticipant_16174,
                    frm.Totaltimespenttravelling_16175,
                    frm.Totaltimespentwithparticipant_16176,
                    frm.Selectthedischargesummaryuploaded_16837,
                    frm.Selectthedischargesummaryuploaded_16837_SourceFormID,
                    frm.Selectthedischargesummaryuploaded_16837_DisplayStr,
                    frm.SelecttheEDFPConsentuploaded_16838,
                    frm.SelecttheEDFPConsentuploaded_16838_SourceFormID,
                    frm.SelecttheEDFPConsentuploaded_16838_DisplayStr,
                    frm.Whatisthesourceofinformationthatthispersonmayhaveamentalillnessormentalhealthcondition_16936,
                    frm.Whatisthesourceofinformationthatthispersonmayhaveamentalillnessormentalhealthcondition_16936_ResponseChoiceID,
                    frm.Whatistheparticipantsprimarygoalforenrollinginthisprogram_19812,
                    frm.Whatistheparticipantsprimarygoalforenrollinginthisprogram_19812_ResponseChoiceID,
                    frm.Theskillsoutlinedbelowarerequiredtocompletethisprogrampleaseindicatewhichoftheseskillstheparti_19814,
                    frm.Theskillsoutlinedbelowarerequiredtocompletethisprogrampleaseindicatewhichoftheseskillstheparti_19814_ResponseChoiceID,
                    frm.Whichofthefollowingfearsconcernsassociatedwithcompletingthisprogramapplytothisparticipant_19815,
                    frm.Whichofthefollowingfearsconcernsassociatedwithcompletingthisprogramapplytothisparticipant_19815_ResponseChoiceID,
                    frm.Isthereanyadditionalsupportthatthisparticipantwillrequiretocompletetheprogram_19816,
                    frm.Doyouhavedebtsynump_20360,
                    frm.Doyouhavedebtsynump_20360_ResponseChoiceID,
                    frm.DoyouhaveaSPERdebtynump_20361,
                    frm.DoyouhaveaSPERdebtynump_20361_ResponseChoiceID,
                    frm.Whatwasthepostcodeofyourmostrecentpermanentplacetolivet_20362,
                    frm.Whatwasthepostcodewhereyouresidedlastweekt_20363,
                    frm.AIHWOrganisationID_21823,
                    frm.Whatwasthesuburblocalityofyourmostrecentpermanentplacetolive_21824,
                    frm.Whatwasthesuburbwhereyouresidedlastweek_21825,
                    frm.SubmitsSHSAIHWreports_21832,
                    frm.SummaryObservations_23040,
                    frm.IstheparticipantcurrentlyreceivinganagreedpackageofsupportthroughtheNationalDisabilityInsuranc_24805,
                    frm.IstheparticipantcurrentlyreceivinganagreedpackageofsupportthroughtheNationalDisabilityInsuranc_24805_ResponseChoiceID,
                     s.FName,
                    s.LName
                

                FROM form.f_290 frm
                JOIN Entities e ON e.EntityID = frm.MicahTeam_16159
                JOIN Staff s ON frm.AuditStaffID = s.StaffID
                JOIN SubjectType sub ON sub.SubjectTypeID = frm.SubjectTypeID
                JOIN Programs prg ON prg.ProgramID = frm.ProgramID
                WHERE frm.SubjectID = (SELECT SubjectID FROM SubjectXClient WHERE CLID = @Id)
                ORDER BY frm.AuditDate DESC";        


            using var command = new SqlCommand(query, connection);
            command.Parameters.AddWithValue("@Id", id);

            var AIHWForm = new List<AIHWFormModel>();
            using var reader = await command.ExecuteReaderAsync();

            while (await reader.ReadAsync())
            {
                AIHWForm.Add(new AIHWFormModel
                {
                    FormResponseID = reader.IsDBNull(0) ? (int?)null : reader.GetInt32(0),
                    FormIdentifier = reader.IsDBNull(1) ? null : reader.GetString(1),
                    SubjectID = reader.IsDBNull(2) ? (int?)null : reader.GetInt32(2),
                    GroupID = reader.IsDBNull(3) ? (int?)null : reader.GetInt32(3),
                    FamilyID = reader.IsDBNull(4) ? (int?)null : reader.GetInt32(4),
                    ResponseSetID = reader.IsDBNull(5) ? (int?)null : reader.GetInt32(5),
                    FormID = reader.IsDBNull(6) ? (int?)null : reader.GetInt32(6),
                    CollectionTypeID = reader.IsDBNull(7) ? (int?)null : reader.GetInt32(7),
                    SubjectTypeID = reader.IsDBNull(8) ? (int?)null : reader.GetInt32(8),
                    CollectionID = reader.IsDBNull(9) ? (int?)null : reader.GetInt32(9),
                    ResponseCreatedDate = reader.IsDBNull(10) ? (DateTime?)null : reader.GetDateTime(10),
                    ProgramID = reader.IsDBNull(11) ? (int?)null : reader.GetInt16(11),
                    AuditStaffID = reader.IsDBNull(12) ? (int?)null : reader.GetInt32(12),
                    AuditDate = reader.IsDBNull(13) ? (DateTime?)null : reader.GetDateTime(13),
                    DataEnteredByID = reader.IsDBNull(14) ? (int?)null : reader.GetInt32(14),
                    DraftSavedOn = reader.IsDBNull(15) ? (DateTime?)null : reader.GetDateTime(15),
                    RemovedDate = reader.IsDBNull(16) ? (DateTime?)null : reader.GetDateTime(16),
                    WhatReasonsDoesTheParticipantReportForSeekingAssistance_14662 = reader.IsDBNull(17) ? null : reader.GetString(17),
                    WhatReasonsDoesTheParticipantReportForSeekingAssistance_14662_ResponseChoiceID = reader.IsDBNull(18) ? (int?)null : reader.GetInt32(18),
                    WhatOtherReasonsDoesTheParticipantReportForSeekingAssistance_14663 = reader.IsDBNull(19) ? null : reader.GetString(19),
                    IfYourSafetyOrThatOfYourFamilyIsAConcernForYouWouldYouLikeHelpToImproveYourSafety_14664 = reader.IsDBNull(20) ? null : reader.GetString(20),
                    IfYourSafetyOrThatOfYourFamilyIsAConcernForYouWouldYouLikeHelpToImproveYourSafety_14664_ResponseChoiceID = reader.IsDBNull(21) ? (int?)null : reader.GetInt32(21),
                    IfThisParticipantHasACareOrProtectionOrderWhatWereTheCareArrangementsTheWeekBeforePresentingFo_14669 = reader.IsDBNull(22) ? null : reader.GetString(22),
                    IfThisParticipantHasACareOrProtectionOrderWhatWereTheCareArrangementsTheWeekBeforePresentingFo_14669_ResponseChoiceID = reader.IsDBNull(23) ? (int?)null : reader.GetInt32(23),
                    IfThisParticipantHasACareOrProtectionOrderWhatWereTheCareArrangementsWhenPresentingForEachFami_14670 = reader.IsDBNull(24) ? null : reader.GetString(24),
                    IfThisParticipantHasACareOrProtectionOrderWhatWereTheCareArrangementsWhenPresentingForEachFami_14670_ResponseChoiceID = reader.IsDBNull(25) ? (int?)null : reader.GetInt32(25),
                    HaveYouBeenInAnyOfTheseInstitutionsOrFacilitiesInTheLast12MonthsforEachFamilyMember_14671 = reader.IsDBNull(26) ? null : reader.GetString(26),
                    HaveYouBeenInAnyOfTheseInstitutionsOrFacilitiesInTheLast12MonthsforEachFamilyMember_14671_ResponseChoiceID = reader.IsDBNull(27) ? (int?)null : reader.GetInt32(27),
                    DoYouHaveAPhysicalHealthConditionDiagnosedByAHealthProfessionalMp_14673 = reader.IsDBNull(28) ? null : reader.GetString(28),
                    DoYouHaveAPhysicalHealthConditionDiagnosedByAHealthProfessionalMp_14673_ResponseChoiceID = reader.IsDBNull(29) ? (int?)null : reader.GetInt32(29),
                    IfYouHaveADiagnosedPhysicalHealthConditionDetailsMp_14674 = reader.IsDBNull(30) ? null : reader.GetString(30),
                    DoYouHaveAMentalHealthConditionDiagnosedByAHealthProfessional_14675 = reader.IsDBNull(31) ? null : reader.GetString(31),
                    DoYouHaveAMentalHealthConditionDiagnosedByAHealthProfessional_14675_ResponseChoiceID = reader.IsDBNull(32) ? (int?)null : reader.GetInt32(32),
                    HaveYouBeenGivenMedicationToHelpManageYourEmotionsOrVoicesthoughtsCap_14676 = reader.IsDBNull(33) ? null : reader.GetString(33),
                    HaveYouBeenGivenMedicationToHelpManageYourEmotionsOrVoicesthoughtsCap_14676_ResponseChoiceID = reader.IsDBNull(34) ? (int?)null : reader.GetInt32(34),
                    DoYouStruggleWithManagingTheseEmotionsCap_14677 = reader.IsDBNull(35) ? null : reader.GetString(35),
                    DoYouStruggleWithManagingTheseEmotionsCap_14677_ResponseChoiceID = reader.IsDBNull(36) ? (int?)null : reader.GetInt32(36),
                    DoYouStruggleWithHearingVoicesAndorHaveProblemsWithYourThoughtsCap_14678 = reader.IsDBNull(37) ? null : reader.GetString(37),
                    DoYouStruggleWithHearingVoicesAndorHaveProblemsWithYourThoughtsCap_14678_ResponseChoiceID = reader.IsDBNull(38) ? (int?)null : reader.GetInt32(38),
                    OverWhatTimePeriodHaveYouReceivedServicesOrAssistanceForYourMentalHealthIssue_14679 = reader.IsDBNull(39) ? null : reader.GetString(39),
                    OverWhatTimePeriodHaveYouReceivedServicesOrAssistanceForYourMentalHealthIssue_14679_ResponseChoiceID = reader.IsDBNull(40) ? (int?)null : reader.GetInt32(40),
                    IsThereAnyAdditionalInformationFormalOrInformalThatIndicatesTheClientHasAMentalHealthIssue_14680 = reader.IsDBNull(41) ? null : reader.GetString(41),
                    IsThereAnyAdditionalInformationFormalOrInformalThatIndicatesTheClientHasAMentalHealthIssue_14680_ResponseChoiceID = reader.IsDBNull(42) ? (int?)null : reader.GetInt32(42),
                    DoYouHaveAnyReasonToBeConcernedAboutYourOwnSafetyOrIfApplicableTheSafetyOfYourChildren_14684 = reader.IsDBNull(43) ? null : reader.GetString(43),
                    DoYouHaveAnyReasonToBeConcernedAboutYourOwnSafetyOrIfApplicableTheSafetyOfYourChildren_14684_ResponseChoiceID = reader.IsDBNull(44) ? (int?)null : reader.GetInt32(44),
                    IfSomeoneIsInDangerWhoIsIt_14685 = reader.IsDBNull(45) ? null : reader.GetString(45),
                    IfSomeoneIsInDangerWhoIsIt_14685_ResponseChoiceID = reader.IsDBNull(46) ? (int?)null : reader.GetInt32(46),
                    AreYouCurrentlyHomeless_14688 = reader.IsDBNull(47) ? null : reader.GetString(47),
                    AreYouCurrentlyHomeless_14688_ResponseChoiceID = reader.IsDBNull(48) ? (int?)null : reader.GetInt32(48),
                    AreYouCurrentlyAtRiskOfHomelessness_14689 = reader.IsDBNull(49) ? null : reader.GetString(49),
                    AreYouCurrentlyAtRiskOfHomelessness_14689_ResponseChoiceID = reader.IsDBNull(50) ? (int?)null : reader.GetInt32(50),
                    IfYouHaveBeenGivenMedicationDetailsCap_14690 = reader.IsDBNull(51) ? null : reader.GetString(51),
                    IfYouHaveADiagnosedDisabilityDetails_14694 = reader.IsDBNull(52) ? null : reader.GetString(52),
                    HaveYouEverUsedAlcoholOrOtherDrugsEgAlcoholIllegalDrugsInhalantsPrescriptionOrOverTheCounterDr_14696 = reader.IsDBNull(53) ? null : reader.GetString(53),
                    HaveYouEverUsedAlcoholOrOtherDrugsEgAlcoholIllegalDrugsInhalantsPrescriptionOrOverTheCounterDr_14696_ResponseChoiceID = reader.IsDBNull(54) ? (int?)null : reader.GetInt32(54),
                    InTheLastThreeMonthsHaveYouFeltThatYouShouldCutDownOrStopDrinkingAlcoholOrUsingDrugsCap_14697 = reader.IsDBNull(55) ? null : reader.GetString(55),
                    InTheLastThreeMonthsHaveYouFeltThatYouShouldCutDownOrStopDrinkingAlcoholOrUsingDrugsCap_14697_ResponseChoiceID = reader.IsDBNull(56) ? (int?)null : reader.GetInt32(56),
                    InTheLastThreeMonthsHasAnyoneAnnoyedYouOrGottenOnYourNervesByTellingYouThatYouShouldCutDownOrS_14698 = reader.IsDBNull(57) ? null : reader.GetString(57),
                    InTheLastThreeMonthsHasAnyoneAnnoyedYouOrGottenOnYourNervesByTellingYouThatYouShouldCutDownOrS_14698_ResponseChoiceID = reader.IsDBNull(58) ? (int?)null : reader.GetInt32(58),
                    InTheLastThreeMonthsHaveYouFeltGuiltyOrBadAboutHowMuchYouAreDrinkingOrUsingDrugsCap_14699 = reader.IsDBNull(59) ? null : reader.GetString(59),
                    InTheLastThreeMonthsHaveYouFeltGuiltyOrBadAboutHowMuchYouAreDrinkingOrUsingDrugsCap_14699_ResponseChoiceID = reader.IsDBNull(60) ? (int?)null : reader.GetInt32(60),
                    InTheLastThreeMonthsHaveYouWokenUpFeelingLikeYouWantDrinkAlcoholOrUseDrugsCap_14700 = reader.IsDBNull(61) ? null : reader.GetString(61),
                    InTheLastThreeMonthsHaveYouWokenUpFeelingLikeYouWantDrinkAlcoholOrUseDrugsCap_14700_ResponseChoiceID = reader.IsDBNull(62) ? (int?)null : reader.GetInt32(62),
                    DoYouNeedHelpsupervisionWithSelfcareEgShoweringOrBathingDressingOrUndressingToiletingOrEatingF_14704 = reader.IsDBNull(63) ? null : reader.GetString(63),
                    DoYouNeedHelpsupervisionWithSelfcareEgShoweringOrBathingDressingOrUndressingToiletingOrEatingF_14704_ResponseChoiceID = reader.IsDBNull(64) ? (int?)null : reader.GetInt32(64),
                    DoYouNeedHelpsupervisionWithMobilityEgMovingAroundTheHouseGettingInAndOutOfAChair_14705 = reader.IsDBNull(65) ? null : reader.GetString(65),
                    DoYouNeedHelpsupervisionWithMobilityEgMovingAroundTheHouseGettingInAndOutOfAChair_14705_ResponseChoiceID = reader.IsDBNull(66) ? (int?)null : reader.GetInt32(66),
                    DoYouNeedHelpsupervisionWithCommunicationEgUnderstandingOrBeingUnderstoodByOtherPeopleIncludin_14706 = reader.IsDBNull(67) ? null : reader.GetString(67),
                    DoYouNeedHelpsupervisionWithCommunicationEgUnderstandingOrBeingUnderstoodByOtherPeopleIncludin_14706_ResponseChoiceID = reader.IsDBNull(68) ? (int?)null : reader.GetInt32(68),
                    LabourForceStatus_14710 = reader.IsDBNull(69) ? null : reader.GetString(69),
                    LabourForceStatus_14710_ResponseChoiceID = reader.IsDBNull(70) ? (int?)null : reader.GetInt32(70),
                    IfTheParticipantIs15yrsWhatIsTheirEmploymentStatus_14711 = reader.IsDBNull(71) ? null : reader.GetString(71),
                    IfTheParticipantIs15yrsWhatIsTheirEmploymentStatus_14711_ResponseChoiceID = reader.IsDBNull(72) ? (int?)null : reader.GetInt32(72),
                    MainSourceOfIncome_14712 = reader.IsDBNull(73) ? null : reader.GetString(73),
                    MainSourceOfIncome_14712_ResponseChoiceID = reader.IsDBNull(74) ? (int?)null : reader.GetInt32(74),
                    IsTheParticipantCurrentlyRegisteredForAGovernmentBenefitPensionOrAllowanceButAwaitingYourFirst_14713 = reader.IsDBNull(75) ? null : reader.GetString(75),
                    IsTheParticipantCurrentlyRegisteredForAGovernmentBenefitPensionOrAllowanceButAwaitingYourFirst_14713_ResponseChoiceID = reader.IsDBNull(76) ? (int?)null : reader.GetInt32(76),
                    IsTheParticipantUndertakingFormalStudyOrTrainingEgSchoolUniversityVocationalStudiesSuchAsTafe_14714 = reader.IsDBNull(77) ? null : reader.GetString(77),
                    IsTheParticipantUndertakingFormalStudyOrTrainingEgSchoolUniversityVocationalStudiesSuchAsTafe_14714_ResponseChoiceID = reader.IsDBNull(78) ? (int?)null : reader.GetInt32(78),
                    WhatTypeOfEducationtrainingIsTheParticipantEnrolledIn_14715 = reader.IsDBNull(79) ? null : reader.GetString(79),
                    WhatTypeOfEducationtrainingIsTheParticipantEnrolledIn_14715_ResponseChoiceID = reader.IsDBNull(80) ? (int?)null : reader.GetInt32(80),
                    LabourForceStatus_14716 = reader.IsDBNull(81) ? null : reader.GetString(81),
                    LabourForceStatus_14716_ResponseChoiceID = reader.IsDBNull(82) ? (int?)null : reader.GetInt32(82),
                    IfTheParticipantIs15yrsWhatIsTheirEmploymentStatus_14717 = reader.IsDBNull(83) ? null : reader.GetString(83),
                    IfTheParticipantIs15yrsWhatIsTheirEmploymentStatus_14717_ResponseChoiceID = reader.IsDBNull(84) ? (int?)null : reader.GetInt32(84),
                    MainSourceOfIncome_14718 = reader.IsDBNull(85) ? null : reader.GetString(85),
                    MainSourceOfIncome_14718_ResponseChoiceID = reader.IsDBNull(86) ? (int?)null : reader.GetInt32(86),
                    IsTheParticipantCurrentlyRegisteredForAGovernmentBenefitPensionOrAllowanceButAwaitingYourFirst_14719 = reader.IsDBNull(87) ? null : reader.GetString(87),
                    IsTheParticipantCurrentlyRegisteredForAGovernmentBenefitPensionOrAllowanceButAwaitingYourFirst_14719_ResponseChoiceID = reader.IsDBNull(88) ? (int?)null : reader.GetInt32(88),
                    IsTheParticipantUndertakingFormalStudyOrTrainingEgSchoolUniversityVocationalStudiesSuchAsTafe_14720 = reader.IsDBNull(89) ? null : reader.GetString(89),
                    IsTheParticipantUndertakingFormalStudyOrTrainingEgSchoolUniversityVocationalStudiesSuchAsTafe_14720_ResponseChoiceID = reader.IsDBNull(90) ? (int?)null : reader.GetInt32(90),
                    WhatTypeOfEducationtrainingIsTheParticipantEnrolledIn_14722 = reader.IsDBNull(91) ? null : reader.GetString(91),
                    WhatTypeOfEducationtrainingIsTheParticipantEnrolledIn_14722_ResponseChoiceID = reader.IsDBNull(92) ? (int?)null : reader.GetInt32(92),
                    WhatIsTheTotalOfYouYourFamilysFortnightlyIncomeCap_14723 = reader.IsDBNull(93) ? (decimal?)null : reader.GetDecimal(93),
                    DoYouHaveDebtsMp_14725 = reader.IsDBNull(94) ? null : reader.GetString(94),
                    DoYouHaveDebtsMp_14725_ResponseChoiceID = reader.IsDBNull(95) ? (int?)null : reader.GetInt32(95),
                    DoYouHaveASperDebtMp_14726 = reader.IsDBNull(96) ? null : reader.GetString(96),
                    DoYouHaveASperDebtMp_14726_ResponseChoiceID = reader.IsDBNull(97) ? (int?)null : reader.GetInt32(97),
                    HasThisParticipantEverHadPreviousEpisodesOfHomelessnessUnk_14728 = reader.IsDBNull(98) ? null : reader.GetString(98),
                    HasThisParticipantEverHadPreviousEpisodesOfHomelessnessUnk_14728_ResponseChoiceID = reader.IsDBNull(99) ? (int?)null : reader.GetInt32(99),
                    WhatIsTheTotalNumberOfMonthsThatYouHaveEverLivedOnTheStreetsOrInEmergencyAccommodationVispdat_14729 = reader.IsDBNull(100) ? (decimal?)null : reader.GetDecimal(100),
                    WhatIsTheTotalNumberOfMonthsThatYouHaveEverLivedWithoutStableAccommodationVispdat_14730 = reader.IsDBNull(101) ? (decimal?)null : reader.GetDecimal(101),
                    EpisodeOfHomelessness_14731 = reader.IsDBNull(102) ? null : reader.GetString(102),
                    EpisodeOfHomelessness_14731_ResponseChoiceID = reader.IsDBNull(103) ? (int?)null : reader.GetInt32(103),
                    EpisodeOfHomelessness_14734 = reader.IsDBNull(104) ? null : reader.GetString(104),
                    EpisodeOfHomelessness_14734_ResponseChoiceID = reader.IsDBNull(105) ? (int?)null : reader.GetInt32(105),
                    HowLongSinceYouHadThisPermanentPlaceToLive_14737 = reader.IsDBNull(106) ? null : reader.GetString(106),
                    HowLongSinceYouHadThisPermanentPlaceToLive_14737_ResponseChoiceID = reader.IsDBNull(107) ? (int?)null : reader.GetInt32(107),
                    WhatWasTheSuburblocalityOfYourMostRecentPermanentPlaceToLive_14738 = reader.IsDBNull(108) ? null : reader.GetString(108),
                    WhatWasThePostcodeOfYourMostRecentPermanentPlaceToLive_14739 = reader.IsDBNull(109) ? (decimal?)null : reader.GetDecimal(109),
                    WhatIsTheState_14740 = reader.IsDBNull(110) ? null : reader.GetString(110),
                    WhatIsTheState_14740_ResponseChoiceID = reader.IsDBNull(111) ? (int?)null : reader.GetInt32(111),
                    WhatWasTheSuburbWhereYouResidedLastWeek_14742 = reader.IsDBNull(112) ? null : reader.GetString(112),
                    WhatWasThePostcodeWhereYouResidedLastWeek_14743 = reader.IsDBNull(113) ? (decimal?)null : reader.GetDecimal(113),
                    WhatIsTheState_14744 = reader.IsDBNull(114) ? null : reader.GetString(114),
                    WhatIsTheState_14744_ResponseChoiceID = reader.IsDBNull(115) ? (int?)null : reader.GetInt32(115),
                    HowManyTimesHaveYouChangedAddressInThePastThreeYearsVispdat_14746 = reader.IsDBNull(116) ? (decimal?)null : reader.GetDecimal(116),
                    WouldYouDescribeYourCurrentHousingAsAdequateAndAffordableEgSafeLongTermSuitableLocationAccessT_14747 = reader.IsDBNull(117) ? null : reader.GetString(117),
                    WouldYouDescribeYourCurrentHousingAsAdequateAndAffordableEgSafeLongTermSuitableLocationAccessT_14747_ResponseChoiceID = reader.IsDBNull(118) ? (int?)null : reader.GetInt32(118),
                    IfCurrentHousingIsNotAdequateDetailsCap_14748 = reader.IsDBNull(119) ? null : reader.GetString(119),
                    HowMuchAreYouPayingWeeklyForHousingCap_14749 = reader.IsDBNull(120) ? (decimal?)null : reader.GetDecimal(120),
                    DoYouHaveACurrentDepartmentOfHousingDohApplicationMp_14750 = reader.IsDBNull(121) ? null : reader.GetString(121),
                    DoYouHaveACurrentDepartmentOfHousingDohApplicationMp_14750_ResponseChoiceID = reader.IsDBNull(122) ? (int?)null : reader.GetInt32(122),
                    IfYouHaveACurrentDohApplicationWhatIsTheApplicationNumber_14751 = reader.IsDBNull(123) ? null : reader.GetString(123),
                    OfficeWhereTheDohApplicationWasLodged_14752 = reader.IsDBNull(124) ? (int?)null : reader.GetInt32(124),
                    Tenure_14754 = reader.IsDBNull(125) ? null : reader.GetString(125),
                    Tenure_14754_ResponseChoiceID = reader.IsDBNull(126) ? (int?)null : reader.GetInt32(126),
                    DwellingType_14755 = reader.IsDBNull(127) ? null : reader.GetString(127),
                    DwellingType_14755_ResponseChoiceID = reader.IsDBNull(128) ? (int?)null : reader.GetInt32(128),
                    LivingArrangements_14756 = reader.IsDBNull(129) ? null : reader.GetString(129),
                    LivingArrangements_14756_ResponseChoiceID = reader.IsDBNull(130) ? (int?)null : reader.GetInt32(130),
                    ConditionsOfOccupancy_14757 = reader.IsDBNull(131) ? null : reader.GetString(131),
                    ConditionsOfOccupancy_14757_ResponseChoiceID = reader.IsDBNull(132) ? (int?)null : reader.GetInt32(132),
                    DwellingType_14758 = reader.IsDBNull(133) ? null : reader.GetString(133),
                    DwellingType_14758_ResponseChoiceID = reader.IsDBNull(134) ? (int?)null : reader.GetInt32(134),
                    LivingArrangements_14759 = reader.IsDBNull(135) ? null : reader.GetString(135),
                    LivingArrangements_14759_ResponseChoiceID = reader.IsDBNull(136) ? (int?)null : reader.GetInt32(136),
                    ConditionsOfOccupancy_14760 = reader.IsDBNull(137) ? null : reader.GetString(137),
                    ConditionsOfOccupancy_14760_ResponseChoiceID = reader.IsDBNull(138) ? (int?)null : reader.GetInt32(138),
                    Tenure_14761 = reader.IsDBNull(139) ? null : reader.GetString(139),
                    Tenure_14761_ResponseChoiceID = reader.IsDBNull(140) ? (int?)null : reader.GetInt32(140),
                    AreYouPregnantOrPlanningToHaveAChildInTheComingYear_14764 = reader.IsDBNull(141) ? null : reader.GetString(141),
                    AreYouPregnantOrPlanningToHaveAChildInTheComingYear_14764_ResponseChoiceID = reader.IsDBNull(142) ? (int?)null : reader.GetInt32(142),
                    IfPregnantWhatIsYourDueDate_14765 = reader.IsDBNull(143) ? (DateTime?)null : reader.GetDateTime(143),
                    HowManyWeeksPregnantAreYou_14766 = reader.IsDBNull(144) ? (decimal?)null : reader.GetDecimal(144),
                    HowManyChildrenCurrentlyInYourFullTimePrimaryCareWhetherTheyAreParticipantsAtMicahOrNot_14768 = reader.IsDBNull(145) ? (decimal?)null : reader.GetDecimal(145),
                    HowManyChildrenDoYouHaveWhoAreNotCurrentlyInYourFullTimeCareWhetherTheyAreParticipantsAtMicahO_14769 = reader.IsDBNull(146) ? (decimal?)null : reader.GetDecimal(146),
                    TotalNumberOfChildrenIncludingThoseInYourfullTimeCareAndThoseNotInFullTimeCare_14770 = reader.IsDBNull(147) ? (decimal?)null : reader.GetDecimal(147),
                    AreYouCurrentlyReceivingServicesToAssistYouWithYourParenting_14772 = reader.IsDBNull(148) ? null : reader.GetString(148),
                    AreYouCurrentlyReceivingServicesToAssistYouWithYourParenting_14772_ResponseChoiceID = reader.IsDBNull(149) ? (int?)null : reader.GetInt32(149),
                    IfYouAreReceivingSupportFromServicesWhoIsThePrimaryServiceAssistingYou_14773 = reader.IsDBNull(150) ? (int?)null : reader.GetInt32(150),
                    IfYouAreReceivingSupportFromServicesWhichOtherServiceIsAssistingYouIfApplicable_14774 = reader.IsDBNull(151) ? (int?)null : reader.GetInt32(151),
                    WhatOtherSupportsFamilyFriendsOtherDoYouHaveToHelpYouWithYourParenting_14775 = reader.IsDBNull(152) ? null : reader.GetString(152),
                    DoYouHaveAnyCurrentConcernsAboutYourParenting_14776 = reader.IsDBNull(153) ? null : reader.GetString(153),
                    DoYouHaveAnyCurrentConcernsAboutYourParenting_14776_ResponseChoiceID = reader.IsDBNull(154) ? (int?)null : reader.GetInt32(154),
                    WhatDoYouThinkIsWorkingWellInRegardToyourParenting_14777 = reader.IsDBNull(155) ? null : reader.GetString(155),
                    WhatDoYouThinkIsNotWorkingWellInRegardToYourParenting_14778 = reader.IsDBNull(156) ? null : reader.GetString(156),
                    WouldYouLikeHelpOrFeelYouNeedSupportInAnyOfTheFollowingAreas_14780 = reader.IsDBNull(157) ? null : reader.GetString(157),
                    WouldYouLikeHelpOrFeelYouNeedSupportInAnyOfTheFollowingAreas_14780_ResponseChoiceID = reader.IsDBNull(158) ? (int?)null : reader.GetInt32(158),
                    HasChildSafetyEverBeenInvolvedWithTheFamilyInThePast_14781 = reader.IsDBNull(159) ? null : reader.GetString(159),
                    HasChildSafetyEverBeenInvolvedWithTheFamilyInThePast_14781_ResponseChoiceID = reader.IsDBNull(160) ? (int?)null : reader.GetInt32(160),
                    IfChildSafetyHasBeenInvolvedInThePastDetails_14782 = reader.IsDBNull(161) ? null : reader.GetString(161),
                    IfChildSafetyHasBeenInvolvedInThePastDetails_14782_ResponseChoiceID = reader.IsDBNull(162) ? (int?)null : reader.GetInt32(162),
                    IsChildSafetyCurrentlyInvolvedWithTheFamily_14783 = reader.IsDBNull(163) ? null : reader.GetString(163),
                    IsChildSafetyCurrentlyInvolvedWithTheFamily_14783_ResponseChoiceID = reader.IsDBNull(164) ? (int?)null : reader.GetInt32(164),
                    IfChildSafetyIsCurrentlyInvolvedWithTheFamilyDetails_14784 = reader.IsDBNull(165) ? null : reader.GetString(165),
                    IfChildSafetyIsCurrentlyInvolvedWithTheFamilyDetails_14784_ResponseChoiceID = reader.IsDBNull(166) ? (int?)null : reader.GetInt32(166),
                    WhichChildSafetyOfficeIsInvolved_14785 = reader.IsDBNull(167) ? (int?)null : reader.GetInt32(167),
                    WhatIsTheNameOfTheChildSafetyOfficerCso_14786 = reader.IsDBNull(168) ? null : reader.GetString(168),
                    DoYouAttendRegularPreAndorAntenatalAppointments_14787 = reader.IsDBNull(169) ? null : reader.GetString(169),
                    DoYouAttendRegularPreAndorAntenatalAppointments_14787_ResponseChoiceID = reader.IsDBNull(170) ? (int?)null : reader.GetInt32(170),
                    AreYouReceivingAssistanceWithTheseConcernsFromProfessionalsUnk_14788 = reader.IsDBNull(171) ? null : reader.GetString(171),
                    AreYouReceivingAssistanceWithTheseConcernsFromProfessionalsUnk_14788_ResponseChoiceID = reader.IsDBNull(172) ? (int?)null : reader.GetInt32(172),
                    AreYouReceivingInformalSupportAndAssistanceFromAnyoneUnk_14789 = reader.IsDBNull(173) ? null : reader.GetString(173),
                    AreYouReceivingInformalSupportAndAssistanceFromAnyoneUnk_14789_ResponseChoiceID = reader.IsDBNull(174) ? (int?)null : reader.GetInt32(174),
                    IfYouAreReceivingInformalSupportDetailsUnk_14790 = reader.IsDBNull(175) ? null : reader.GetString(175),
                    DoesYourUseOfAlcoholOrDrugsContributeToAnyDifficultiesForYouInAnyOfTheFollowingAreasCap_14791 = reader.IsDBNull(176) ? null : reader.GetString(176),
                    DoesYourUseOfAlcoholOrDrugsContributeToAnyDifficultiesForYouInAnyOfTheFollowingAreasCap_14791_ResponseChoiceID = reader.IsDBNull(177) ? (int?)null : reader.GetInt32(177),
                    IfYesByWho_14792 = reader.IsDBNull(178) ? null : reader.GetString(178),
                    AreYouReceivingAppropriateSupportAndTreatmentForThisCondition_14794 = reader.IsDBNull(179) ? null : reader.GetString(179),
                    AreYouReceivingAppropriateSupportAndTreatmentForThisCondition_14794_ResponseChoiceID = reader.IsDBNull(180) ? (int?)null : reader.GetInt32(180),
                    WouldYouLikeAssistanceAccessingAppropriateCaretreatmentsupportForYourDisability_14795 = reader.IsDBNull(181) ? null : reader.GetString(181),
                    WouldYouLikeAssistanceAccessingAppropriateCaretreatmentsupportForYourDisability_14795_ResponseChoiceID = reader.IsDBNull(182) ? (int?)null : reader.GetInt32(182),
                    OtherNotesAboutCareProtectionIssues_14796 = reader.IsDBNull(183) ? null : reader.GetString(183),
                    OtherNotesAboutEducationEmploymentAndFinances_14797 = reader.IsDBNull(184) ? null : reader.GetString(184),
                    OtherNotesAboutHousingIssues_14798 = reader.IsDBNull(185) ? null : reader.GetString(185),
                    IfThereIsPresenceOfDomesticViolencedisruptionToFamilyRelationshipsAndTheParticipantHasRequeste_14799 = reader.IsDBNull(186) ? null : reader.GetString(186),
                    IfThereIsPresenceOfDomesticViolencedisruptionToFamilyRelationshipsAndTheParticipantHasRequeste_14799_ResponseChoiceID = reader.IsDBNull(187) ? (int?)null : reader.GetInt32(187),
                    IfYesWhatDisabilityDiagnosedByAHealthProfessionalDoYouHaveMp_14800 = reader.IsDBNull(188) ? null : reader.GetString(188),
                    IfYesWhatDisabilityDiagnosedByAHealthProfessionalDoYouHaveMp_14800_ResponseChoiceID = reader.IsDBNull(189) ? (int?)null : reader.GetInt32(189),
                    DoYouHaveADisabilityDiagnosedByAHealthProfessionalMp_14801 = reader.IsDBNull(190) ? null : reader.GetString(190),
                    DoYouHaveADisabilityDiagnosedByAHealthProfessionalMp_14801_ResponseChoiceID = reader.IsDBNull(191) ? (int?)null : reader.GetInt32(191),
                    Age_14803 = reader.IsDBNull(192) ? (decimal?)null : reader.GetDecimal(192),
                    IfSomeoneIsInDangerWhatType_14806 = reader.IsDBNull(193) ? null : reader.GetString(193),
                    IfSomeoneIsInDangerWhatType_14806_ResponseChoiceID = reader.IsDBNull(194) ? (int?)null : reader.GetInt32(194),
                    IfYesByWhom_14807 = reader.IsDBNull(195) ? null : reader.GetString(195),
                    DoesYourMentalHealthConditionsContributeToAnyDifficultiesForYouInAnyOfTheFollowingAreasCap_14808 = reader.IsDBNull(196) ? null : reader.GetString(196),
                    DoesYourMentalHealthConditionsContributeToAnyDifficultiesForYouInAnyOfTheFollowingAreasCap_14808_ResponseChoiceID = reader.IsDBNull(197) ? (int?)null : reader.GetInt32(197),
                    Details_14809 = reader.IsDBNull(198) ? null : reader.GetString(198),
                    AreYouReceivingAppropriateCaretreatmentsupportInRegardToYourDisabilityMp_14810 = reader.IsDBNull(199) ? null : reader.GetString(199),
                    AreYouReceivingAppropriateCaretreatmentsupportInRegardToYourDisabilityMp_14810_ResponseChoiceID = reader.IsDBNull(200) ? (int?)null : reader.GetInt32(200),
                    Details_14811 = reader.IsDBNull(201) ? null : reader.GetString(201),
                    IfYesDetails_14812 = reader.IsDBNull(202) ? null : reader.GetString(202),
                    IsTheParticipantChildEnrolledInOneOfTheFollowing_14814 = reader.IsDBNull(203) ? null : reader.GetString(203),
                    IsTheParticipantChildEnrolledInOneOfTheFollowing_14814_ResponseChoiceID = reader.IsDBNull(204) ? (int?)null : reader.GetInt32(204),
                    DoesTheParticipantHaveAccessToThreeHealthyMealsADayEveryDayEgHotMealsForDinnerDietThatIncludes_14816 = reader.IsDBNull(205) ? null : reader.GetString(205),
                    DoesTheParticipantHaveAccessToThreeHealthyMealsADayEveryDayEgHotMealsForDinnerDietThatIncludes_14816_ResponseChoiceID = reader.IsDBNull(206) ? (int?)null : reader.GetInt32(206),
                    WouldYouLikeHelpAccessingFoodForYourFamily_14817 = reader.IsDBNull(207) ? null : reader.GetString(207),
                    WouldYouLikeHelpAccessingFoodForYourFamily_14817_ResponseChoiceID = reader.IsDBNull(208) ? (int?)null : reader.GetInt32(208),
                    Details_14818 = reader.IsDBNull(209) ? null : reader.GetString(209),
                    IfSoHowOftenDoesTheParticipantChildGetThere_14819 = reader.IsDBNull(210) ? null : reader.GetString(210),
                    IfSoHowOftenDoesTheParticipantChildGetThere_14819_ResponseChoiceID = reader.IsDBNull(211) ? (int?)null : reader.GetInt32(211),
                    WouldTheFamilyLikeHelpWithAccessingSchoolOrKindergartenOrAttendingMoreRegularly_14820 = reader.IsDBNull(212) ? null : reader.GetString(212),
                    WouldTheFamilyLikeHelpWithAccessingSchoolOrKindergartenOrAttendingMoreRegularly_14820_ResponseChoiceID = reader.IsDBNull(213) ? (int?)null : reader.GetInt32(213),
                    Details_14821 = reader.IsDBNull(214) ? null : reader.GetString(214),
                    AreImmunisationsUpToDate_14823 = reader.IsDBNull(215) ? null : reader.GetString(215),
                    AreImmunisationsUpToDate_14823_ResponseChoiceID = reader.IsDBNull(216) ? (int?)null : reader.GetInt32(216),
                    DoesTheParticipantChildhaveAnyOfTheFollowingDiagnosedconditions_14824 = reader.IsDBNull(217) ? null : reader.GetString(217),
                    DoesTheParticipantChildhaveAnyOfTheFollowingDiagnosedconditions_14824_ResponseChoiceID = reader.IsDBNull(218) ? (int?)null : reader.GetInt32(218),
                    Details_14825 = reader.IsDBNull(219) ? null : reader.GetString(219),
                    IfYouHaveADiagnosedMentalHealthConditionDetails_14826 = reader.IsDBNull(220) ? null : reader.GetString(220),
                    OfTheseReasonsWhichDoesTheParticipantReportAsBeingTheMainReasonForSeekingAssistance_14827 = reader.IsDBNull(221) ? null : reader.GetString(221),
                    OfTheseReasonsWhichDoesTheParticipantReportAsBeingTheMainReasonForSeekingAssistance_14827_ResponseChoiceID = reader.IsDBNull(222) ? (int?)null : reader.GetInt32(222),
                    DoesThePublicTrusteeAdministerTheParticipantsPersonalFinancesMp_14829 = reader.IsDBNull(223) ? null : reader.GetString(223),
                    DoesThePublicTrusteeAdministerTheParticipantsPersonalFinancesMp_14829_ResponseChoiceID = reader.IsDBNull(224) ? (int?)null : reader.GetInt32(224),
                    WithinDemographicsMedicareNumberWasAnsweredAs_14837 = reader.IsDBNull(225) ? null : reader.GetString(225),
                    WithinDemographicsMedicareNoIndividualIdWasAnsweredAs_14838 = reader.IsDBNull(226) ? null : reader.GetString(226),
                    AtSpdatIndiividualHowManyTimesHaveYouChangedAddressesWasAnsweredAs_14840 = reader.IsDBNull(227) ? (int?)null : reader.GetInt32(227),
                    AtSpdatIndiividualHowManyTimesHaveYouChangedAddressesWasAnsweredAs_14840_DisplayStr = reader.IsDBNull(228) ? null : reader.GetString(228),
                    AsAChildWereYouEverInTheFollowingInstitutions_14841 = reader.IsDBNull(229) ? null : reader.GetString(229),
                    AsAChildWereYouEverInTheFollowingInstitutions_14841_ResponseChoiceID = reader.IsDBNull(230) ? (int?)null : reader.GetInt32(230),
                    AtSpdatIndividualAsAChildWereYouEverInTheFollowingInstitutionsWasAnsweredAsUseResponsesToThisQ_14842 = reader.IsDBNull(231) ? (int?)null : reader.GetInt32(231),
                    AtSpdatIndividualAsAChildWereYouEverInTheFollowingInstitutionsWasAnsweredAsUseResponsesToThisQ_14842_DisplayStr = reader.IsDBNull(232) ? null : reader.GetString(232),
                    AsAnAdultHaveYouEverBeenInTheFollowingInstitutions_14843 = reader.IsDBNull(233) ? null : reader.GetString(233),
                    AsAnAdultHaveYouEverBeenInTheFollowingInstitutions_14843_ResponseChoiceID = reader.IsDBNull(234) ? (int?)null : reader.GetInt32(234),
                    AtSpdatIndividualMainSourceOfIncomeWasAnsweredAs_14846 = reader.IsDBNull(235) ? (int?)null : reader.GetInt32(235),
                    AtSpdatIndividualMainSourceOfIncomeWasAnsweredAs_14846_DisplayStr = reader.IsDBNull(236) ? null : reader.GetString(236),
                    WhatWasTheSchoolEnrolmentAndAttendanceStatusOnPresentation_14847 = reader.IsDBNull(237) ? null : reader.GetString(237),
                    WhatWasTheSchoolEnrolmentAndAttendanceStatusOnPresentation_14847_ResponseChoiceID = reader.IsDBNull(238) ? (int?)null : reader.GetInt32(238),
                    WhatIsTheHighestYearOfSchoolYouCompletedVispdat_14849 = reader.IsDBNull(239) ? null : reader.GetString(239),
                    WhatIsTheHighestYearOfSchoolYouCompletedVispdat_14849_ResponseChoiceID = reader.IsDBNull(240) ? (int?)null : reader.GetInt32(240),
                    MostRecentQhipConsentWasSignedByParticipantOn_14854 = reader.IsDBNull(241) ? (int?)null : reader.GetInt32(241),
                    MostRecentQhipConsentWasSignedByParticipantOn_14854_DisplayStr = reader.IsDBNull(242) ? null : reader.GetString(242),
                    MostRecentMicahStandardConsentWasSignedByParticipantOn_14855 = reader.IsDBNull(243) ? (int?)null : reader.GetInt32(243),
                    MostRecentMicahStandardConsentWasSignedByParticipantOn_14855_DisplayStr = reader.IsDBNull(244) ? null : reader.GetString(244),
                    AtFamilySpdatWhatIsTheTotalLengthOfTimeYouAndYourFamilyHaveNotHadYourOwnTenancyWasAnsweredAs_14857 = reader.IsDBNull(245) ? (int?)null : reader.GetInt32(245),
                    AtFamilySpdatWhatIsTheTotalLengthOfTimeYouAndYourFamilyHaveNotHadYourOwnTenancyWasAnsweredAs_14857_DisplayStr = reader.IsDBNull(246) ? null : reader.GetString(246),
                    AtIndividualSpdatWhatIsTheTotalLengthOfTimeYouHaveLivedOnTheStreetsOrInEmergencyAccommodationW_14858 = reader.IsDBNull(247) ? (int?)null : reader.GetInt32(247),
                    AtIndividualSpdatWhatIsTheTotalLengthOfTimeYouHaveLivedOnTheStreetsOrInEmergencyAccommodationW_14858_DisplayStr = reader.IsDBNull(248) ? null : reader.GetString(248),
                    KeepMeEmpty_14860 = reader.IsDBNull(249) ? (decimal?)null : reader.GetDecimal(249),
                    VariableAtIndividualSpdatWhatIsTheTotalLengthOfTimeYouHaveLivedOnTheStreetsOrInEmergencyAccomm_14861 = reader.IsDBNull(250) ? (decimal?)null : reader.GetDecimal(250),
                    VariableAtFamilySpdatWhatIsTheTotalLengthOfTimeYouAndYourFamilyHaveNotHadYourOwnTenancyWasAnsw_14862 = reader.IsDBNull(251) ? (decimal?)null : reader.GetDecimal(251),
                    VariableAtSpdatIndividualAsAChildWereYouEverInTheFollowingInstitutionsWasAnsweredAs_14865 = reader.IsDBNull(252) ? (decimal?)null : reader.GetDecimal(252),
                    VariableAtSpdatIndividualAsAnAdultHaveYouBeenInTheFollowingInstitutionsWasAnsweredAs_14866 = reader.IsDBNull(253) ? (decimal?)null : reader.GetDecimal(253),
                    VariableAtSpdatIndividualDoYouHaveADisabilityDiagnosedByAHealthProfessionalWasAnsweredAs_14867 = reader.IsDBNull(254) ? (decimal?)null : reader.GetDecimal(254),
                    VariableAtSpdatIndividualMainSourceOfIncomeWasAnsweredAs_14868 = reader.IsDBNull(255) ? (decimal?)null : reader.GetDecimal(255),
                    VariableAtSpdatFamilyMainSourceOfIncomeWasAnsweredAs_14869 = reader.IsDBNull(256) ? (decimal?)null : reader.GetDecimal(256),
                    VariableAtSpdatIndividualWhatIsTheHighestYearOfSchoolYouCompletedWasAnsweredAs_14870 = reader.IsDBNull(257) ? (decimal?)null : reader.GetDecimal(257),
                    VariableAtSpdatFamilyWhatIsTheHighestYearOfSchoolYouCompletedWasAnsweredAs_14871 = reader.IsDBNull(258) ? (decimal?)null : reader.GetDecimal(258),
                    VariableAtSpdatIndividualWhatWasTheSchoolEnrolmentAndAttendanceStatusOnPresentationWasAnswered_14872 = reader.IsDBNull(259) ? (decimal?)null : reader.GetDecimal(259),
                    VariableAtSpdatIndividualHowManyTimesHaveYouChangedAddressesWasAnsweredAs_14873 = reader.IsDBNull(260) ? (decimal?)null : reader.GetDecimal(260),
                    VariableAtSpdatFamilyHowManyTimesHaveYouChangedAddressesWasAnsweredAs_14874 = reader.IsDBNull(261) ? (decimal?)null : reader.GetDecimal(261),
                    AtSpdatFamilyMainSourceOfIncomeWasAnsweredAs_14876 = reader.IsDBNull(262) ? (int?)null : reader.GetInt32(262),
                    AtSpdatFamilyMainSourceOfIncomeWasAnsweredAs_14876_DisplayStr = reader.IsDBNull(263) ? null : reader.GetString(263),
                    AtSpdatFamilyHowManyTimesHaveYouChangedAddressesWasAnsweredAs_14878 = reader.IsDBNull(264) ? (int?)null : reader.GetInt32(264),
                    AtSpdatFamilyHowManyTimesHaveYouChangedAddressesWasAnsweredAs_14878_DisplayStr = reader.IsDBNull(265) ? null : reader.GetString(265),
                    FrequentPresenterHospitalConsent_14881 = reader.IsDBNull(266) ? null : reader.GetString(266),
                    FrequentPresenterHospitalConsent_14881_ResponseChoiceID = reader.IsDBNull(267) ? (int?)null : reader.GetInt32(267),
                    HospitalUrNumber_14882 = reader.IsDBNull(268) ? null : reader.GetString(268),
                    HospitalDischargeDate_14883 = reader.IsDBNull(269) ? (DateTime?)null : reader.GetDateTime(269),
                    HospitalDischargeSummary_14884 = reader.IsDBNull(270) ? null : reader.GetString(270),
                    HospitalDischargeSummary_14884_ResponseChoiceID = reader.IsDBNull(271) ? (int?)null : reader.GetInt32(271),
                    SupportiveHousingHopeStreetLowIncomeOrFormerlyHomeless_14885 = reader.IsDBNull(272) ? null : reader.GetString(272),
                    SupportiveHousingHopeStreetLowIncomeOrFormerlyHomeless_14885_ResponseChoiceID = reader.IsDBNull(273) ? (int?)null : reader.GetInt32(273),
                    LeaseSignDate_14886 = reader.IsDBNull(274) ? (DateTime?)null : reader.GetDateTime(274),
                    MoveInDate_14887 = reader.IsDBNull(275) ? (DateTime?)null : reader.GetDateTime(275),
                    AreYouTicaListedMp_14888 = reader.IsDBNull(276) ? null : reader.GetString(276),
                    AreYouTicaListedMp_14888_ResponseChoiceID = reader.IsDBNull(277) ? (int?)null : reader.GetInt32(277),
                    WithinAddressBookGpHasBeenEnteredAs_14891 = reader.IsDBNull(278) ? (int?)null : reader.GetInt32(278),
                    WithinAddressBookGpHasBeenEnteredAs_14891_DisplayStr = reader.IsDBNull(279) ? null : reader.GetString(279),
                    AtIntakeDoYouHaveARegularGpThatYouAttend_14893 = reader.IsDBNull(280) ? null : reader.GetString(280),
                    AtIntakeDoYouHaveARegularGpThatYouAttend_14893_ResponseChoiceID = reader.IsDBNull(281) ? (int?)null : reader.GetInt32(281),
                    Doyouhaveanappointedsubstitutedecisionmakermp_14902 = reader.IsDBNull(282) ? null : reader.GetString(282),
                    Doyouhaveanappointedsubstitutedecisionmakermp_14902_ResponseChoiceID = reader.IsDBNull(283) ? (int?)null : reader.GetInt32(283),
                    SHSTypeOfServiceActivityTxt_15117 = reader.IsDBNull(284) ? null : reader.GetString(284),
                    Totalefforttimeforparticipant_15588 = reader.IsDBNull(285) ? (int?)null : reader.GetInt32(285),
                    SHSTypeOfServiceActivityNum_16051 = reader.IsDBNull(286) ? null : reader.GetString(286),
                    HowmanystaffdidthistogetherAtmost4_16157 = reader.IsDBNull(287) ? (decimal?)null : reader.GetDecimal(287),
                    Selectyourname_16158 = reader.IsDBNull(288) ? (int?)null : reader.GetInt32(288),
                    MicahTeam_16159 = reader.IsDBNull(289) ? null : reader.GetString(289),
                    Start_16161 = reader.IsDBNull(290) ? null : reader.GetString(290),
                    Endoptional_16162 = reader.IsDBNull(291) ? null : reader.GetString(291),
                    Selectthe2ndstaffperson_16163 = reader.IsDBNull(292) ? (int?)null : reader.GetInt32(292),
                    Whatotherteamassisted_16164 = reader.IsDBNull(293) ? (int?)null : reader.GetInt32(293),
                    WasthisaPATpersonalvisit_16165 = reader.IsDBNull(294) ? null : reader.GetString(294),
                    WasthisaPATpersonalvisit_16165_ResponseChoiceID = reader.IsDBNull(295) ? (int?)null : reader.GetInt32(295),
                    TimespentonbehalfofparticipantPerstaffmember_16166 = reader.IsDBNull(296) ? (int?)null : reader.GetInt32(296),
                    TimespenttravellingNotwithparticipantPerstaffmember_16167 = reader.IsDBNull(297) ? (int?)null : reader.GetInt32(297),
                    TimespentwithparticipantPerstaffmember_16168 = reader.IsDBNull(298) ? (int?)null : reader.GetInt32(298),
                    WastheparticipantfamilypresentduringthisactivityAnswerYesifconversingwithParticipantFamilyonph_16169 = reader.IsDBNull(299) ? null : reader.GetString(299),
                    WastheparticipantfamilypresentduringthisactivityAnswerYesifconversingwithParticipantFamilyonph_16169_ResponseChoiceID = reader.IsDBNull(300) ? (int?)null : reader.GetInt32(300),
                    ContactLocation_16170 = reader.IsDBNull(301) ? null : reader.GetString(301),
                    ContactLocation_16170_ResponseChoiceID = reader.IsDBNull(302) ? (int?)null : reader.GetInt32(302),
                    ContactMethod_16171 = reader.IsDBNull(303) ? null : reader.GetString(303),
                    ContactMethod_16171_ResponseChoiceID = reader.IsDBNull(304) ? (int?)null : reader.GetInt32(304),
                    Ifcontactlocationisotherpleasespecify_16172 = reader.IsDBNull(305) ? null : reader.GetString(305),
                    PhoneContactType_16173 = reader.IsDBNull(306) ? null : reader.GetString(306),
                    PhoneContactType_16173_ResponseChoiceID = reader.IsDBNull(307) ? (int?)null : reader.GetInt32(307),
                    Totaltimespentonbehalfofparticipant_16174 = reader.IsDBNull(308) ? (int?)null : reader.GetInt32(308),
                    Totaltimespenttravelling_16175 = reader.IsDBNull(309) ? (int?)null : reader.GetInt32(309),
                    Totaltimespentwithparticipant_16176 = reader.IsDBNull(310) ? (int?)null : reader.GetInt32(310),
                    Selectthedischargesummaryuploaded_16837 = reader.IsDBNull(311) ? (int?)null : reader.GetInt32(311),
                    Selectthedischargesummaryuploaded_16837_SourceFormID = reader.IsDBNull(312) ? (int?)null : reader.GetInt32(312),
                    Selectthedischargesummaryuploaded_16837_DisplayStr = reader.IsDBNull(313) ? null : reader.GetString(313),
                    SelecttheEDFPConsentuploaded_16838 = reader.IsDBNull(314) ? (int?)null : reader.GetInt32(314),
                    SelecttheEDFPConsentuploaded_16838_SourceFormID = reader.IsDBNull(315) ? (int?)null : reader.GetInt32(315),
                    SelecttheEDFPConsentuploaded_16838_DisplayStr = reader.IsDBNull(316) ? null : reader.GetString(316),
                    Whatisthesourceofinformationthatthispersonmayhaveamentalillnessormentalhealthcondition_16936 = reader.IsDBNull(317) ? null : reader.GetString(317),
                    Whatisthesourceofinformationthatthispersonmayhaveamentalillnessormentalhealthcondition_16936_ResponseChoiceID = reader.IsDBNull(318) ? (int?)null : reader.GetInt32(318),
                    Whatistheparticipantsprimarygoalforenrollinginthisprogram_19812 = reader.IsDBNull(319) ? null : reader.GetString(319),
                    Whatistheparticipantsprimarygoalforenrollinginthisprogram_19812_ResponseChoiceID = reader.IsDBNull(320) ? (int?)null : reader.GetInt32(320),
                    Theskillsoutlinedbelowarerequiredtocompletethisprogrampleaseindicatewhichoftheseskillstheparti_19814 = reader.IsDBNull(321) ? null : reader.GetString(321),
                    Theskillsoutlinedbelowarerequiredtocompletethisprogrampleaseindicatewhichoftheseskillstheparti_19814_ResponseChoiceID = reader.IsDBNull(322) ? (int?)null : reader.GetInt32(322),
                    Whichofthefollowingfearsconcernsassociatedwithcompletingthisprogramapplytothisparticipant_19815 = reader.IsDBNull(323) ? null : reader.GetString(323),
                    Whichofthefollowingfearsconcernsassociatedwithcompletingthisprogramapplytothisparticipant_19815_ResponseChoiceID = reader.IsDBNull(324) ? (int?)null : reader.GetInt32(324),
                    Isthereanyadditionalsupportthatthisparticipantwillrequiretocompletetheprogram_19816 = reader.IsDBNull(325) ? null : reader.GetString(325),
                    Doyouhavedebtsynump_20360 = reader.IsDBNull(326) ? null : reader.GetString(326),
                    Doyouhavedebtsynump_20360_ResponseChoiceID = reader.IsDBNull(327) ? (int?)null : reader.GetInt32(327),
                    DoyouhaveaSPERdebtynump_20361 = reader.IsDBNull(328) ? null : reader.GetString(328),
                    DoyouhaveaSPERdebtynump_20361_ResponseChoiceID = reader.IsDBNull(329) ? (int?)null : reader.GetInt32(329),
                    Whatwasthepostcodeofyourmostrecentpermanentplacetolivet_20362 = reader.IsDBNull(330) ? null : reader.GetString(330),
                    Whatwasthepostcodewhereyouresidedlastweekt_20363 = reader.IsDBNull(331) ? null : reader.GetString(331),
                    AIHWOrganisationID_21823 = reader.IsDBNull(332) ? null : reader.GetString(332),
                    Whatwasthesuburblocalityofyourmostrecentpermanentplacetolive_21824 = reader.IsDBNull(333) ? (int?)null : reader.GetInt32(333),
                    Whatwasthesuburbwhereyouresidedlastweek_21825 = reader.IsDBNull(334) ? (int?)null : reader.GetInt32(334),
                    SubmitsSHSAIHWreports_21832 = reader.IsDBNull(335) ? null : reader.GetString(335),
                    SummaryObservations_23040 = reader.IsDBNull(336) ? null : reader.GetString(336),
                    IstheparticipantcurrentlyreceivinganagreedpackageofsupportthroughtheNationalDisabilityInsuranc_24805 = reader.IsDBNull(337) ? null : reader.GetString(337),
                    IstheparticipantcurrentlyreceivinganagreedpackageofsupportthroughtheNationalDisabilityInsuranc_24805_ResponseChoiceID = reader.IsDBNull(338) ? (int?)null : reader.GetInt32(338),
                    FName = reader.IsDBNull(339) ? null : reader.GetString(339),
                    LName = reader.IsDBNull(340) ? null : reader.GetString(340)
                });
            }

            return AIHWForm;
        }
    }
}