using EtoApi.Models;
using Microsoft.Data.SqlClient;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;

namespace EtoApi.DataAccess
{
    public class BrokeragePaymentRepository
    {
        
        private readonly ISqlConnectionFactory _connectionFactory;
        
        public BrokeragePaymentRepository(ISqlConnectionFactory connectionFactory)
        {
            _connectionFactory = connectionFactory;
        }
        public async Task<List<BrokeragePaymentModel>> GetBrokeragePaymentByIdAsync(int id)
        {
            
            using var connection = await _connectionFactory.CreateOpenConnectionAsync();

            var query = @"
                SELECT                    
                    frm.FormResponseID,
                    frm.FormIdentifier,
                    frm.SubjectID,
                    frm.GroupID,
                    frm.FamilyID,
                    frm.ResponseSetID,
                    frm.FormID,
                    frm.CollectionTypeID,
                    frm.SubjectTypeID,
                    frm.CollectionID,
                    frm.ResponseCreatedDate,
                    frm.ProgramID,
                    frm.AuditStaffID,
                    frm.AuditDate,
                    frm.DataEnteredByID,
                    frm.DraftSavedOn,
                    frm.RemovedDate,
                    frm.Purpose_6508,
                    frm.Purpose_6508_ResponseChoiceID,
                    frm.Context_6510,
                    frm.Context_6510_ResponseChoiceID,
                    frm.PaymentMethod_6511,
                    frm.PaymentMethod_6511_ResponseChoiceID,
                    frm.NumberOfAdults_6514,
                    frm.NumberOfChildren_6515,
                    frm.NumberOfNightsOfaccommodation_6516,
                    frm.AmountRecovered_6518,
                    frm.TransactionDate_6525,
                    frm.Shouldthepaperformbeanonymous_6527,
                    frm.Shouldthepaperformbeanonymous_6527_ResponseChoiceID,
                    frm.JobCode_6528,
                    frm.JobCode_6528_ResponseChoiceID,
                    frm.TransactionAmount_6530,
                    frm.IsGSTincluded_6531,
                    frm.IsGSTincluded_6531_ResponseChoiceID,
                    frm.NonGSTAmount_6532,
                    frm.DetailsofTransaction_6533,
                    frm.PaymentforAIHW_6535,
                    frm.PaymentforAIHW_6535_ResponseChoiceID,
                    frm.PurposeOther_6537,
                    frm.HUBReason_6541,
                    frm.HUBReason_6541_ResponseChoiceID,
                    frm.Haspaymentalreadybeenmadeordoesfinancestillneedtopay_6548,
                    frm.Haspaymentalreadybeenmadeordoesfinancestillneedtopay_6548_ResponseChoiceID,
                    frm.PaymentMethod_6550,
                    frm.PaymentMethod_6550_ResponseChoiceID,
                    frm.WhoseBusinessCreditCard_6551,
                    frm.Vouchertype_6553,
                    frm.Vouchertype_6553_ResponseChoiceID,
                    frm.ChequePayableTo_6554,
                    frm.ChequeDeliveryPostInstructions_6555,
                    frm.ChequeDeliveryPickupInstructions_6556,
                    frm.EFTAccountName_6558,
                    frm.EFTBSB_6559,
                    frm.EFTAccountNumber_6560,
                    frm.BPayBillerCode_6561,
                    frm.BPayBillerReference_6562,
                    frm.Isanyportionofthistransactionrecoverable_6563,
                    frm.Isanyportionofthistransactionrecoverable_6563_ResponseChoiceID,
                    frm.AmountRecovered2_6570,
                    frm.AuthorisingContact1_6571,
                    frm.AuthorisingContact2_6572,
                    frm.AuthorisingContactEmail1_6573,
                    frm.AuthorisingContactEmail2_6574,
                    frm.RecoveryInvoiceAddress1_6577,
                    frm.RecoveryInvoiceAddress2_6578,
                    frm.Worker1_7379,
                    frm.Worker2_7380,
                    frm.Ifpaidbystaffpersonallywhichstaff_7384,
                    frm.RecoveryInvoiceFax1_7389,
                    frm.AuthorisingContactPhone1_7390,
                    frm.RecoveryInvoiceFax2_7394,
                    frm.AuthorisingContactPhone2_7395,
                    frm.TeamLeaderSignOff_8255,
                    frm.TeamLeaderSignOff_8255_Signee,
                    frm.TeamLeaderSignOff_8255_Image,
                    frm.MicahTeam_8276,
                    frm.MicahTeam_8276_ResponseChoiceID,
                    frm.SupplierProvider_8871,
                    frm.RecoveryInvoiceName1_8872,
                    frm.RecoveryInvoiceName2_8873,
                    frm.HUBPurpose_9316,
                    frm.HUBPurpose_9316_ResponseChoiceID,
                    frm.HUBExpenseType_9317,
                    frm.HUBExpenseType_9317_ResponseChoiceID,
                    frm.MicahTeam_11295,
                    frm.TenancyAccessorSustainment_13318,
                    frm.TenancyAccessorSustainment_13318_ResponseChoiceID,
                    frm.AuthorizedBy_16942,
                    frm.AuthorizedBy_16942_Signee,
                    frm.AuthorizedBy_16942_Image,
                    frm.AuthorizedBy_16943,
                    frm.FinanceJobCode_16945,
                    frm.FinanceShortJobCode_16946,
                    frm.SignatureofCreditCardHolder_16947,
                    frm.SignatureofCreditCardHolder_16947_Signee,
                    frm.SignatureofCreditCardHolder_16947_Image,
                    frm.SelectBusinessCreditCardHolder_16948,
                    frm.WhichPettyCashTin_16959,
                    frm.Willthistransactionbenefitonlythisindividualorisitforanentirefamily_21917,
                    frm.Willthistransactionbenefitonlythisindividualorisitforanentirefamily_21917_ResponseChoiceID,
                    frm.ServiceUserDFVOonlyOusterCondition_22992,
                    frm.ServiceUserDFVOonlyOusterCondition_22992_ResponseChoiceID,
                    frm.IstheServiceUsercurrentlylivinginthehome_22993,
                    frm.IstheServiceUsercurrentlylivinginthehome_22993_ResponseChoiceID,
                    frm.NumberofChildrenlivingwiththeServiceUserinhome_22995,
                    frm.DateSafetyUpgradeCompleted_22996,
                    frm.SafetyUpgradeComments_22997,
                    frm.AttachDocumentssuchasInvoicesorreceipts_23268,
                    frm.IfotherWhatisit_23527,
                    frm.ABN_23535,
                    frm.BSBNumber_26963,
                    frm.BrokerageTypeShouldbeansweredonlybytheLotusDRCteam_27196,
                    frm.BrokerageTypeShouldbeansweredonlybytheLotusDRCteam_27196_ResponseChoiceID,
                    frm.Category_28340,
                    frm.Category_28340_ResponseChoiceID,
                    frm.AIHWpurpose_28341,
                    frm.AIHWpurpose_28341_ResponseChoiceID,
                    frm.Ofchildrenunder5_32024,
                    frm.childrenbetween6and12_32025,
                    frm.childrenbetween13and18_32026

                FROM form.f_200 frm
                JOIN Staff s ON frm.AuditStaffID = s.StaffID
                JOIN Entities e ON e.EntityID = frm.MicahTeam_16790
                JOIN SubjectType sub ON sub.SubjectTypeID = frm.SubjectTypeID
                JOIN Programs prg ON prg.ProgramID = frm.ProgramID
                WHERE frm.SubjectID = (SELECT SubjectID FROM SubjectXClient WHERE CLID = @Id)";

            using var command = new SqlCommand(query, connection);
            command.Parameters.AddWithValue("@Id", id);

            var brokeragePayment = new List<BrokeragePaymentModel>();
            using var reader = await command.ExecuteReaderAsync();

            while (await reader.ReadAsync())
            {
                brokeragePayment.Add(new BrokeragePaymentModel
                {

                    FormResponseID = reader.IsDBNull(0) ? (int?)null : reader.GetInt32(0),
                    FormIdentifier = reader.IsDBNull(1) ? null : reader.GetString(1),
                    SubjectID = reader.IsDBNull(2)? (int ?) null : reader.GetInt32(2),
                    GroupID = reader.IsDBNull(3) ? (int?)null : reader.GetInt32(3),
                    FamilyID = reader.IsDBNull(4) ? (int?)null : reader.GetInt32(4),
                    ResponseSetID = reader.IsDBNull(5) ? (int?)null : reader.GetInt32(5),
                    FormID = reader.IsDBNull(6) ? (int?)null : reader.GetInt32(6),
                    CollectionTypeID = reader.IsDBNull(7) ? (int?)null : reader.GetInt32(7),
                    SubjectTypeID = reader.IsDBNull(8) ? (int?)null : reader.GetInt32(8),
                    CollectionID = reader.IsDBNull(9) ? (int?)null : reader.GetInt32(9),
                    ResponseCreatedDate = reader.IsDBNull(10) ? (DateTime?)null : reader.GetDateTime(10),
                    ProgramID = reader.IsDBNull(11) ? (int?)null : reader.GetInt16(11),
                    AuditStaffID = reader.IsDBNull(12) ? (int?)null : reader.GetInt32(12),
                    AuditDate = reader.IsDBNull(13) ? (DateTime?)null : reader.GetDateTime(13),
                    DataEnteredByID = reader.IsDBNull(14) ? (int?)null : reader.GetInt32(14),
                    DraftSavedOn = reader.IsDBNull(15) ? (DateTime?)null : reader.GetDateTime(15),
                    RemovedDate = reader.IsDBNull(16) ? (DateTime?)null : reader.GetDateTime(16),
                    Purpose_6508 = reader.IsDBNull(17) ? null : reader.GetString(17),
                    Purpose_6508_ResponseChoiceID = reader.IsDBNull(18) ? (int?)null : reader.GetInt32(18),
                    Context_6510 = reader.IsDBNull(19) ? null : reader.GetString(19),
                    Context_6510_ResponseChoiceID = reader.IsDBNull(20) ? (int?)null : reader.GetInt32(20),
                    PaymentMethod_6511 = reader.IsDBNull(21) ? null : reader.GetString(21),
                    PaymentMethod_6511_ResponseChoiceID = reader.IsDBNull(22) ? (int?)null : reader.GetInt32(22),
                    NumberOfAdults_6514 = reader.IsDBNull(23) ? (decimal?)null : reader.GetDecimal(23),
                    NumberOfChildren_6515 = reader.IsDBNull(24) ? (decimal?)null : reader.GetDecimal(24),
                    NumberOfNightsOfaccommodation_6516 = reader.IsDBNull(25) ? (decimal?)null : reader.GetDecimal(25),
                    AmountRecovered_6518 = reader.IsDBNull(26) ? (decimal?)null : reader.GetDecimal(26),
                    TransactionDate_6525 = reader.IsDBNull(27) ? (DateTime?)null : reader.GetDateTime(27),
                    Shouldthepaperformbeanonymous_6527 = reader.IsDBNull(28) ? null : reader.GetString(28),
                    Shouldthepaperformbeanonymous_6527_ResponseChoiceID = reader.IsDBNull(29) ? (int?)null : reader.GetInt32(29),
                    JobCode_6528 = reader.IsDBNull(30) ? null : reader.GetString(30),
                    JobCode_6528_ResponseChoiceID = reader.IsDBNull(31) ? (int?)null : reader.GetInt32(31),
                    TransactionAmount_6530 = reader.IsDBNull(32) ? (decimal?)null : reader.GetDecimal(32),
                    IsGSTincluded_6531 = reader.IsDBNull(33) ? null : reader.GetString(33),
                    IsGSTincluded_6531_ResponseChoiceID = reader.IsDBNull(34) ? (int?)null : reader.GetInt32(34),
                    NonGSTAmount_6532 = reader.IsDBNull(35) ? (decimal?)null : reader.GetDecimal(35),
                    DetailsofTransaction_6533 = reader.IsDBNull(36) ? null : reader.GetString(36),
                    PaymentforAIHW_6535 = reader.IsDBNull(37) ? null : reader.GetString(37),
                    PaymentforAIHW_6535_ResponseChoiceID = reader.IsDBNull(38) ? (int?)null : reader.GetInt32(38),
                    PurposeOther_6537 = reader.IsDBNull(39) ? null : reader.GetString(39),
                    HUBReason_6541 = reader.IsDBNull(40) ? null : reader.GetString(40),
                    HUBReason_6541_ResponseChoiceID = reader.IsDBNull(41) ? (int?)null : reader.GetInt32(41),
                    Haspaymentalreadybeenmadeordoesfinancestillneedtopay_6548 = reader.IsDBNull(42) ? null : reader.GetString(42),
                    Haspaymentalreadybeenmadeordoesfinancestillneedtopay_6548_ResponseChoiceID = reader.IsDBNull(43) ? (int?)null : reader.GetInt32(43),
                    PaymentMethod_6550 = reader.IsDBNull(44) ? null : reader.GetString(44),
                    PaymentMethod_6550_ResponseChoiceID = reader.IsDBNull(45) ? (int?)null : reader.GetInt32(45),
                    WhoseBusinessCreditCard_6551 = reader.IsDBNull(46) ? null : reader.GetString(46),
                    Vouchertype_6553 = reader.IsDBNull(47) ? null : reader.GetString(47),
                    Vouchertype_6553_ResponseChoiceID = reader.IsDBNull(48) ? (int?)null : reader.GetInt32(48),
                    ChequePayableTo_6554 = reader.IsDBNull(49) ? null : reader.GetString(49),
                    ChequeDeliveryPostInstructions_6555 = reader.IsDBNull(50) ? null : reader.GetString(50),
                    ChequeDeliveryPickupInstructions_6556 = reader.IsDBNull(51) ? null : reader.GetString(51),
                    EFTAccountName_6558 = reader.IsDBNull(52) ? null : reader.GetString(52),
                    EFTBSB_6559 = reader.IsDBNull(53) ? (decimal?)null : reader.GetDecimal(53),
                    EFTAccountNumber_6560 = reader.IsDBNull(54) ? (decimal?)null : reader.GetDecimal(54),
                    BPayBillerCode_6561 = reader.IsDBNull(55) ? (decimal?)null : reader.GetDecimal(55),
                    BPayBillerReference_6562 = reader.IsDBNull(56) ? null : reader.GetString(56),
                    Isanyportionofthistransactionrecoverable_6563 = reader.IsDBNull(57) ? null : reader.GetString(57),
                    Isanyportionofthistransactionrecoverable_6563_ResponseChoiceID = reader.IsDBNull(58) ? (int?)null : reader.GetInt32(58),
                    AmountRecovered2_6570 = reader.IsDBNull(59) ? (decimal?)null : reader.GetDecimal(59),
                    AuthorisingContact1_6571 = reader.IsDBNull(60) ? null : reader.GetString(60),
                    AuthorisingContact2_6572 = reader.IsDBNull(61) ? null : reader.GetString(61),
                    AuthorisingContactEmail1_6573 = reader.IsDBNull(62) ? null : reader.GetString(62),
                    AuthorisingContactEmail2_6574 = reader.IsDBNull(63) ? null : reader.GetString(63),
                    RecoveryInvoiceAddress1_6577 = reader.IsDBNull(64) ? null : reader.GetString(64),
                    RecoveryInvoiceAddress2_6578 = reader.IsDBNull(65) ? null : reader.GetString(65),
                    Worker1_7379 = reader.IsDBNull(66) ? (int?)null : reader.GetInt32(66),
                    Worker2_7380 = reader.IsDBNull(67) ? (int?)null : reader.GetInt32(67),
                    Ifpaidbystaffpersonallywhichstaff_7384 = reader.IsDBNull(68) ? (int?)null : reader.GetInt32(68),
                    RecoveryInvoiceFax1_7389 = reader.IsDBNull(69) ? null : reader.GetString(69),
                    AuthorisingContactPhone1_7390 = reader.IsDBNull(70) ? null : reader.GetString(70),
                    RecoveryInvoiceFax2_7394 = reader.IsDBNull(71) ? null : reader.GetString(71),
                    AuthorisingContactPhone2_7395 = reader.IsDBNull(72) ? null : reader.GetString(72),
                    TeamLeaderSignOff_8255 = reader.IsDBNull(73) ? null : reader.GetString(73),
                    TeamLeaderSignOff_8255_Signee = reader.IsDBNull(74) ? null : reader.GetString(74),
                    TeamLeaderSignOff_8255_Image = reader.IsDBNull(75) ? null : reader.GetSqlBinary(75).Value,
                    MicahTeam_8276 = reader.IsDBNull(76) ? null : reader.GetString(76),
                    MicahTeam_8276_ResponseChoiceID = reader.IsDBNull(77) ? (int?)null : reader.GetInt32(77),
                    SupplierProvider_8871 = reader.IsDBNull(78) ? (int?)null : reader.GetInt32(78),
                    RecoveryInvoiceName1_8872 = reader.IsDBNull(79) ? (int?)null : reader.GetInt32(79),
                    RecoveryInvoiceName2_8873 = reader.IsDBNull(80) ? (int?)null : reader.GetInt32(80),
                    HUBPurpose_9316 = reader.IsDBNull(81) ? null : reader.GetString(81),
                    HUBPurpose_9316_ResponseChoiceID = reader.IsDBNull(82) ? (int?)null : reader.GetInt32(82),
                    HUBExpenseType_9317 = reader.IsDBNull(83) ? null : reader.GetString(83),
                    HUBExpenseType_9317_ResponseChoiceID = reader.IsDBNull(84) ? (int?)null : reader.GetInt32(84),
                    MicahTeam_11295 = reader.IsDBNull(85) ? (int?)null : reader.GetInt32(85),
                    TenancyAccessorSustainment_13318 = reader.IsDBNull(86) ? null : reader.GetString(86),
                    TenancyAccessorSustainment_13318_ResponseChoiceID = reader.IsDBNull(87) ? (int?)null : reader.GetInt32(87),
                    AuthorizedBy_16942 = reader.IsDBNull(88) ? null : reader.GetString(88),
                    AuthorizedBy_16942_Signee = reader.IsDBNull(89) ? null : reader.GetString(89),
                    AuthorizedBy_16942_Image = reader.IsDBNull(90) ? null : reader.GetSqlBinary(90).Value,
                    AuthorizedBy_16943 = reader.IsDBNull(91) ? (int?)null : reader.GetInt32(91),
                    FinanceJobCode_16945 = reader.IsDBNull(92) ? (int?)null : reader.GetInt32(92),
                    FinanceShortJobCode_16946 = reader.IsDBNull(93) ? null : reader.GetString(93),
                    SignatureofCreditCardHolder_16947 = reader.IsDBNull(94) ? null : reader.GetString(94),
                    SignatureofCreditCardHolder_16947_Signee = reader.IsDBNull(95) ? null : reader.GetString(95),
                    SignatureofCreditCardHolder_16947_Image = reader.IsDBNull(96) ? null : reader.GetSqlBinary(96).Value,
                    SelectBusinessCreditCardHolder_16948 = reader.IsDBNull(97) ? (int?)null : reader.GetInt32(97),
                    WhichPettyCashTin_16959 = reader.IsDBNull(98) ? (int?)null : reader.GetInt32(98),
                    Willthistransactionbenefitonlythisindividualorisitforanentirefamily_21917 = reader.IsDBNull(99) ? null : reader.GetString(99),
                    Willthistransactionbenefitonlythisindividualorisitforanentirefamily_21917_ResponseChoiceID = reader.IsDBNull(100) ? (int?)null : reader.GetInt32(100),
                    ServiceUserDFVOonlyOusterCondition_22992 = reader.IsDBNull(101) ? null : reader.GetString(101),
                    ServiceUserDFVOonlyOusterCondition_22992_ResponseChoiceID = reader.IsDBNull(102) ? (int?)null : reader.GetInt32(102),
                    IstheServiceUsercurrentlylivinginthehome_22993 = reader.IsDBNull(103) ? null : reader.GetString(103),
                    IstheServiceUsercurrentlylivinginthehome_22993_ResponseChoiceID = reader.IsDBNull(104) ? (int?)null : reader.GetInt32(104),
                    NumberofChildrenlivingwiththeServiceUserinhome_22995 = reader.IsDBNull(105) ? (decimal?)null : reader.GetDecimal(105),
                    DateSafetyUpgradeCompleted_22996 = reader.IsDBNull(106) ? (DateTime?)null : reader.GetDateTime(106),
                    SafetyUpgradeComments_22997 = reader.IsDBNull(107) ? null : reader.GetString(107),
                    AttachDocumentssuchasInvoicesorreceipts_23268 = reader.IsDBNull(108) ? (int?)null : reader.GetInt32(108),
                    IfotherWhatisit_23527 = reader.IsDBNull(109) ? null : reader.GetString(109),
                    ABN_23535 = reader.IsDBNull(110) ? null : reader.GetString(110),
                    BSBNumber_26963 = reader.IsDBNull(111) ? null : reader.GetString(111),
                    BrokerageTypeShouldbeansweredonlybytheLotusDRCteam_27196 = reader.IsDBNull(112) ? null : reader.GetString(112),
                    BrokerageTypeShouldbeansweredonlybytheLotusDRCteam_27196_ResponseChoiceID = reader.IsDBNull(113) ? (int?)null : reader.GetInt32(113),
                    Category_28340 = reader.IsDBNull(114) ? null : reader.GetString(114),
                    Category_28340_ResponseChoiceID = reader.IsDBNull(115) ? (int?)null : reader.GetInt32(115),
                    AIHWpurpose_28341 = reader.IsDBNull(116) ? null : reader.GetString(116),
                    AIHWpurpose_28341_ResponseChoiceID = reader.IsDBNull(117) ? (int?)null : reader.GetInt32(117),
                    Ofchildrenunder5_32024 = reader.IsDBNull(118) ? (decimal?)null : reader.GetDecimal(118),
                    childrenbetween6and12_32025 = reader.IsDBNull(119) ? (decimal?)null : reader.GetDecimal(119),
                    childrenbetween13and18_32026 = reader.IsDBNull(120) ? (decimal?)null : reader.GetDecimal(120),

                });
            }

            return brokeragePayment;
        }
    }
}
