using System.Collections.Generic;
using System.Threading.Tasks;
using EtoApi.Models;
using Microsoft.Data.SqlClient;

namespace EtoApi.DataAccess
{
    public class LotusNotesRepository
    {
       private readonly ISqlConnectionFactory _connectionFactory;

        public LotusNotesRepository(ISqlConnectionFactory connectionFactory)
            {
                _connectionFactory = connectionFactory;
            }

        public async Task<List<LotusNotes>> GetLotusNotesByIdAsync(int id)
        {
             using var connection = await _connectionFactory.CreateOpenConnectionAsync();

            var query = @"
                SELECT
                FormResponseID,
                FormIdentifier,
                SubjectID,
                GroupID,
                FamilyID,
                ResponseSetID,
                FormID,
                CollectionTypeID,
                frm.SubjectTypeID,
                CollectionID,
                ResponseCreatedDate,
                frm.ProgramID,
                frm.AuditStaffID,
                frm.AuditDate,
                DataEnteredByID,
                DraftSavedOn,
                RemovedDate,
                ContactMethod_27348,
                ContactMethod_27348_ResponseChoiceID,
                ContactLocation_27349,
                ContactLocation_27349_ResponseChoiceID,
                HowmanystaffdidthistogetherAtmost4_27350,
                TimespentwithparticipantPerstaffmember_27351,
                TimespentonbehalfofparticipantPerstaffmember_27352,
                TimespenttravellingNotwithparticipantPerstaffmember_27353,
                Totaltimespentwithparticipant_27354,
                Totaltimespentonbehalfofparticipant_27355,
                Totaltimespenttravelling_27356,
                Totalefforttimeforparticipant_27357,
                Selectyourname_27358,
                MicahTeam_27359,
                Selectthe2ndstaffperson_27360,
                Whatotherteamassisted_27361,
                ServiceType_27366,
                ServiceType_27366_ResponseChoiceID,
                ServiceSetting_27367,
                ServiceSetting_27367_ResponseChoiceID,
                InterpreterPresent_27368,
                InterpreterPresent_27368_ResponseChoiceID,
                Notes_27369,
                Disabilityimpairmentorconditionindicator_27372,
                Disabilityimpairmentorconditionindicator_27372_ResponseChoiceID,
                Selectallofthereasonsforseekingassistance_27378,
                Selectallofthereasonsforseekingassistance_27378_ResponseChoiceID,
                SelectDomain_27386,
                SelectDomain_27386_ResponseChoiceID,
                SelectthemainreasonforseekingassistanceNotethemainreasonmustbeoneofthereasonstickedabove_27408,
                SelectthemainreasonforseekingassistanceNotethemainreasonmustbeoneofthereasonstickedabove_27408_ResponseChoiceID,
                Selectyourlocation_27412,
                Selectyourlocation_27412_ResponseChoiceID,
                StartTime_27430,
                EndTimeoptional_27431,
                ContactCategory_27854,
                ContactCategory_27854_ResponseChoiceID,
                ContactDomain_27855,
                ContactDomain_27855_ResponseChoiceID,
                WhatWDYNwasthisactioninresponseto_27856,
                WhatWDYNwasthisactioninresponseto_27856_SourceFormID,
                WhatWDYNwasthisactioninresponseto_27856_DisplayStr,
                ContactLocation_28145,
                ContactLocation_28145_ResponseChoiceID,
                Program_28235,
                Program_28235_ResponseChoiceID,
                TypeofNote_28236,
                TypeofNote_28236_ResponseChoiceID,
                Checkallfurtherassessmentsthatneedtobecompleted_29024,
                Checkallfurtherassessmentsthatneedtobecompleted_29024_ResponseChoiceID,
                Scoreassessedby_29027,
                Scoreassessedby_29027_ResponseChoiceID,
                Isthisthefirstpreorlastpostscore_29028,
                Isthisthefirstpreorlastpostscore_29028_ResponseChoiceID,
                DomainGoals_29029,
                DomainGoals_29029_ResponseChoiceID,
                ChangedbehavioursScore1Noprogressinchangingbehavioursinareasrelevanttoclientsneedsandcircumsta_29032,
                ChangedbehavioursScore1Noprogressinchangingbehavioursinareasrelevanttoclientsneedsandcircumsta_29032_ResponseChoiceID,
                ChangedimmediatecrisisScore1NoprogressinreducingthenegativeimpactoftheimmediatecrisisScore2Lim_29033,
                ChangedimmediatecrisisScore1NoprogressinreducingthenegativeimpactoftheimmediatecrisisScore2Lim_29033_ResponseChoiceID,
                ChangedknowledgeandaccesstoinformationScore1Noprogressinincreasingaccesstoinformationandknowle_29103,
                ChangedknowledgeandaccesstoinformationScore1Noprogressinincreasingaccesstoinformationandknowle_29103_ResponseChoiceID,
                ChangedSkillsScore1NoprogressinincreasingskillsinareasrelevanttoclientsneedsandcircumstancesSc_29104,
                ChangedSkillsScore1NoprogressinincreasingskillsinareasrelevanttoclientsneedsandcircumstancesSc_29104_ResponseChoiceID,
                EmpowermentchoiceandcontroltomakeowndecisionsScore1Noprogressinincreasingconfidenceandexercisi_29105,
                EmpowermentchoiceandcontroltomakeowndecisionsScore1Noprogressinincreasingconfidenceandexercisi_29105_ResponseChoiceID,
                EngagementwithrelevantsupportservicesScore1Noprogressinincreasingengagementwithsupportservices_29106,
                EngagementwithrelevantsupportservicesScore1Noprogressinincreasingengagementwithsupportservices_29106_ResponseChoiceID,
                DomainCircumstances_29107,
                DomainCircumstances_29107_ResponseChoiceID,
                AgeappropriatedevelopmentScore1Significantnegativeimpactofpoorageappropriatedevelopmentonindep_29109,
                AgeappropriatedevelopmentScore1Significantnegativeimpactofpoorageappropriatedevelopmentonindep_29109_ResponseChoiceID,
                CommunityparticipationnetworksScore1Significantnegativeimpactofpoorcommunityparticipationnetwo_29110,
                CommunityparticipationnetworksScore1Significantnegativeimpactofpoorcommunityparticipationnetwo_29110_ResponseChoiceID,
                EducationandskillstrainingScore1Significantnegativeimpactoflackofengagementwitheducationandtra_29111,
                EducationandskillstrainingScore1Significantnegativeimpactoflackofengagementwitheducationandtra_29111_ResponseChoiceID,
                EmploymentScore1Significantnegativeimpactoflackofemploymentonindependenceparticipationandwellb_29112,
                EmploymentScore1Significantnegativeimpactoflackofemploymentonindependenceparticipationandwellb_29112_ResponseChoiceID,
                FamilyFunctioningScore1Significantnegativeimpactofpoorfamilyfunctioningonindependenceparticipa_29113,
                FamilyFunctioningScore1Significantnegativeimpactofpoorfamilyfunctioningonindependenceparticipa_29113_ResponseChoiceID,
                FinancialresilienceScore1Significantnegativeimpactofpoorfinancialresilienceonindependenceparti_29114,
                FinancialresilienceScore1Significantnegativeimpactofpoorfinancialresilienceonindependenceparti_29114_ResponseChoiceID,
                HousingScore1Significantnegativeimpactofpoorhousingonindependenceparticipationandwellbeingegro_29115,
                HousingScore1Significantnegativeimpactofpoorhousingonindependenceparticipationandwellbeingegro_29115_ResponseChoiceID,
                MaterialwellbeingandbasicnecessitiesScore1Significantnegativeimpactoflackofbasicmaterialresour_29116,
                MaterialwellbeingandbasicnecessitiesScore1Significantnegativeimpactoflackofbasicmaterialresour_29116_ResponseChoiceID,
                MentalhealthwellbeingandselfcareScore1Significantnegativeimpactofpoormentalhealthwellbeingands_29117,
                MentalhealthwellbeingandselfcareScore1Significantnegativeimpactofpoormentalhealthwellbeingands_29117_ResponseChoiceID,
                PersonalsafetyScore1Significantnegativeimpactofpoorpersonalandfamilysafetyonindependencepartic_29118,
                PersonalsafetyScore1Significantnegativeimpactofpoorpersonalandfamilysafetyonindependencepartic_29118_ResponseChoiceID,
                PhysicalhealthScore1Significantnegativeimpactofpoorphysicalhealthonindependenceparticipationan_29119,
                PhysicalhealthScore1Significantnegativeimpactofpoorphysicalhealthonindependenceparticipationan_29119_ResponseChoiceID,
                DomainSatisfaction_29120,
                DomainSatisfaction_29120_ResponseChoiceID,
                Iambetterabletodealwithissuesthatsoughthelpwith_29122,
                Iambetterabletodealwithissuesthatsoughthelpwith_29122_ResponseChoiceID,
                IamsatisfiedwiththeservicesIhavereceived_29123,
                IamsatisfiedwiththeservicesIhavereceived_29123_ResponseChoiceID,
                Theservicelistenedtomeandunderstoodmyissues_29124,
                Theservicelistenedtomeandunderstoodmyissues_29124_ResponseChoiceID,
                Partofthisengagementwasareferraldone_29458,
                Partofthisengagementwasareferraldone_29458_ResponseChoiceID,
                Referredto_29459,
                Scoring_31496,
                prg.ProgramName,
                e.EntityName,
                s.FName,
                s.LName
                FROM form.f_524 frm
                JOIN Staff s ON frm.AuditStaffID = s.StaffID
                JOIN Entities e ON e.EntityID = frm.MicahTeam_27359
                JOIN SubjectType sub ON sub.SubjectTypeID = frm.SubjectTypeID
                JOIN Programs prg ON prg.ProgramID = frm.ProgramID
                WHERE frm.SubjectID = (SELECT SubjectID FROM SubjectXClient WHERE CLID = @Id) ORDER BY frm.AuditDate DESC";

            using var command = new SqlCommand(query, connection);
            command.Parameters.AddWithValue("@Id", id);

            var lotusNotes = new List<LotusNotes>();
            using var reader = await command.ExecuteReaderAsync();

            while (await reader.ReadAsync())
            {
                lotusNotes.Add(new LotusNotes
                {
                    FormResponseID = reader.IsDBNull(0) ? (int?)null : reader.GetInt32(0),
                    FormIdentifier = reader.IsDBNull(1) ? null : reader.GetString(1),
                    SubjectID = reader.IsDBNull(2) ? (int?)null : reader.GetInt32(2),
                    GroupID = reader.IsDBNull(3) ? (int?)null : reader.GetInt32(3),
                    FamilyID = reader.IsDBNull(4) ? (int?)null : reader.GetInt32(4),
                    ResponseSetID = reader.IsDBNull(5) ? (int?)null : reader.GetInt32(5),
                    FormID = reader.IsDBNull(6) ? (int?)null : reader.GetInt32(6),
                    CollectionTypeID = reader.IsDBNull(7) ? (int?)null : reader.GetInt32(7),
                    SubjectTypeID = reader.IsDBNull(8) ? (int?)null : reader.GetInt32(8),
                    CollectionID = reader.IsDBNull(9) ? (int?)null : reader.GetInt32(9),
                    ResponseCreatedDate = reader.IsDBNull(10) ? (DateTime?)null : reader.GetDateTime(10),
                    ProgramID = reader.IsDBNull(11) ? (int?)null : reader.GetInt16(11),
                    AuditStaffID = reader.IsDBNull(12) ? (int?)null : reader.GetInt32(12),
                    AuditDate = reader.IsDBNull(13) ? (DateTime?)null : reader.GetDateTime(13),
                    DataEnteredByID = reader.IsDBNull(14) ? (int?)null : reader.GetInt32(14),
                    DraftSavedOn = reader.IsDBNull(15) ? (DateTime?)null : reader.GetDateTime(15),
                    RemovedDate = reader.IsDBNull(16) ? (DateTime?)null : reader.GetDateTime(16),
                    ContactMethod_27348 = reader.IsDBNull(17) ? null : reader.GetString(17),
                    ContactMethod_27348_ResponseChoiceID = reader.IsDBNull(18) ? (int?)null : reader.GetInt32(18),
                    ContactLocation_27349 = reader.IsDBNull(19) ? null : reader.GetString(19),
                    ContactLocation_27349_ResponseChoiceID = reader.IsDBNull(20) ? (int?)null : reader.GetInt32(20),
                    HowmanystaffdidthistogetherAtmost4_27350 = reader.IsDBNull(21) ? (decimal?)null : reader.GetDecimal(21),
                    TimespentwithparticipantPerstaffmember_27351 = reader.IsDBNull(22) ? (int?)null : reader.GetInt32(22),
                    TimespentonbehalfofparticipantPerstaffmember_27352 = reader.IsDBNull(23) ? (int?)null : reader.GetInt32(23),
                    TimespenttravellingNotwithparticipantPerstaffmember_27353 = reader.IsDBNull(24) ? (int?)null : reader.GetInt32(24),
                    Totaltimespentwithparticipant_27354 = reader.IsDBNull(25) ? (int?)null : reader.GetInt32(25),
                    Totaltimespentonbehalfofparticipant_27355 = reader.IsDBNull(26) ? (int?)null : reader.GetInt32(26),
                    Totaltimespenttravelling_27356 = reader.IsDBNull(27) ? (int?)null : reader.GetInt32(27),
                    Totalefforttimeforparticipant_27357 = reader.IsDBNull(28) ? (int?)null : reader.GetInt32(28),
                    Selectyourname_27358 = reader.IsDBNull(29) ? (int?)null : reader.GetInt32(29),
                    MicahTeam_27359 = reader.IsDBNull(30) ? null : reader.GetInt32(30),
                    Selectthe2ndstaffperson_27360 = reader.IsDBNull(31) ? null : reader.GetInt32(31),
                    Whatotherteamassisted_27361 = reader.IsDBNull(32) ? null : reader.GetInt32(32),
                    ServiceType_27366 = reader.IsDBNull(33) ? null : reader.GetString(33),
                    ServiceType_27366_ResponseChoiceID = reader.IsDBNull(34) ? (int?)null : reader.GetInt32(34),
                    ServiceSetting_27367 = reader.IsDBNull(35) ? null : reader.GetString(35),
                    ServiceSetting_27367_ResponseChoiceID = reader.IsDBNull(36) ? (int?)null : reader.GetInt32(36),
                    InterpreterPresent_27368 = reader.IsDBNull(37) ? null : reader.GetString(37),
                    InterpreterPresent_27368_ResponseChoiceID = reader.IsDBNull(38) ? (int?)null : reader.GetInt32(38),
                    Notes_27369 = reader.IsDBNull(39) ? null : reader.GetString(39),
                    Disabilityimpairmentorconditionindicator_27372 = reader.IsDBNull(40) ? null : reader.GetString(40),
                    Disabilityimpairmentorconditionindicator_27372_ResponseChoiceID = reader.IsDBNull(41) ? (int?)null : reader.GetInt32(41),
                    Selectallofthereasonsforseekingassistance_27378 = reader.IsDBNull(42) ? null : reader.GetString(42),
                    Selectallofthereasonsforseekingassistance_27378_ResponseChoiceID = reader.IsDBNull(43) ? (int?)null : reader.GetInt32(43),
                    SelectDomain_27386 = reader.IsDBNull(44) ? null : reader.GetString(44),
                    SelectDomain_27386_ResponseChoiceID = reader.IsDBNull(45) ? (int?)null : reader.GetInt32(45),
                    SelectthemainreasonforseekingassistanceNotethemainreasonmustbeoneofthereasonstickedabove_27408 = reader.IsDBNull(46) ? null : reader.GetString(46),
                    SelectthemainreasonforseekingassistanceNotethemainreasonmustbeoneofthereasonstickedabove_27408_ResponseChoiceID = reader.IsDBNull(47) ? (int?)null : reader.GetInt32(47),
                    Selectyourlocation_27412 = reader.IsDBNull(48) ? null : reader.GetString(48),
                    Selectyourlocation_27412_ResponseChoiceID = reader.IsDBNull(49) ? (int?)null : reader.GetInt32(49),
                    StartTime_27430 = reader.IsDBNull(50) ? null : reader.GetString(50),
                    EndTimeoptional_27431 = reader.IsDBNull(51) ? null : reader.GetString(51),
                    ContactCategory_27854 = reader.IsDBNull(52) ? null : reader.GetString(52),
                    ContactCategory_27854_ResponseChoiceID = reader.IsDBNull(53) ? (int?)null : reader.GetInt32(53),
                    ContactDomain_27855 = reader.IsDBNull(54) ? null : reader.GetString(54),
                    ContactDomain_27855_ResponseChoiceID = reader.IsDBNull(55) ? (int?)null : reader.GetInt32(55),
                    WhatWDYNwasthisactioninresponseto_27856 = reader.IsDBNull(56) ? null : reader.GetInt32(56),
                    WhatWDYNwasthisactioninresponseto_27856_SourceFormID = reader.IsDBNull(57) ? (int?)null : reader.GetInt32(57),
                    WhatWDYNwasthisactioninresponseto_27856_DisplayStr = reader.IsDBNull(58) ? null : reader.GetString(58),
                    ContactLocation_28145 = reader.IsDBNull(59) ? null : reader.GetString(59),
                    ContactLocation_28145_ResponseChoiceID = reader.IsDBNull(60) ? (int?)null : reader.GetInt32(60),
                    Program_28235 = reader.IsDBNull(61) ? null : reader.GetString(61),
                    Program_28235_ResponseChoiceID = reader.IsDBNull(62) ? (int?)null : reader.GetInt32(62),
                    TypeofNote_28236 = reader.IsDBNull(63) ? null : reader.GetString(63),
                    TypeofNote_28236_ResponseChoiceID = reader.IsDBNull(64) ? (int?)null : reader.GetInt32(64),
                    Checkallfurtherassessmentsthatneedtobecompleted_29024 = reader.IsDBNull(65) ? null : reader.GetString(65),
                    Checkallfurtherassessmentsthatneedtobecompleted_29024_ResponseChoiceID = reader.IsDBNull(66) ? (int?)null : reader.GetInt32(66),
                    Scoreassessedby_29027 = reader.IsDBNull(67) ? null : reader.GetString(67),
                    Scoreassessedby_29027_ResponseChoiceID = reader.IsDBNull(68) ? (int?)null : reader.GetInt32(68),
                    Isthisthefirstpreorlastpostscore_29028 = reader.IsDBNull(69) ? null : reader.GetString(69),
                    Isthisthefirstpreorlastpostscore_29028_ResponseChoiceID = reader.IsDBNull(70) ? (int?)null : reader.GetInt32(70),
                    DomainGoals_29029 = reader.IsDBNull(71) ? null : reader.GetString(71),
                    DomainGoals_29029_ResponseChoiceID = reader.IsDBNull(72) ? (int?)null : reader.GetInt32(72),
                    ChangedbehavioursScore1Noprogressinchangingbehavioursinareasrelevanttoclientsneedsandcircumsta_29032 = reader.IsDBNull(73) ? null : reader.GetString(73),
                    ChangedbehavioursScore1Noprogressinchangingbehavioursinareasrelevanttoclientsneedsandcircumsta_29032_ResponseChoiceID = reader.IsDBNull(74) ? (int?)null : reader.GetInt32(74),
                    ChangedimmediatecrisisScore1NoprogressinreducingthenegativeimpactoftheimmediatecrisisScore2Lim_29033 = reader.IsDBNull(75) ? null : reader.GetString(75),
                    ChangedimmediatecrisisScore1NoprogressinreducingthenegativeimpactoftheimmediatecrisisScore2Lim_29033_ResponseChoiceID = reader.IsDBNull(76) ? (int?)null : reader.GetInt32(76),
                    ChangedknowledgeandaccesstoinformationScore1Noprogressinincreasingaccesstoinformationandknowle_29103 = reader.IsDBNull(77) ? null : reader.GetString(77),
                    ChangedknowledgeandaccesstoinformationScore1Noprogressinincreasingaccesstoinformationandknowle_29103_ResponseChoiceID = reader.IsDBNull(78) ? (int?)null : reader.GetInt32(78),
                    ChangedSkillsScore1NoprogressinincreasingskillsinareasrelevanttoclientsneedsandcircumstancesSc_29104 = reader.IsDBNull(79) ? null : reader.GetString(79),
                    ChangedSkillsScore1NoprogressinincreasingskillsinareasrelevanttoclientsneedsandcircumstancesSc_29104_ResponseChoiceID = reader.IsDBNull(80) ? (int?)null : reader.GetInt32(80),
                    EmpowermentchoiceandcontroltomakeowndecisionsScore1Noprogressinincreasingconfidenceandexercisi_29105 = reader.IsDBNull(81) ? null : reader.GetString(81),
                    EmpowermentchoiceandcontroltomakeowndecisionsScore1Noprogressinincreasingconfidenceandexercisi_29105_ResponseChoiceID = reader.IsDBNull(82) ? (int?)null : reader.GetInt32(82),
                    EngagementwithrelevantsupportservicesScore1Noprogressinincreasingengagementwithsupportservices_29106 = reader.IsDBNull(83) ? null : reader.GetString(83),
                    EngagementwithrelevantsupportservicesScore1Noprogressinincreasingengagementwithsupportservices_29106_ResponseChoiceID = reader.IsDBNull(84) ? (int?)null : reader.GetInt32(84),
                    DomainCircumstances_29107 = reader.IsDBNull(85) ? null : reader.GetString(85),
                    DomainCircumstances_29107_ResponseChoiceID = reader.IsDBNull(86) ? (int?)null : reader.GetInt32(86),
                    AgeappropriatedevelopmentScore1Significantnegativeimpactofpoorageappropriatedevelopmentonindep_29109 = reader.IsDBNull(87) ? null : reader.GetString(87),
                    AgeappropriatedevelopmentScore1Significantnegativeimpactofpoorageappropriatedevelopmentonindep_29109_ResponseChoiceID = reader.IsDBNull(88) ? (int?)null : reader.GetInt32(88),
                    CommunityparticipationnetworksScore1Significantnegativeimpactofpoorcommunityparticipationnetwo_29110 = reader.IsDBNull(89) ? null : reader.GetString(89),
                    CommunityparticipationnetworksScore1Significantnegativeimpactofpoorcommunityparticipationnetwo_29110_ResponseChoiceID = reader.IsDBNull(90) ? (int?)null : reader.GetInt32(90),
                    EducationandskillstrainingScore1Significantnegativeimpactoflackofengagementwitheducationandtra_29111 = reader.IsDBNull(91) ? null : reader.GetString(91),
                    EducationandskillstrainingScore1Significantnegativeimpactoflackofengagementwitheducationandtra_29111_ResponseChoiceID = reader.IsDBNull(92) ? (int?)null : reader.GetInt32(92),
                    EmploymentScore1Significantnegativeimpactoflackofemploymentonindependenceparticipationandwellb_29112 = reader.IsDBNull(93) ? null : reader.GetString(93),
                    EmploymentScore1Significantnegativeimpactoflackofemploymentonindependenceparticipationandwellb_29112_ResponseChoiceID = reader.IsDBNull(94) ? (int?)null : reader.GetInt32(94),
                    FamilyFunctioningScore1Significantnegativeimpactofpoorfamilyfunctioningonindependenceparticipa_29113 = reader.IsDBNull(95) ? null : reader.GetString(95),
                    FamilyFunctioningScore1Significantnegativeimpactofpoorfamilyfunctioningonindependenceparticipa_29113_ResponseChoiceID = reader.IsDBNull(96) ? (int?)null : reader.GetInt32(96),
                    FinancialresilienceScore1Significantnegativeimpactofpoorfinancialresilienceonindependenceparti_29114 = reader.IsDBNull(97) ? null : reader.GetString(97),
                    FinancialresilienceScore1Significantnegativeimpactofpoorfinancialresilienceonindependenceparti_29114_ResponseChoiceID = reader.IsDBNull(98) ? (int?)null : reader.GetInt32(98),
                    HousingScore1Significantnegativeimpactofpoorhousingonindependenceparticipationandwellbeingegro_29115 = reader.IsDBNull(99) ? null : reader.GetString(99),
                    HousingScore1Significantnegativeimpactofpoorhousingonindependenceparticipationandwellbeingegro_29115_ResponseChoiceID = reader.IsDBNull(100) ? (int?)null : reader.GetInt32(100),
                    MaterialwellbeingandbasicnecessitiesScore1Significantnegativeimpactoflackofbasicmaterialresour_29116 = reader.IsDBNull(101) ? null : reader.GetString(101),
                    MaterialwellbeingandbasicnecessitiesScore1Significantnegativeimpactoflackofbasicmaterialresour_29116_ResponseChoiceID = reader.IsDBNull(102) ? (int?)null : reader.GetInt32(102),
                    MentalhealthwellbeingandselfcareScore1Significantnegativeimpactofpoormentalhealthwellbeingands_29117 = reader.IsDBNull(103) ? null : reader.GetString(103),
                    MentalhealthwellbeingandselfcareScore1Significantnegativeimpactofpoormentalhealthwellbeingands_29117_ResponseChoiceID = reader.IsDBNull(104) ? (int?)null : reader.GetInt32(104),
                    PersonalsafetyScore1Significantnegativeimpactofpoorpersonalandfamilysafetyonindependencepartic_29118 = reader.IsDBNull(105) ? null : reader.GetString(105),
                    PersonalsafetyScore1Significantnegativeimpactofpoorpersonalandfamilysafetyonindependencepartic_29118_ResponseChoiceID = reader.IsDBNull(106) ? (int?)null : reader.GetInt32(106),
                    PhysicalhealthScore1Significantnegativeimpactofpoorphysicalhealthonindependenceparticipationan_29119 = reader.IsDBNull(107) ? null : reader.GetString(107),
                    PhysicalhealthScore1Significantnegativeimpactofpoorphysicalhealthonindependenceparticipationan_29119_ResponseChoiceID = reader.IsDBNull(108) ? (int?)null : reader.GetInt32(108),
                    DomainSatisfaction_29120 = reader.IsDBNull(109) ? null : reader.GetString(109),
                    DomainSatisfaction_29120_ResponseChoiceID = reader.IsDBNull(110) ? (int?)null : reader.GetInt32(110),
                    Iambetterabletodealwithissuesthatsoughthelpwith_29122 = reader.IsDBNull(111) ? null : reader.GetString(111),
                    Iambetterabletodealwithissuesthatsoughthelpwith_29122_ResponseChoiceID = reader.IsDBNull(112) ? (int?)null : reader.GetInt32(112),
                    IamsatisfiedwiththeservicesIhavereceived_29123 = reader.IsDBNull(113) ? null : reader.GetString(113),
                    IamsatisfiedwiththeservicesIhavereceived_29123_ResponseChoiceID = reader.IsDBNull(114) ? (int?)null : reader.GetInt32(114),
                    Theservicelistenedtomeandunderstoodmyissues_29124 = reader.IsDBNull(115) ? null : reader.GetString(115),
                    Theservicelistenedtomeandunderstoodmyissues_29124_ResponseChoiceID = reader.IsDBNull(116) ? (int?)null : reader.GetInt32(116),
                    Partofthisengagementwasareferraldone_29458 = reader.IsDBNull(117) ? null : reader.GetString(117),
                    Partofthisengagementwasareferraldone_29458_ResponseChoiceID = reader.IsDBNull(118) ? (int?)null : reader.GetInt32(118),
                    Referredto_29459 = reader.IsDBNull(119) ? null : reader.GetString(119),
                    Scoring_31496 = reader.IsDBNull(120) ? null : reader.GetString(120),
                    ProgramName = reader.IsDBNull(121) ? null : reader.GetString(121),
                    EntityName = reader.IsDBNull(122) ? null : reader.GetString(122),
                    FName = reader.IsDBNull(123) ? null : reader.GetString(123),
                    LName = reader.IsDBNull(124) ? null : reader.GetString(124)

                });

            }
            return lotusNotes;
        }
    }
}
