using EtoApi.Models;
using Microsoft.Data.SqlClient;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;

namespace EtoApi.DataAccess
{
    public class RedressNotesRepository
    {
        
        private readonly ISqlConnectionFactory _connectionFactory;
        

        public RedressNotesRepository(ISqlConnectionFactory connectionFactory)
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<List<RedressNotesModel>> GetRedressNotesByIdAsync(int id)
        {
            
            using var connection = await _connectionFactory.CreateOpenConnectionAsync();

            var query = @"
                SELECT    
                  frm.FormResponseID,
                    frm.FormIdentifier,
                    frm.SubjectID,
                    frm.GroupID,
                    frm.FamilyID,
                    frm.ResponseSetID,
                    frm.FormID,
                    frm.CollectionTypeID,
                    frm.SubjectTypeID,
                    frm.CollectionID,
                    frm.ResponseCreatedDate,
                    frm.ProgramID,
                    frm.AuditStaffID,
                    frm.AuditDate,
                    frm.DataEnteredByID,
                    frm.DraftSavedOn,
                    frm.RemovedDate,
                    frm.ContactMethod_28605,
                    frm.ContactMethod_28605_ResponseChoiceID,
                    frm.ContactLocation_28606,
                    frm.ContactLocation_28606_ResponseChoiceID,
                    frm.ServiceType_28607,
                    frm.ServiceType_28607_ResponseChoiceID,
                    frm.ServiceSetting_28608,
                    frm.ServiceSetting_28608_ResponseChoiceID,
                    frm.InterpreterPresent_28609,
                    frm.InterpreterPresent_28609_ResponseChoiceID,
                    frm.Selectyourlocation_28614,
                    frm.Selectyourlocation_28614_ResponseChoiceID,
                    frm.ContactLocation_28617,
                    frm.ContactLocation_28617_ResponseChoiceID,
                    frm.TypeofNote_28619,
                    frm.TypeofNote_28619_ResponseChoiceID,
                    frm.Notes_28620,
                    frm.HowmanystaffdidthistogetherAtmost4_28621,
                    frm.TimespentwithparticipantPerstaffmember_28625,
                    frm.TimespentonbehalfofparticipantPerstaffmember_28626,
                    frm.TimespenttravellingNotwithparticipantPerstaffmember_28627,
                    frm.Totaltimespentwithparticipant_28628,
                    frm.Totaltimespentonbehalfofparticipant_28629,
                    frm.Totaltimespenttravelling_28630,
                    frm.Totalefforttimeforparticipant_28631,
                    frm.Selectyourname_28632,
                    frm.MicahTeam_28633,
                    frm.Selectthe2ndstaffperson_28634,
                    frm.Whatotherteamassisted_28635,
                    frm.WhatWDYNwasthisactioninresponseto_28639,
                    frm.WhatWDYNwasthisactioninresponseto_28639_SourceFormID,
                    frm.WhatWDYNwasthisactioninresponseto_28639_DisplayStr,
                    frm.StatusofNRSapplication_28727,
                    frm.StatusofNRSapplication_28727_ResponseChoiceID,
                    frm.IftheparticipantisunabletoaccesstheSchemewasawarmreferraltoanothersuitableservicegiven_28728,
                    frm.IftheparticipantisunabletoaccesstheSchemewasawarmreferraltoanothersuitableservicegiven_28728_ResponseChoiceID,
                    frm.Whatistheserviceprovidersnamesparticipantwasreferredto_28729,
                    frm.Wastheparticipantsupportedwerereferredtoknowmorelegalorfinancialcounsellingservice_28730,
                    frm.Wastheparticipantsupportedwerereferredtoknowmorelegalorfinancialcounsellingservice_28730_ResponseChoiceID,
                    frm.Referredto_28731,
                    frm.Referredto_28731_ResponseChoiceID,
                    frm.Otherservices_28732,
                    frm.Wastheparticipantreferredtoamainstreamorspecialistsupportservice_28736,
                    frm.Wastheparticipantreferredtoamainstreamorspecialistsupportservice_28736_ResponseChoiceID,
                    frm.Wastheparticipantreferredtoacounsellingserviceduringtheapplicationprocess_28737,
                    frm.Wastheparticipantreferredtoacounsellingserviceduringtheapplicationprocess_28737_ResponseChoiceID,
                    frm.Wastheparticipantreferredtoamainstreamorspecialistsupportservice_28738,
                    frm.Wastheparticipantreferredtoamainstreamorspecialistsupportservice_28738_ResponseChoiceID,
                    frm.CounsellingService_28739,
                    frm.CounsellingService_28739_ResponseChoiceID,
                    frm.Recognitionofsexualabuse_28743,
                    frm.Recognitionofsexualabuse_28743_ResponseChoiceID,
                    frm.Recognitionofimpactofsexualabuse_28744,
                    frm.Recognitionofimpactofsexualabuse_28744_ResponseChoiceID,
                    frm.Recognitionofrelatednonsexualabuse_28745,
                    frm.Recognitionofrelatednonsexualabuse_28745_ResponseChoiceID,
                    frm.Recognitionpersonwasinstitutionallyvulnerable_28746,
                    frm.Recognitionpersonwasinstitutionallyvulnerable_28746_ResponseChoiceID,
                    frm.Recognitionofextremecircumstancesofsexualabuse_28747,
                    frm.Recognitionofextremecircumstancesofsexualabuse_28747_ResponseChoiceID,
                    frm.HasparticipantacceptedDPR_28749,
                    frm.HasparticipantacceptedDPR_28749_ResponseChoiceID,
                    frm.HasDPRcommenced_28750,
                    frm.HasDPRcommenced_28750_ResponseChoiceID,
                    frm.Whoisthefacilitator_28751,
                    frm.Datesetforapology_28752,
                    frm.Followuprequirednotes_28753,
                    frm.HasparticipantaccpetedCPC_28755,
                    frm.HasparticipantaccpetedCPC_28755_ResponseChoiceID,
                    frm.HasCPCcommenced_28756,
                    frm.HasCPCcommenced_28756_ResponseChoiceID,
                    frm.Whoisthepractitioner_28757,
                    frm.Hasawarmreferralbeenmade_28861,
                    frm.Hasawarmreferralbeenmade_28861_ResponseChoiceID,
                    frm.HasaNRSofferbeenreceived_28862,
                    frm.HasaNRSofferbeenreceived_28862_ResponseChoiceID,
                    frm.Scoreassessedby_29634,
                    frm.Scoreassessedby_29634_ResponseChoiceID,
                    frm.Isthisthefirstpreorlastpostscore_29635,
                    frm.Isthisthefirstpreorlastpostscore_29635_ResponseChoiceID,
                    frm.DomainGoals_29636,
                    frm.DomainGoals_29636_ResponseChoiceID,
                    frm.ChangedknowledgeandaccesstoinformationScore1Noprogressinincreasingaccesstoinformationandknowle_29638,
                    frm.ChangedknowledgeandaccesstoinformationScore1Noprogressinincreasingaccesstoinformationandknowle_29638_ResponseChoiceID,
                    frm.EmpowermentchoiceandcontroltomakeowndecisionsScore1Noprogressinincreasingconfidenceandexercisi_29639,
                    frm.EmpowermentchoiceandcontroltomakeowndecisionsScore1Noprogressinincreasingconfidenceandexercisi_29639_ResponseChoiceID,
                    frm.EngagementwithrelevantsupportservicesScore1Noprogressinincreasingengagementwithsupportservices_29640,
                    frm.EngagementwithrelevantsupportservicesScore1Noprogressinincreasingengagementwithsupportservices_29640_ResponseChoiceID,
                    frm.DomainCircumstances_29641,
                    frm.DomainCircumstances_29641_ResponseChoiceID,
                    frm.CommunityparticipationnetworksScore1Significantnegativeimpactofpoorcommunityparticipationnetwo_29643,
                    frm.CommunityparticipationnetworksScore1Significantnegativeimpactofpoorcommunityparticipationnetwo_29643_ResponseChoiceID,
                    frm.MentalhealthwellbeingandselfcareScore1Significantnegativeimpactofpoormentalhealthwellbeingands_29644,
                    frm.MentalhealthwellbeingandselfcareScore1Significantnegativeimpactofpoormentalhealthwellbeingands_29644_ResponseChoiceID,
                    frm.PersonalandfamilysafetyScore1Significantnegativeimpactofpoorpersonalandfamilysafetyonindepende_29645,
                    frm.PersonalandfamilysafetyScore1Significantnegativeimpactofpoorpersonalandfamilysafetyonindepende_29645_ResponseChoiceID,
                    frm.DomainSatisfaction_29646,
                    frm.DomainSatisfaction_29646_ResponseChoiceID,
                    frm.Iambetterabletodealwithissuesthatsoughthelpwith_29648,
                    frm.Iambetterabletodealwithissuesthatsoughthelpwith_29648_ResponseChoiceID,
                    frm.IamsatisfiedwiththeservicesIhavereceived_29649,
                    frm.IamsatisfiedwiththeservicesIhavereceived_29649_ResponseChoiceID,
                    frm.Theservicelistenedtomeandunderstoodmyissues_29650,
                    frm.Theservicelistenedtomeandunderstoodmyissues_29650_ResponseChoiceID,
                    frm.ChangedbehavioursScore1Noprogressinchangingbehavioursinareasrelevanttoclientsneedsandcircumsta_29651,
                    frm.ChangedbehavioursScore1Noprogressinchangingbehavioursinareasrelevanttoclientsneedsandcircumsta_29651_ResponseChoiceID,
                    frm.ChangedimmediatecrisisScore1NoprogressinreducingthenegativeimpactoftheimmediatecrisisScore2Lim_29652,
                    frm.ChangedimmediatecrisisScore1NoprogressinreducingthenegativeimpactoftheimmediatecrisisScore2Lim_29652_ResponseChoiceID,
                    frm.ChangedSkillsScore1NoprogressinincreasingskillsinareasrelevanttoclientsneedsandcircumstancesSc_29653,
                    frm.ChangedSkillsScore1NoprogressinincreasingskillsinareasrelevanttoclientsneedsandcircumstancesSc_29653_ResponseChoiceID,
                    frm.AgeappropriatedevelopmentScore1Significantnegativeimpactofpoorageappropriatedevelopmentonindep_29654,
                    frm.AgeappropriatedevelopmentScore1Significantnegativeimpactofpoorageappropriatedevelopmentonindep_29654_ResponseChoiceID,
                    frm.EducationandskillstrainingScore1Significantnegativeimpactoflackofengagementwitheducationandtra_29655,
                    frm.EducationandskillstrainingScore1Significantnegativeimpactoflackofengagementwitheducationandtra_29655_ResponseChoiceID,
                    frm.EmploymentScore1Significantnegativeimpactoflackofemploymentonindependenceparticipationandwellb_29657,
                    frm.EmploymentScore1Significantnegativeimpactoflackofemploymentonindependenceparticipationandwellb_29657_ResponseChoiceID,
                    frm.FamilyFunctioningScore1Significantnegativeimpactofpoorfamilyfunctioningonindependenceparticipa_29658,
                    frm.FamilyFunctioningScore1Significantnegativeimpactofpoorfamilyfunctioningonindependenceparticipa_29658_ResponseChoiceID,
                    frm.FinancialresilienceScore1Significantnegativeimpactofpoorfinancialresilienceonindependenceparti_29659,
                    frm.FinancialresilienceScore1Significantnegativeimpactofpoorfinancialresilienceonindependenceparti_29659_ResponseChoiceID,
                    frm.HousingScore1Significantnegativeimpactofpoorhousingonindependenceparticipationandwellbeingegro_29660,
                    frm.HousingScore1Significantnegativeimpactofpoorhousingonindependenceparticipationandwellbeingegro_29660_ResponseChoiceID,
                    frm.MaterialwellbeingandbasicnecessitiesScore1Significantnegativeimpactoflackofbasicmaterialresour_29661,
                    frm.MaterialwellbeingandbasicnecessitiesScore1Significantnegativeimpactoflackofbasicmaterialresour_29661_ResponseChoiceID,
                    frm.PhysicalhealthScore1Significantnegativeimpactofpoorphysicalhealthonindependenceparticipationan_29662,
                    frm.PhysicalhealthScore1Significantnegativeimpactofpoorphysicalhealthonindependenceparticipationan_29662_ResponseChoiceID,
                    frm.Scoring_31497,

                    s.FName,
                    s.LName,
                    sub.Name,
                    prg.ProgramName,
                    e.EntityName

                FROM form.f_546 frm
                JOIN Staff s ON frm.AuditStaffID = s.StaffID
                JOIN Entities e ON e.EntityID = frm.MicahTeam_28633
                JOIN SubjectType sub ON sub.SubjectTypeID = frm.SubjectTypeID
                JOIN Programs prg ON prg.ProgramID = frm.ProgramID
                WHERE frm.SubjectID = (SELECT SubjectID FROM SubjectXClient WHERE CLID = @Id)";

            using var command = new SqlCommand(query, connection);
            command.Parameters.AddWithValue("@Id", id);

            var redressnotesrepo = new List<RedressNotesModel>();
            using var reader = await command.ExecuteReaderAsync();

            while (await reader.ReadAsync())
            {
                redressnotesrepo.Add(new RedressNotesModel
                {


                    FormResponseID = reader.IsDBNull(0) ? (int?)null : reader.GetInt32(0),
                    FormIdentifier = reader.IsDBNull(1) ? null : reader.GetString(1),
                    SubjectID = reader.IsDBNull(2) ? (int?)null : reader.GetInt32(2),
                    GroupID = reader.IsDBNull(3) ? (int?)null : reader.GetInt32(3),
                    FamilyID = reader.IsDBNull(4) ? (int?)null : reader.GetInt32(4),
                    ResponseSetID = reader.IsDBNull(5) ? (int?)null : reader.GetInt32(5),
                    FormID = reader.IsDBNull(6) ? (int?)null : reader.GetInt32(6),
                    CollectionTypeID = reader.IsDBNull(7) ? (int?)null : reader.GetInt32(7),
                    SubjectTypeID = reader.IsDBNull(8) ? (int?)null : reader.GetInt32(8),
                    CollectionID = reader.IsDBNull(9) ? (int?)null : reader.GetInt32(9),
                    ResponseCreatedDate = reader.IsDBNull(10) ? (DateTime?)null : reader.GetDateTime(10),
                    ProgramID = reader.IsDBNull(11) ? (int?)null : reader.GetInt16(11),
                    AuditStaffID = reader.IsDBNull(12) ? (int?)null : reader.GetInt32(12),
                    AuditDate = reader.IsDBNull(13) ? (DateTime?)null : reader.GetDateTime(13),
                    DataEnteredByID = reader.IsDBNull(14) ? (int?)null : reader.GetInt32(14),
                    DraftSavedOn = reader.IsDBNull(15) ? (DateTime?)null : reader.GetDateTime(15),
                    RemovedDate = reader.IsDBNull(16) ? (DateTime?)null : reader.GetDateTime(16),
                    ContactMethod_28605 = reader.IsDBNull(17) ? null : reader.GetString(17),
                    ContactMethod_28605_ResponseChoiceID = reader.IsDBNull(18) ? (int?)null : reader.GetInt32(18),
                    ContactLocation_28606 = reader.IsDBNull(19) ? null : reader.GetString(19),
                    ContactLocation_28606_ResponseChoiceID = reader.IsDBNull(20) ? (int?)null : reader.GetInt32(20),
                    ServiceType_28607 = reader.IsDBNull(21) ? null : reader.GetString(21),
                    ServiceType_28607_ResponseChoiceID = reader.IsDBNull(22) ? (int?)null : reader.GetInt32(22),
                    ServiceSetting_28608 = reader.IsDBNull(23) ? null : reader.GetString(23),
                    ServiceSetting_28608_ResponseChoiceID = reader.IsDBNull(24) ? (int?)null : reader.GetInt32(24),
                    InterpreterPresent_28609 = reader.IsDBNull(25) ? null : reader.GetString(25),
                    InterpreterPresent_28609_ResponseChoiceID = reader.IsDBNull(26) ? (int?)null : reader.GetInt32(26),
                    Selectyourlocation_28614 = reader.IsDBNull(27) ? null : reader.GetString(27),
                    Selectyourlocation_28614_ResponseChoiceID = reader.IsDBNull(28) ? (int?)null : reader.GetInt32(28),
                    ContactLocation_28617 = reader.IsDBNull(29) ? null : reader.GetString(29),
                    ContactLocation_28617_ResponseChoiceID = reader.IsDBNull(30) ? (int?)null : reader.GetInt32(30),
                    TypeofNote_28619 = reader.IsDBNull(31) ? null : reader.GetString(31),
                    TypeofNote_28619_ResponseChoiceID = reader.IsDBNull(32) ? (int?)null : reader.GetInt32(32),
                    Notes_28620 = reader.IsDBNull(33) ? null : reader.GetString(33),
                    HowmanystaffdidthistogetherAtmost4_28621 = reader.IsDBNull(34) ? (decimal?)null : reader.GetDecimal(34),
                    TimespentwithparticipantPerstaffmember_28625 = reader.IsDBNull(35) ? (int?)null : reader.GetInt32(35),
                    TimespentonbehalfofparticipantPerstaffmember_28626 = reader.IsDBNull(36) ? (int?)null : reader.GetInt32(36),
                    TimespenttravellingNotwithparticipantPerstaffmember_28627 = reader.IsDBNull(37) ? (int?)null : reader.GetInt32(37),
                    Totaltimespentwithparticipant_28628 = reader.IsDBNull(38) ? (int?)null : reader.GetInt32(38),
                    Totaltimespentonbehalfofparticipant_28629 = reader.IsDBNull(39) ? (int?)null : reader.GetInt32(39),
                    Totaltimespenttravelling_28630 = reader.IsDBNull(40) ? (int?)null : reader.GetInt32(40),
                    Totalefforttimeforparticipant_28631 = reader.IsDBNull(41) ? (int?)null : reader.GetInt32(41),
                    Selectyourname_28632 = reader.IsDBNull(42) ? (int?)null : reader.GetInt32(42),
                    MicahTeam_28633 = reader.IsDBNull(43) ? (int?)null : reader.GetInt32(43),
                    Selectthe2ndstaffperson_28634 = reader.IsDBNull(44) ? (int?)null : reader.GetInt32(44),
                    Whatotherteamassisted_28635 = reader.IsDBNull(45) ? (int?)null : reader.GetInt32(45),
                    WhatWDYNwasthisactioninresponseto_28639 = reader.IsDBNull(46) ? (int?)null : reader.GetInt32(46),
                    WhatWDYNwasthisactioninresponseto_28639_SourceFormID = reader.IsDBNull(47) ? (int?)null : reader.GetInt32(47),
                    WhatWDYNwasthisactioninresponseto_28639_DisplayStr = reader.IsDBNull(48) ? null : reader.GetString(48),
                    StatusofNRSapplication_28727 = reader.IsDBNull(49) ? null : reader.GetString(49),
                    StatusofNRSapplication_28727_ResponseChoiceID = reader.IsDBNull(50) ? (int?)null : reader.GetInt32(50),
                    IftheparticipantisunabletoaccesstheSchemewasawarmreferraltoanothersuitableservicegiven_28728 = reader.IsDBNull(51) ? null : reader.GetString(51),
                    IftheparticipantisunabletoaccesstheSchemewasawarmreferraltoanothersuitableservicegiven_28728_ResponseChoiceID = reader.IsDBNull(52) ? (int?)null : reader.GetInt32(52),
                    Whatistheserviceprovidersnamesparticipantwasreferredto_28729 = reader.IsDBNull(53) ? null : reader.GetString(53),
                    Wastheparticipantsupportedwerereferredtoknowmorelegalorfinancialcounsellingservice_28730 = reader.IsDBNull(54) ? null : reader.GetString(54),
                    Wastheparticipantsupportedwerereferredtoknowmorelegalorfinancialcounsellingservice_28730_ResponseChoiceID = reader.IsDBNull(55) ? (int?)null : reader.GetInt32(55),
                    Referredto_28731 = reader.IsDBNull(56) ? null : reader.GetString(56),
                    Referredto_28731_ResponseChoiceID = reader.IsDBNull(57) ? (int?)null : reader.GetInt32(57),
                    Otherservices_28732 = reader.IsDBNull(58) ? null : reader.GetString(58),
                    Wastheparticipantreferredtoamainstreamorspecialistsupportservice_28736 = reader.IsDBNull(59) ? null : reader.GetString(59),
                    Wastheparticipantreferredtoamainstreamorspecialistsupportservice_28736_ResponseChoiceID = reader.IsDBNull(60) ? (int?)null : reader.GetInt32(60),
                    Wastheparticipantreferredtoacounsellingserviceduringtheapplicationprocess_28737 = reader.IsDBNull(61) ? null : reader.GetString(61),
                    Wastheparticipantreferredtoacounsellingserviceduringtheapplicationprocess_28737_ResponseChoiceID = reader.IsDBNull(62) ? (int?)null : reader.GetInt32(62),
                    Wastheparticipantreferredtoamainstreamorspecialistsupportservice_28738 = reader.IsDBNull(63) ? null : reader.GetString(63),
                    Wastheparticipantreferredtoamainstreamorspecialistsupportservice_28738_ResponseChoiceID = reader.IsDBNull(64) ? (int?)null : reader.GetInt32(64),
                    CounsellingService_28739 = reader.IsDBNull(65) ? null : reader.GetString(65),
                    CounsellingService_28739_ResponseChoiceID = reader.IsDBNull(66) ? (int?)null : reader.GetInt32(66),
                    Recognitionofsexualabuse_28743 = reader.IsDBNull(67) ? null : reader.GetString(67),
                    Recognitionofsexualabuse_28743_ResponseChoiceID = reader.IsDBNull(68) ? (int?)null : reader.GetInt32(68),
                    Recognitionofimpactofsexualabuse_28744 = reader.IsDBNull(69) ? null : reader.GetString(69),
                    Recognitionofimpactofsexualabuse_28744_ResponseChoiceID = reader.IsDBNull(70) ? (int?)null : reader.GetInt32(70),
                    Recognitionofrelatednonsexualabuse_28745 = reader.IsDBNull(71) ? null : reader.GetString(71),
                    Recognitionofrelatednonsexualabuse_28745_ResponseChoiceID = reader.IsDBNull(72) ? (int?)null : reader.GetInt32(72),
                    Recognitionpersonwasinstitutionallyvulnerable_28746 = reader.IsDBNull(73) ? null : reader.GetString(73),
                    Recognitionpersonwasinstitutionallyvulnerable_28746_ResponseChoiceID = reader.IsDBNull(74) ? (int?)null : reader.GetInt32(74),
                    Recognitionofextremecircumstancesofsexualabuse_28747 = reader.IsDBNull(75) ? null : reader.GetString(75),
                    Recognitionofextremecircumstancesofsexualabuse_28747_ResponseChoiceID = reader.IsDBNull(76) ? (int?)null : reader.GetInt32(76),
                    HasparticipantacceptedDPR_28749 = reader.IsDBNull(77) ? null : reader.GetString(77),
                    HasparticipantacceptedDPR_28749_ResponseChoiceID = reader.IsDBNull(78) ? (int?)null : reader.GetInt32(78),
                    HasDPRcommenced_28750 = reader.IsDBNull(79) ? null : reader.GetString(79),
                    HasDPRcommenced_28750_ResponseChoiceID = reader.IsDBNull(80) ? (int?)null : reader.GetInt32(80),
                    Whoisthefacilitator_28751 = reader.IsDBNull(81) ? null : reader.GetString(81),
                    Datesetforapology_28752 = reader.IsDBNull(82) ? (DateTime?)null : reader.GetDateTime(82),
                    Followuprequirednotes_28753 = reader.IsDBNull(83) ? null : reader.GetString(83),
                    HasparticipantaccpetedCPC_28755 = reader.IsDBNull(84) ? null : reader.GetString(84),
                    HasparticipantaccpetedCPC_28755_ResponseChoiceID = reader.IsDBNull(85) ? (int?)null : reader.GetInt32(85),
                    HasCPCcommenced_28756 = reader.IsDBNull(86) ? null : reader.GetString(86),
                    HasCPCcommenced_28756_ResponseChoiceID = reader.IsDBNull(87) ? (int?)null : reader.GetInt32(87),
                    Whoisthepractitioner_28757 = reader.IsDBNull(88) ? null : reader.GetString(88),
                    Hasawarmreferralbeenmade_28861 = reader.IsDBNull(89) ? null : reader.GetString(89),
                    Hasawarmreferralbeenmade_28861_ResponseChoiceID = reader.IsDBNull(90) ? (int?)null : reader.GetInt32(90),
                    HasaNRSofferbeenreceived_28862 = reader.IsDBNull(91) ? null : reader.GetString(91),
                    HasaNRSofferbeenreceived_28862_ResponseChoiceID = reader.IsDBNull(92) ? (int?)null : reader.GetInt32(92),
                    Scoreassessedby_29634 = reader.IsDBNull(93) ? null : reader.GetString(93),
                    Scoreassessedby_29634_ResponseChoiceID = reader.IsDBNull(94) ? (int?)null : reader.GetInt32(94),
                    Isthisthefirstpreorlastpostscore_29635 = reader.IsDBNull(95) ? null : reader.GetString(95),
                    Isthisthefirstpreorlastpostscore_29635_ResponseChoiceID = reader.IsDBNull(96) ? (int?)null : reader.GetInt32(96),
                    DomainGoals_29636 = reader.IsDBNull(97) ? null : reader.GetString(97),
                    DomainGoals_29636_ResponseChoiceID = reader.IsDBNull(98) ? (int?)null : reader.GetInt32(98),
                    ChangedknowledgeandaccesstoinformationScore1Noprogressinincreasingaccesstoinformationandknowle_29638 = reader.IsDBNull(99) ? null : reader.GetString(99),
                    ChangedknowledgeandaccesstoinformationScore1Noprogressinincreasingaccesstoinformationandknowle_29638_ResponseChoiceID = reader.IsDBNull(100) ? (int?)null : reader.GetInt32(100),
                    EmpowermentchoiceandcontroltomakeowndecisionsScore1Noprogressinincreasingconfidenceandexercisi_29639 = reader.IsDBNull(101) ? null : reader.GetString(101),
                    EmpowermentchoiceandcontroltomakeowndecisionsScore1Noprogressinincreasingconfidenceandexercisi_29639_ResponseChoiceID = reader.IsDBNull(102) ? (int?)null : reader.GetInt32(102),
                    EngagementwithrelevantsupportservicesScore1Noprogressinincreasingengagementwithsupportservices_29640 = reader.IsDBNull(103) ? null : reader.GetString(103),
                    EngagementwithrelevantsupportservicesScore1Noprogressinincreasingengagementwithsupportservices_29640_ResponseChoiceID = reader.IsDBNull(104) ? (int?)null : reader.GetInt32(104),
                    DomainCircumstances_29641 = reader.IsDBNull(105) ? null : reader.GetString(105),
                    DomainCircumstances_29641_ResponseChoiceID = reader.IsDBNull(106) ? (int?)null : reader.GetInt32(106),
                    CommunityparticipationnetworksScore1Significantnegativeimpactofpoorcommunityparticipationnetwo_29643 = reader.IsDBNull(107) ? null : reader.GetString(107),
                    CommunityparticipationnetworksScore1Significantnegativeimpactofpoorcommunityparticipationnetwo_29643_ResponseChoiceID = reader.IsDBNull(108) ? (int?)null : reader.GetInt32(108),
                    MentalhealthwellbeingandselfcareScore1Significantnegativeimpactofpoormentalhealthwellbeingands_29644 = reader.IsDBNull(109) ? null : reader.GetString(109),
                    MentalhealthwellbeingandselfcareScore1Significantnegativeimpactofpoormentalhealthwellbeingands_29644_ResponseChoiceID = reader.IsDBNull(110) ? (int?)null : reader.GetInt32(110),
                    PersonalandfamilysafetyScore1Significantnegativeimpactofpoorpersonalandfamilysafetyonindepende_29645 = reader.IsDBNull(111) ? null : reader.GetString(111),
                    PersonalandfamilysafetyScore1Significantnegativeimpactofpoorpersonalandfamilysafetyonindepende_29645_ResponseChoiceID = reader.IsDBNull(112) ? (int?)null : reader.GetInt32(112),
                    DomainSatisfaction_29646 = reader.IsDBNull(113) ? null : reader.GetString(113),
                    DomainSatisfaction_29646_ResponseChoiceID = reader.IsDBNull(114) ? (int?)null : reader.GetInt32(114),
                    Iambetterabletodealwithissuesthatsoughthelpwith_29648 = reader.IsDBNull(115) ? null : reader.GetString(115),
                    Iambetterabletodealwithissuesthatsoughthelpwith_29648_ResponseChoiceID = reader.IsDBNull(116) ? (int?)null : reader.GetInt32(116),
                    IamsatisfiedwiththeservicesIhavereceived_29649 = reader.IsDBNull(117) ? null : reader.GetString(117),
                    IamsatisfiedwiththeservicesIhavereceived_29649_ResponseChoiceID = reader.IsDBNull(118) ? (int?)null : reader.GetInt32(118),
                    Theservicelistenedtomeandunderstoodmyissues_29650 = reader.IsDBNull(119) ? null : reader.GetString(119),
                    Theservicelistenedtomeandunderstoodmyissues_29650_ResponseChoiceID = reader.IsDBNull(120) ? (int?)null : reader.GetInt32(120),
                    ChangedbehavioursScore1Noprogressinchangingbehavioursinareasrelevanttoclientsneedsandcircumsta_29651 = reader.IsDBNull(121) ? null : reader.GetString(121),
                    ChangedbehavioursScore1Noprogressinchangingbehavioursinareasrelevanttoclientsneedsandcircumsta_29651_ResponseChoiceID = reader.IsDBNull(122) ? (int?)null : reader.GetInt32(122),
                    ChangedimmediatecrisisScore1NoprogressinreducingthenegativeimpactoftheimmediatecrisisScore2Lim_29652 = reader.IsDBNull(123) ? null : reader.GetString(123),
                    ChangedimmediatecrisisScore1NoprogressinreducingthenegativeimpactoftheimmediatecrisisScore2Lim_29652_ResponseChoiceID = reader.IsDBNull(124) ? (int?)null : reader.GetInt32(124),
                    ChangedSkillsScore1NoprogressinincreasingskillsinareasrelevanttoclientsneedsandcircumstancesSc_29653 = reader.IsDBNull(125) ? null : reader.GetString(125),
                    ChangedSkillsScore1NoprogressinincreasingskillsinareasrelevanttoclientsneedsandcircumstancesSc_29653_ResponseChoiceID = reader.IsDBNull(126) ? (int?)null : reader.GetInt32(126),
                    AgeappropriatedevelopmentScore1Significantnegativeimpactofpoorageappropriatedevelopmentonindep_29654 = reader.IsDBNull(127) ? null : reader.GetString(127),
                    AgeappropriatedevelopmentScore1Significantnegativeimpactofpoorageappropriatedevelopmentonindep_29654_ResponseChoiceID = reader.IsDBNull(128) ? (int?)null : reader.GetInt32(128),
                    EducationandskillstrainingScore1Significantnegativeimpactoflackofengagementwitheducationandtra_29655 = reader.IsDBNull(129) ? null : reader.GetString(129),
                    EducationandskillstrainingScore1Significantnegativeimpactoflackofengagementwitheducationandtra_29655_ResponseChoiceID = reader.IsDBNull(130) ? (int?)null : reader.GetInt32(130),
                    EmploymentScore1Significantnegativeimpactoflackofemploymentonindependenceparticipationandwellb_29657 = reader.IsDBNull(131) ? null : reader.GetString(131),
                    EmploymentScore1Significantnegativeimpactoflackofemploymentonindependenceparticipationandwellb_29657_ResponseChoiceID = reader.IsDBNull(132) ? (int?)null : reader.GetInt32(132),
                    FamilyFunctioningScore1Significantnegativeimpactofpoorfamilyfunctioningonindependenceparticipa_29658 = reader.IsDBNull(133) ? null : reader.GetString(133),
                    FamilyFunctioningScore1Significantnegativeimpactofpoorfamilyfunctioningonindependenceparticipa_29658_ResponseChoiceID = reader.IsDBNull(134) ? (int?)null : reader.GetInt32(134),
                    FinancialresilienceScore1Significantnegativeimpactofpoorfinancialresilienceonindependenceparti_29659 = reader.IsDBNull(135) ? null : reader.GetString(135),
                    FinancialresilienceScore1Significantnegativeimpactofpoorfinancialresilienceonindependenceparti_29659_ResponseChoiceID = reader.IsDBNull(136) ? (int?)null : reader.GetInt32(136),
                    HousingScore1Significantnegativeimpactofpoorhousingonindependenceparticipationandwellbeingegro_29660 = reader.IsDBNull(137) ? null : reader.GetString(137),
                    HousingScore1Significantnegativeimpactofpoorhousingonindependenceparticipationandwellbeingegro_29660_ResponseChoiceID = reader.IsDBNull(138) ? (int?)null : reader.GetInt32(138),
                    MaterialwellbeingandbasicnecessitiesScore1Significantnegativeimpactoflackofbasicmaterialresour_29661 = reader.IsDBNull(139) ? null : reader.GetString(1398),
                    MaterialwellbeingandbasicnecessitiesScore1Significantnegativeimpactoflackofbasicmaterialresour_29661_ResponseChoiceID = reader.IsDBNull(140) ? (int?)null : reader.GetInt32(140),
                    PhysicalhealthScore1Significantnegativeimpactofpoorphysicalhealthonindependenceparticipationan_29662 = reader.IsDBNull(141) ? null : reader.GetString(141),
                    PhysicalhealthScore1Significantnegativeimpactofpoorphysicalhealthonindependenceparticipationan_29662_ResponseChoiceID = reader.IsDBNull(142) ? (int?)null : reader.GetInt32(142),
                    Scoring_31497 = reader.IsDBNull(143) ? null : reader.GetString(143),
                    FName = reader.IsDBNull(144) ? null : reader.GetString(144),
                    LName = reader.IsDBNull(145) ? null : reader.GetString(145),
                    SubjectName = reader.IsDBNull(146) ? null : reader.GetString(146),
                    ProgramName = reader.IsDBNull(147) ? null : reader.GetString(147),
                    EntityName = reader.IsDBNull(148) ? null : reader.GetString(148),                   

                });
            }

            return redressnotesrepo;
        }
    }
}