using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.Data.SqlClient;
using EtoApi.Models;

namespace EtoApi.DataAccess
{
    public class ServiceActivitiesRepository
    {
       private readonly ISqlConnectionFactory _connectionFactory;

        public ServiceActivitiesRepository(ISqlConnectionFactory connectionFactory)
            {
                _connectionFactory = connectionFactory;
            }

        public async Task<List<ServiceActivity>> GetServiceActivitiesByIdAsync(int id, int programCode)
        {
            var result = new List<ServiceActivity>();
            using var connection = await _connectionFactory.CreateOpenConnectionAsync();

            var query = @"
                SELECT 
                    FormResponseID,
                    FormIdentifier,
                    SubjectID,
                    GroupID,
                    FamilyID,
                    ResponseSetID,
                    FormID,
                    CollectionTypeID,
                    sub.SubjectTypeID,
                    CollectionID,
                    ResponseCreatedDate,
                    prg.ProgramName,
                    s.AuditStaffID,
                    s.AuditDate,
                    DataEnteredByID,
                    DraftSavedOn,
                    RemovedDate,
                    ShsGeneralAssistanceAndSupportActivities_16201,
                    ShsGeneralAssistanceAndSupportActivities_16201_ResponseChoiceID,
                    Notes_16203,
                    VisitSite_16219,
                    VisitSite_16219_ResponseChoiceID,
                    PresentingReason_16220,
                    InclusiveHealthReferralSource_16221,
                    PostcodeOfServiceDelivery_16230,
                    EpisodeOfCareOutcome_16231,
                    EpisodeOfCareOutcome_16231_ResponseChoiceID,
                    AccommodationStartDate_16236,
                    AccommodationProvider_16237,
                    AccommodationExitDate_16238,
                    NumberNights_16239,
                    WasTheParticipantFamilyPresentDuringThisActivityAnswerYesIfConversingWithParticipantFamilyOnPh_16241,
                    WasTheParticipantFamilyPresentDuringThisActivityAnswerYesIfConversingWithParticipantFamilyOnPh_16241_ResponseChoiceID,
                    ContactMethod_16242,
                    ContactMethod_16242_ResponseChoiceID,
                    ContactLocation_16243,
                    ContactLocation_16243_ResponseChoiceID,
                    IfContactLocationIsOtherPleaseIndicate_16244,
                    PhoneContactType_16245,
                    PhoneContactType_16245_ResponseChoiceID,
                    IfSupportTypeisOtherPleaseIndicate_16250,
                    HousingaccommodationShs_16262,
                    HousingaccommodationShs_16262_ResponseChoiceID,
                    WithWhichProviderDidYouLiaiseCoordinateOrAdvocate_16263,
                    NeedsIdentifiedHousingaccommodation_16267,
                    NeedsIdentifiedHousingaccommodation_16267_ResponseChoiceID,
                    NeedsIdentifiedGeneralAssistanceAndSupport_16268,
                    NeedsIdentifiedGeneralAssistanceAndSupport_16268_ResponseChoiceID,
                    NeedsIdentifiedSpecialisedServices_16269,
                    NeedsIdentifiedSpecialisedServices_16269_ResponseChoiceID,
                    e.EntityName,
                    Start_16282,
                    EndOptional_16283,
                    HowManyStaffDidThisTogetherAtMost4_16284,
                    SelectThe2ndStaffPerson_16285,
                    WasThisAPatPersonalVisit_16295,
                    WasThisAPatPersonalVisit_16295_ResponseChoiceID,
                    SelectYourName_16296,
                    ShsSpecialisedActivities_16338,
                    ShsSpecialisedActivities_16338_ResponseChoiceID,
                    WhatOtherTeamAssisted_16352,
                    KeepNullCondition_16354,
                    TimespentwithparticipantPerstaffmember_16356,
                    TimespentonbehalfofparticipantPerstaffmember_16357,
                    TimespenttravellingNotwithparticipantPerstaffmember_16358,
                    Totalefforttimeforparticipant_16362,
                    ParentFormResponseID_293,
                    SupportTypewhatdidyouprovideprimarily_16505,
                    ScopeofNeedGoal_16580,
                    ScopeofNeedGoal_16580_DisplayStr,
                    Domain_16582,
                    Domain_16582_DisplayStr,
                    LongTermGoal_16583,
                    LongTermGoal_16583_DisplayStr,
                    CrisisGoalNeed_16585,
                    CrisisGoalNeed_16585_DisplayStr,
                    OtherGoalNeed_16586,
                    OtherGoalNeed_16586_DisplayStr,
                    TimespentwithparticipantPerstaffmemberSA1_16588,
                    TimespentonbehalfofparticipantPerstaffmemberSA1_16589,
                    TimespenttravellingNotwithparticipantPerstaffmemberSA2_16590,
                    Ifyouprovidedasecondserviceoractivityselectithere_16591,
                    If2ndServiceorActivitytypeisOtherpleaseindicate_16592,
                    TimespentwithparticipantPerstaffmemberSA2_16593,
                    TimespentonbehalfofparticipantPerstaffmemberSA2_16594,
                    TimespenttravellingNotwithparticipantPerstaffmemberSA2_16595,
                    Ifyouprovidedathirdserviceoractivityselectithere_16596,
                    If3rdServiceorActivityisOtherpleasespecify_16600,
                    TimespentwithparticipantPerstaffmemberSA3_16601,
                    TimespentonbehalfofparticipantPerstaffmemberSA3_16602,
                    TimespenttravellingNotwithparticipantPerstaffmemberSA3_16603,
                    IfyouprovidedafourthServiceorActivityselectithere_16604,
                    If4thServiceorActivityisOtherpleasespecify_16605,
                    TimespentwithparticipantPerstaffmemberSA4_16606,
                    TimespentonbehalfofparticipantPerstaffmemberSA4_16607,
                    TimespenttravellingNotwithparticipantPerstaffmemberSA4_16608,
                    Totaltimespentwithparticipant_16609,
                    Totaltimespentonbehalfofparticipant_16610,
                    Totaltimespenttravelling_16611,
                    AIHWServiceActivitySA1_16698,
                    AIHWServiceActivitySA2_16699,
                    AIHWServiceActivitySA3_16700,
                    AIHWServiceActivitySA4_16701,
                    ShowHousingTabinSA1_16702,
                    ShowHousingTabinSA2_16703,
                    ShowHousingTabinSA3_16704,
                    ShowHousingTabinSA4_16705,
                    ShowInclusiveHealthtab1_16706,
                    ShowInclusiveHealthtab3_16707,
                    ShowInclusiveHealthtab2_16708,
                    ShowInclusiveHealthtab1_16709,
                    Isthisahousinggoalandhasthispersonfamilybeenhoused_16810,
                    Isthisahousinggoalandhasthispersonfamilybeenhoused_16810_ResponseChoiceID,
                    Progresstowardsthisgoalinthepasttwoweekshasbeen_16819,
                    Progresstowardsthisgoalinthepasttwoweekshasbeen_16819_ResponseChoiceID,
                    Participantlevelofmotivationforthisgoal_16821,
                    Participantlevelofmotivationforthisgoal_16821_ResponseChoiceID,
                    InclusiveHealthReferralSource_17548,
                    InclusiveHealthReferralSource_17548_ResponseChoiceID,
                    InclusiveHealthReferralMade_17549,
                    InclusiveHealthReferralMade_17549_ResponseChoiceID,
                    TeamInclusiveHealth_19817,
                    TeamInclusiveHealth2_19818,
                    WereyouinavehicleIfsoselect_20571,
                    WereyouinavehicleIfsoselect_20571_ResponseChoiceID,
                    WithwhichProviderdidyouliaisecoordinateoradvocateSA2_20970,
                    WithwhichProviderdidyouliaisecoordinateoradvocateSA3_20971,
                    WithwhichProviderdidyouliaisecoordinateoradvocateSA4_20972,
                    InclusiveHealthReferralMade_21843,
                    InclusiveHealthReferralMade_21843_ResponseChoiceID,
                    InclusiveHealthReferralMade_21844,
                    InclusiveHealthReferralMade_21844_ResponseChoiceID,
                    HealthVanRequired_22454,
                    HealthVanRequired_22455,
                    DateWDYNClosed_23231,
                    DateWDYNClosed_23231_DisplayStr,
                    IfanoutstandingDebtwasreducedbyhowmuch_23273,
                    Ifonetimeincomewasobtainedhowmuch_23274,
                    IFrecurringincomewasobtainedwhatismonthlyamount_23275,
                    WereyouinavehicleIfsoselect_23525,
                    WereyouinavehicleIfsoselect_23525_ResponseChoiceID,
                    InclusiveHealthReferralMade_23549,
                    InclusiveHealthReferralMade_23549_ResponseChoiceID,
                    PostCode_23550,
                    PostcodeofServiceDelivery_23551,
                    VisitSiteHealth_23976,
                    InclusiveHealthReferralSource_23992,
                    InclusiveHealthReferralMade_23993,
                    InclusiveHealthReferralMade_24031,
                    InclusiveHealthReferralMade_24032,
                    IgnoreThis_24086,
                    IgnoreThis_24086_ResponseChoiceID,
                    HealthReferralMade_24481,
                    Temprature_26012,
                    BloodPressuremmHg_26013,
                    HeartRatebeastperminute_26014,
                    HeartRateregularity_26015,
                    HeartRateregularity_26015_ResponseChoiceID,
                    Respirationsperminute_26016,
                    Oxygensaturation_26017,
                    BloodSugarmmollitre_26018,
                    PeakFlow_26019,
                    Weightkilograms_26020,
                    Heightcentimeters_26021,
                    BMI_26022,
                    Urinalysis_26023,
                    Areyourecordingclinicalobservations_26024,
                    Areyourecordingclinicalobservations_26024_ResponseChoiceID,
                    Iamhere_28395,
                    Iamhere_28396,
                    Didyouadministermedication_28401,
                    Didyouadministermedication_28401_ResponseChoiceID,
                    Didyoucallemergencyservicesaspartofthisengagement_28405,
                    Didyoucallemergencyservicesaspartofthisengagement_28405_ResponseChoiceID,
                    Ifyeswhichoneshavebeencalled_28406,
                    Ifyeswhichoneshavebeencalled_28406_ResponseChoiceID,
                    Whichgoalwasthisfor_29378,
                    Whichgoalwasthisfor_29378_SourceFormID,
                    Whichgoalwasthisfor_29378_DisplayStr,
                    Whichgoalwasthisfor_29381,
                    Whichgoalwasthisfor_29381_SourceFormID,
                    Whichgoalwasthisfor_29381_DisplayStr,
                    2ndactivitiyWhichgoalwasthisfor_29496,
                    2ndactivitiyWhichgoalwasthisfor_29496_SourceFormID,
                    2ndactivitiyWhichgoalwasthisfor_29496_DisplayStr,
                    3AWhichgoalwasthisfor_29497,
                    3AWhichgoalwasthisfor_29497_SourceFormID,
                    3AWhichgoalwasthisfor_29497_DisplayStr,
                    4AWhichgoalwasthisfor_29498,
                    4AWhichgoalwasthisfor_29498_SourceFormID,
                    4AWhichgoalwasthisfor_29498_DisplayStr,
                    UserName_29499,
                    Whatkindofentryisthis_29502,
                    Whatkindofentryisthis_29502_ResponseChoiceID,
                    Isthisahighlevelcheckin_31616,
                    Isthisahighlevelcheckin_31616_ResponseChoiceID,
                    IsthistheFIRSThighlevelcheckin_31618,
                    IsthistheFIRSThighlevelcheckin_31618_ResponseChoiceID,
                    Aresupportservicesinplaceandstillmeetingtheirneeds_31619,
                    Aresupportservicesinplaceandstillmeetingtheirneeds_31619_ResponseChoiceID,
                    Dotheyneedsupportfromcarefinder_31623,
                    Dotheyneedsupportfromcarefinder_31623_ResponseChoiceID,
                    Reasonsfornotstayingconnectedtoservices_31628,
                    Reasonsfornotstayingconnectedtoservices_31628_ResponseChoiceID,
                    Isthereachronichealthcondition_32752,
                    Isthereachronichealthcondition_32752_ResponseChoiceID,
                    Howwouldyouratethenursingcareprovidedtoyou_32939,
                    Howwouldyouratethenursingcareprovidedtoyou_32939_ResponseChoiceID,
                    ClaimType_33234,
                    ClaimType_33234_ResponseChoiceID,
                    GSTCode_33235,
                    GSTCode_33235_ResponseChoiceID,
                    Isthisascheduledsupport_33236,
                    Isthisascheduledsupport_33236_ResponseChoiceID,
                    ReasonforCancellationatShortNotice_33237,
                    ReasonforCancellationatShortNotice_33237_ResponseChoiceID,
                    TransactionDate_33294,
                    TransactionAmount_33296,
                    PaymentforAIHW_33297,
                    PaymentforAIHW_33297_ResponseChoiceID,
                    DateSafetyUpgradeCompleted_33299,
                    IfanymonitoringoreffortiswasrequiredtocompleteSafetyUpgradepleasedescribe_33300,
                    ServiceUserDFVOonlyOusterCondition_33301,
                    ServiceUserDFVOonlyOusterCondition_33301_ResponseChoiceID,
                    IstheServiceUsercurrentlylivinginthehome_33302,
                    IstheServiceUsercurrentlylivinginthehome_33302_ResponseChoiceID,
                    NumberofChildrenlivingwiththeServiceUserinhome_33303,
                    TransportofParticipanttofromApptorActivitySA1_33304,
                    TransportofParticipanttofromApptorActivitySA2_33305,
                    TimespenttravellingTransportofParticipanttofromApptorActivitySA3_33306,
                    TimespenttravellingTransportofParticipanttofromApptorActivitySA4_33307,
                    TimespenttravellingTransportofParticipanttofromApptorActivity_33308,
                    TotaltimespenttravellingTransportofParticipanttofromApptorActivity_33309,
                    Financeprojectcode_33310,
                    Brieftransactiondescription_33311,
                    Supplierprovider_33312,
                    Ifotherprovidesupplierbusinessname_33313,
                    Howwaspaymentmade_33314,
                    Howwaspaymentmade_33314_ResponseChoiceID,
                    Authorisedby_33315,
                    Isanyportionofthistransactionrecoverable_33316,
                    Isanyportionofthistransactionrecoverable_33316_ResponseChoiceID,
                    Recoveryinvoicename_33317,
                    Amountrecoverablefromthissource_33318,
                    Recoveryinvoicecontactname_33319,
                    Recoveryinvoicecontactemail_33320,
                    Haspaymentalreadybeenmadeordoesfinancestillneedtopay_33321,
                    Haspaymentalreadybeenmadeordoesfinancestillneedtopay_33321_ResponseChoiceID,
                    IsthistransactionrelatedtoHousingandSafetyUpgrades_33322,
                    IsthistransactionrelatedtoHousingandSafetyUpgrades_33322_ResponseChoiceID,
                    Wasbrokeragedoneforthisactivity_33325,
                    Wasbrokeragedoneforthisactivity_33325_ResponseChoiceID,
                    Purpose_33327,
                    Purpose_33327_ResponseChoiceID,
                    WasNaloxone_33329,
                    WasNaloxone_33329_ResponseChoiceID,
                    UploadDocument_33331,
                    TESTDONOTCOMPLETEWhichtypeofdwellingdoesthisindividualcurrentlyresideinFOROUTREACHNURSEONLY_33332,
                    TESTDONOTCOMPLETEWhichtypeofdwellingdoesthisindividualcurrentlyresideinFOROUTREACHNURSEONLY_33332_ResponseChoiceID,
                    TESTDONOTCOMPLETEIstheparticipantcurrentlyresidinginastableresidentialdwellingForoutreachnursi_33333,
                    TESTDONOTCOMPLETEIstheparticipantcurrentlyresidinginastableresidentialdwellingForoutreachnursi_33333_ResponseChoiceID,
                    Whichstaffmembersbusinesscardwasused_33337,
                    Whichstaffmemberistobereimbursed_33338,
                    s.FName,
                    s.LName
                    FROM form.f_299 frm
                    JOIN Staff s ON frm.AuditStaffID = s.StaffID
                    JOIN Entities e ON e.EntityID = frm.MicahTeam_16280
                    JOIN SubjectType sub ON sub.SubjectTypeID = frm.SubjectTypeID
                    JOIN Programs prg ON prg.ProgramID = frm.ProgramID
                    Join ClientsXPrograms cp ON cp.CLID = @Id and cp.ProgramID = @programCode
                    WHERE frm.SubjectID = (SELECT SubjectID FROM SubjectXClient WHERE CLID = @Id) and frm.ProgramID = @programCode ORDER BY frm.AuditDate DESC";
    
    using var command = new SqlCommand(query, connection);
            command.Parameters.AddWithValue("@Id", id);
            command.Parameters.AddWithValue("@programCode", programCode);

          var serviceActivities = new List<ServiceActivity>();
            using var reader = await command.ExecuteReaderAsync();

            while (await reader.ReadAsync())
            {
                try {
                serviceActivities.Add(new ServiceActivity
                {
                    FormResponseID = reader.IsDBNull(0) ? (int?)null : reader.GetInt32(0),
                    FormIdentifier = reader.IsDBNull(1) ? null : reader.GetString(1),
                    SubjectID = reader.IsDBNull(2) ? (int?)null : reader.GetInt32(2),
                    GroupID = reader.IsDBNull(3) ? (int?)null : reader.GetInt32(3),
                    FamilyID = reader.IsDBNull(4) ? (int?)null : reader.GetInt32(4),
                    ResponseSetID = reader.IsDBNull(5) ? (int?)null : reader.GetInt32(5),
                    FormID = reader.IsDBNull(6) ? (int?)null : reader.GetInt32(6),
                    CollectionTypeID = reader.IsDBNull(7) ? (int?)null : reader.GetInt32(7),
                    SubjectTypeID = reader.IsDBNull(8) ? (int?)null : reader.GetInt32(8),
                    CollectionID = reader.IsDBNull(9) ? (int?)null : reader.GetInt32(9),
                    ResponseCreatedDate = reader.IsDBNull(10) ? (DateTime?)null : reader.GetDateTime(10),
                    ProgramName = reader.IsDBNull(11) ? null : reader.GetString(11),
                    AuditStaffID = reader.IsDBNull(12) ? (int?)null : reader.GetInt32(12),
                    AuditDate = reader.IsDBNull(13) ? (DateTime?)null : reader.GetDateTime(13),
                    DataEnteredByID = reader.IsDBNull(14) ? (int?)null : reader.GetInt32(14),
                    DraftSavedOn = reader.IsDBNull(15) ? (DateTime?)null : reader.GetDateTime(15),
                    RemovedDate = reader.IsDBNull(16) ? (DateTime?)null : reader.GetDateTime(16),
                    ShsGeneralAssistanceAndSupportActivities_16201 = reader.IsDBNull(17) ? null : reader.GetString(17),
                    ShsGeneralAssistanceAndSupportActivities_16201_ResponseChoiceID = reader.IsDBNull(18) ? (int?)null : reader.GetInt32(18),
                    Notes_16203 = reader.IsDBNull(19) ? null : reader.GetString(19),
                    VisitSite_16219 = reader.IsDBNull(20) ? null : reader.GetString(20),
                    VisitSite_16219_ResponseChoiceID = reader.IsDBNull(21) ? (int?)null : reader.GetInt32(21),
                    PresentingReason_16220 = reader.IsDBNull(22) ? null : reader.GetString(22),
                    InclusiveHealthReferralSource_16221 = reader.IsDBNull(23) ? (int?)null : reader.GetInt32(23),
                    PostcodeOfServiceDelivery_16230 = reader.IsDBNull(24) ? (decimal?)null : reader.GetDecimal(24),
                    EpisodeOfCareOutcome_16231 = reader.IsDBNull(25) ? null : reader.GetString(25),
                    EpisodeOfCareOutcome_16231_ResponseChoiceID = reader.IsDBNull(26) ? (int?)null : reader.GetInt32(26),
                    AccommodationStartDate_16236 = reader.IsDBNull(27) ? (DateTime?)null : reader.GetDateTime(27),
                    AccommodationProvider_16237 = reader.IsDBNull(28) ? (int?)null : reader.GetInt32(28),
                    AccommodationExitDate_16238 = reader.IsDBNull(29) ? (DateTime?)null : reader.GetDateTime(29),
                    NumberNights_16239 = reader.IsDBNull(30) ? (decimal?)null : reader.GetDecimal(30),
                    WasTheParticipantFamilyPresentDuringThisActivityAnswerYesIfConversingWithParticipantFamilyOnPh_16241 = reader.IsDBNull(31) ? null : reader.GetString(31),
                    WasTheParticipantFamilyPresentDuringThisActivityAnswerYesIfConversingWithParticipantFamilyOnPh_16241_ResponseChoiceID = reader.IsDBNull(32) ? (int?)null : reader.GetInt32(32),
                    ContactMethod_16242 = reader.IsDBNull(33) ? null : reader.GetString(33),
                    ContactMethod_16242_ResponseChoiceID = reader.IsDBNull(34) ? (int?)null : reader.GetInt32(34),
                    ContactLocation_16243 = reader.IsDBNull(35) ? null : reader.GetString(35),
                    ContactLocation_16243_ResponseChoiceID = reader.IsDBNull(36) ? (int?)null : reader.GetInt32(36),
                    IfContactLocationIsOtherPleaseIndicate_16244 = reader.IsDBNull(37) ? null : reader.GetString(37),
                    PhoneContactType_16245 = reader.IsDBNull(38) ? null : reader.GetString(38),
                    PhoneContactType_16245_ResponseChoiceID = reader.IsDBNull(39) ? (int?)null : reader.GetInt32(39),
                    IfSupportTypeisOtherPleaseIndicate_16250 = reader.IsDBNull(40) ? null : reader.GetString(40),
                    HousingaccommodationShs_16262 = reader.IsDBNull(41) ? null : reader.GetString(41),
                    HousingaccommodationShs_16262_ResponseChoiceID = reader.IsDBNull(42) ? (int?)null : reader.GetInt32(42),
                    WithWhichProviderDidYouLiaiseCoordinateOrAdvocate_16263 = reader.IsDBNull(43) ? (int?)null : reader.GetInt32(43),
                    NeedsIdentifiedHousingaccommodation_16267 = reader.IsDBNull(44) ? null : reader.GetString(44),
                    NeedsIdentifiedHousingaccommodation_16267_ResponseChoiceID = reader.IsDBNull(45) ? (int?)null : reader.GetInt32(45),
                    NeedsIdentifiedGeneralAssistanceAndSupport_16268 = reader.IsDBNull(46) ? null : reader.GetString(46),
                    NeedsIdentifiedGeneralAssistanceAndSupport_16268_ResponseChoiceID = reader.IsDBNull(47) ? (int?)null : reader.GetInt32(47),
                    NeedsIdentifiedSpecialisedServices_16269 = reader.IsDBNull(48) ? null : reader.GetString(48),
                    NeedsIdentifiedSpecialisedServices_16269_ResponseChoiceID = reader.IsDBNull(49) ? (int?)null : reader.GetInt32(49),
                    EntityName = reader.IsDBNull(50) ? null : reader.GetString(50),
                    Start_16282 = reader.IsDBNull(51) ? null : reader.GetString(51),
                    EndOptional_16283 = reader.IsDBNull(52) ? null : reader.GetString(52),
                    HowManyStaffDidThisTogetherAtMost4_16284 = reader.IsDBNull(53) ? (decimal?)null : reader.GetDecimal(53),
                    SelectThe2ndStaffPerson_16285 = reader.IsDBNull(54) ? (int?)null : reader.GetInt32(54),
                    WasThisAPatPersonalVisit_16295 = reader.IsDBNull(55) ? null : reader.GetString(55),
                    WasThisAPatPersonalVisit_16295_ResponseChoiceID = reader.IsDBNull(56) ? (int?)null : reader.GetInt32(56),
                    SelectYourName_16296 = reader.IsDBNull(57) ? (int?)null : reader.GetInt32(57),
                    ShsSpecialisedActivities_16338 = reader.IsDBNull(58) ? null : reader.GetString(58),
                    ShsSpecialisedActivities_16338_ResponseChoiceID = reader.IsDBNull(59) ? (int?)null : reader.GetInt32(59),
                    WhatOtherTeamAssisted_16352 = reader.IsDBNull(60) ? (int?)null : reader.GetInt32(60),
                    KeepNullCondition_16354 = reader.IsDBNull(61) ? (decimal?)null : reader.GetDecimal(61),
                    TimespentwithparticipantPerstaffmember_16356 = reader.IsDBNull(62) ? (int?)null : reader.GetInt32(62),
                    TimespentonbehalfofparticipantPerstaffmember_16357 = reader.IsDBNull(63) ? (int?)null : reader.GetInt32(63),
                    TimespenttravellingNotwithparticipantPerstaffmember_16358 = reader.IsDBNull(64) ? (int?)null : reader.GetInt32(64),
                    Totalefforttimeforparticipant_16362 = reader.IsDBNull(65) ? (int?)null : reader.GetInt32(65),
                    ParentFormResponseID_293 = reader.IsDBNull(66) ? (int?)null : reader.GetInt32(66),
                    SupportTypewhatdidyouprovideprimarily_16505 = reader.IsDBNull(67) ? (int?)null : reader.GetInt32(67),
                    ScopeofNeedGoal_16580 = reader.IsDBNull(68) ? (int?)null : reader.GetInt32(68),
                    ScopeofNeedGoal_16580_DisplayStr = reader.IsDBNull(69) ? null : reader.GetString(69),
                    Domain_16582 = reader.IsDBNull(70) ? (int?)null : reader.GetInt32(70),
                    Domain_16582_DisplayStr = reader.IsDBNull(71) ? null : reader.GetString(71),
                    LongTermGoal_16583 = reader.IsDBNull(72) ? (int?)null : reader.GetInt32(72),
                    LongTermGoal_16583_DisplayStr = reader.IsDBNull(73) ? null : reader.GetString(73),
                    CrisisGoalNeed_16585 = reader.IsDBNull(74) ? (int?)null : reader.GetInt32(74),
                    CrisisGoalNeed_16585_DisplayStr = reader.IsDBNull(75) ? null : reader.GetString(75),
                    OtherGoalNeed_16586 = reader.IsDBNull(76) ? (int?)null : reader.GetInt32(76),
                    OtherGoalNeed_16586_DisplayStr = reader.IsDBNull(77) ? null : reader.GetString(77),
                    TimespentwithparticipantPerstaffmemberSA1_16588 = reader.IsDBNull(78) ? (int?)null : reader.GetInt32(78),
                    TimespentonbehalfofparticipantPerstaffmemberSA1_16589 = reader.IsDBNull(79) ? (int?)null : reader.GetInt32(79),
                    TimespenttravellingNotwithparticipantPerstaffmemberSA2_16590 = reader.IsDBNull(80) ? (int?)null : reader.GetInt32(80),
                    Ifyouprovidedasecondserviceoractivityselectithere_16591 = reader.IsDBNull(81) ? (int?)null : reader.GetInt32(81),
                    If2ndServiceorActivitytypeisOtherpleaseindicate_16592 = reader.IsDBNull(82) ? null : reader.GetString(82),
                    TimespentwithparticipantPerstaffmemberSA2_16593 = reader.IsDBNull(83) ? (int?)null : reader.GetInt32(83),
                    TimespentonbehalfofparticipantPerstaffmemberSA2_16594 = reader.IsDBNull(84) ? (int?)null : reader.GetInt32(84),
                    TimespenttravellingNotwithparticipantPerstaffmemberSA2_16595 = reader.IsDBNull(85) ? (int?)null : reader.GetInt32(85),
                    Ifyouprovidedathirdserviceoractivityselectithere_16596 = reader.IsDBNull(86) ? (int?)null : reader.GetInt32(86),
                    If3rdServiceorActivityisOtherpleasespecify_16600 = reader.IsDBNull(87) ? null : reader.GetString(87),
                    TimespentwithparticipantPerstaffmemberSA3_16601 = reader.IsDBNull(88) ? (int?)null : reader.GetInt32(88),
                    TimespentonbehalfofparticipantPerstaffmemberSA3_16602 = reader.IsDBNull(89) ? (int?)null : reader.GetInt32(89),
                    TimespenttravellingNotwithparticipantPerstaffmemberSA3_16603 = reader.IsDBNull(90) ? (int?)null : reader.GetInt32(90),
                    IfyouprovidedafourthServiceorActivityselectithere_16604 = reader.IsDBNull(91) ? (int?)null : reader.GetInt32(91),
                    If4thServiceorActivityisOtherpleasespecify_16605 = reader.IsDBNull(92) ? null : reader.GetString(92),
                    TimespentwithparticipantPerstaffmemberSA4_16606 = reader.IsDBNull(93) ? (int?)null : reader.GetInt32(93),
                    TimespentonbehalfofparticipantPerstaffmemberSA4_16607 = reader.IsDBNull(94) ? (int?)null : reader.GetInt32(94),
                    TimespenttravellingNotwithparticipantPerstaffmemberSA4_16608 = reader.IsDBNull(95) ? (int?)null : reader.GetInt32(95),
                    Totaltimespentwithparticipant_16609 = reader.IsDBNull(96) ? (int?)null : reader.GetInt32(96),
                    Totaltimespentonbehalfofparticipant_16610 = reader.IsDBNull(97) ? (int?)null : reader.GetInt32(97),
                    Totaltimespenttravelling_16611 = reader.IsDBNull(98) ? (int?)null : reader.GetInt32(98),
                    AIHWServiceActivitySA1_16698 = reader.IsDBNull(99) ? null : reader.GetString(99),
                    AIHWServiceActivitySA2_16699 = reader.IsDBNull(100) ? null : reader.GetString(100),
                    AIHWServiceActivitySA3_16700 = reader.IsDBNull(101) ? null : reader.GetString(101),
                    AIHWServiceActivitySA4_16701 = reader.IsDBNull(102) ? null : reader.GetString(102),
                    ShowHousingTabinSA1_16702 = reader.IsDBNull(103) ? null : reader.GetString(103),
                    ShowHousingTabinSA2_16703 = reader.IsDBNull(104) ? null : reader.GetString(104),
                    ShowHousingTabinSA3_16704 = reader.IsDBNull(105) ? null : reader.GetString(105),
                    ShowHousingTabinSA4_16705 = reader.IsDBNull(106) ? null : reader.GetString(106),
                    ShowInclusiveHealthtab1_16706 = reader.IsDBNull(107) ? null : reader.GetString(107),
                    ShowInclusiveHealthtab3_16707 = reader.IsDBNull(108) ? null : reader.GetString(108),
                    ShowInclusiveHealthtab2_16708 = reader.IsDBNull(109) ? null : reader.GetString(109),
                    ShowInclusiveHealthtab1_16709 = reader.IsDBNull(110) ? null : reader.GetString(110),
                    Isthisahousinggoalandhasthispersonfamilybeenhoused_16810 = reader.IsDBNull(111) ? null : reader.GetString(111),
                    Isthisahousinggoalandhasthispersonfamilybeenhoused_16810_ResponseChoiceID = reader.IsDBNull(112) ? (int?)null : reader.GetInt32(112),
                    Progresstowardsthisgoalinthepasttwoweekshasbeen_16819 = reader.IsDBNull(113) ? null : reader.GetString(113),
                    Progresstowardsthisgoalinthepasttwoweekshasbeen_16819_ResponseChoiceID = reader.IsDBNull(114) ? (int?)null : reader.GetInt32(114),
                    Participantlevelofmotivationforthisgoal_16821 = reader.IsDBNull(115) ? null : reader.GetString(115),
                    Participantlevelofmotivationforthisgoal_16821_ResponseChoiceID = reader.IsDBNull(116) ? (int?)null : reader.GetInt32(116),
                    InclusiveHealthReferralSource_17548 = reader.IsDBNull(117) ? null : reader.GetString(117),
                    InclusiveHealthReferralSource_17548_ResponseChoiceID = reader.IsDBNull(118) ? (int?)null : reader.GetInt32(118),
                    InclusiveHealthReferralMade_17549 = reader.IsDBNull(119) ? null : reader.GetString(119),
                    InclusiveHealthReferralMade_17549_ResponseChoiceID = reader.IsDBNull(120) ? (int?)null : reader.GetInt32(120),
                    TeamInclusiveHealth_19817 = reader.IsDBNull(121) ? null : reader.GetString(121),
                    TeamInclusiveHealth2_19818 = reader.IsDBNull(122) ? null : reader.GetString(122),
                    WereyouinavehicleIfsoselect_20571 = reader.IsDBNull(123) ? null : reader.GetString(123),
                    WereyouinavehicleIfsoselect_20571_ResponseChoiceID = reader.IsDBNull(124) ? (int?)null : reader.GetInt32(124),
                    WithwhichProviderdidyouliaisecoordinateoradvocateSA2_20970 = reader.IsDBNull(125) ? (int?)null : reader.GetInt32(125),
                    WithwhichProviderdidyouliaisecoordinateoradvocateSA3_20971 = reader.IsDBNull(126) ? (int?)null : reader.GetInt32(126),
                    WithwhichProviderdidyouliaisecoordinateoradvocateSA4_20972 = reader.IsDBNull(127) ? (int?)null : reader.GetInt32(127),
                    InclusiveHealthReferralMade_21843 = reader.IsDBNull(128) ? null : reader.GetString(128),
                    InclusiveHealthReferralMade_21843_ResponseChoiceID = reader.IsDBNull(129) ? (int?)null : reader.GetInt32(129),
                    InclusiveHealthReferralMade_21844 = reader.IsDBNull(130) ? null : reader.GetString(130),
                    InclusiveHealthReferralMade_21844_ResponseChoiceID = reader.IsDBNull(131) ? (int?)null : reader.GetInt32(131),
                    HealthVanRequired_22454 = reader.IsDBNull(132) ? null : reader.GetString(132),
                    HealthVanRequired_22455 = reader.IsDBNull(133) ? null : reader.GetString(133),
                    DateWDYNClosed_23231 = reader.IsDBNull(134) ? (int?)null : reader.GetInt32(134),
                    DateWDYNClosed_23231_DisplayStr = reader.IsDBNull(135) ? null : reader.GetString(135),
                    IfanoutstandingDebtwasreducedbyhowmuch_23273 = reader.IsDBNull(136) ? (decimal?)null : reader.GetDecimal(136),
                    Ifonetimeincomewasobtainedhowmuch_23274 = reader.IsDBNull(137) ? (decimal?)null : reader.GetDecimal(137),
                    IFrecurringincomewasobtainedwhatismonthlyamount_23275 = reader.IsDBNull(138) ? (decimal?)null : reader.GetDecimal(138),
                    WereyouinavehicleIfsoselect_23525 = reader.IsDBNull(139) ? null : reader.GetString(139),
                    WereyouinavehicleIfsoselect_23525_ResponseChoiceID = reader.IsDBNull(140) ? (int?)null : reader.GetInt32(140),
                    InclusiveHealthReferralMade_23549 = reader.IsDBNull(141) ? null : reader.GetString(141),
                    InclusiveHealthReferralMade_23549_ResponseChoiceID = reader.IsDBNull(142) ? (int?)null : reader.GetInt32(142),
                    PostCode_23550 = reader.IsDBNull(143) ? (int?)null : reader.GetInt32(143),
                    PostcodeofServiceDelivery_23551 = reader.IsDBNull(144) ? (int?)null : reader.GetInt32(144),
                    VisitSiteHealth_23976 = reader.IsDBNull(145) ? (int?)null : reader.GetInt32(145),
                    InclusiveHealthReferralSource_23992 = reader.IsDBNull(146) ? (int?)null : reader.GetInt32(146),
                    InclusiveHealthReferralMade_23993 = reader.IsDBNull(147) ? (int?)null : reader.GetInt32(147),
                    InclusiveHealthReferralMade_24031 = reader.IsDBNull(148) ? (int?)null : reader.GetInt32(148),
                    InclusiveHealthReferralMade_24032 = reader.IsDBNull(149) ? (int?)null : reader.GetInt32(149),
                    IgnoreThis_24086 = reader.IsDBNull(150) ? null : reader.GetString(150),
                    IgnoreThis_24086_ResponseChoiceID = reader.IsDBNull(151) ? (int?)null : reader.GetInt32(151),
                    HealthReferralMade_24481 = reader.IsDBNull(152) ? (int?)null : reader.GetInt32(152),
                    Temprature_26012 = reader.IsDBNull(153) ? (decimal?)null : reader.GetDecimal(153),
                    BloodPressuremmHg_26013 = reader.IsDBNull(154) ? null : reader.GetString(154),
                    HeartRatebeastperminute_26014 = reader.IsDBNull(155) ? (decimal?)null : reader.GetDecimal(155),
                    HeartRateregularity_26015 = reader.IsDBNull(156) ? null : reader.GetString(156),
                    HeartRateregularity_26015_ResponseChoiceID = reader.IsDBNull(157) ? (int?)null : reader.GetInt32(157),
                    Respirationsperminute_26016 = reader.IsDBNull(158) ? (decimal?)null : reader.GetDecimal(158),
                    Oxygensaturation_26017 = reader.IsDBNull(159) ? (decimal?)null : reader.GetDecimal(159),
                    BloodSugarmmollitre_26018 = reader.IsDBNull(160) ? (decimal?)null : reader.GetDecimal(160),
                    PeakFlow_26019 = reader.IsDBNull(161) ? (decimal?)null : reader.GetDecimal(161),
                    Weightkilograms_26020 = reader.IsDBNull(162) ? (decimal?)null : reader.GetDecimal(162),
                    Heightcentimeters_26021 = reader.IsDBNull(163) ? (decimal?)null : reader.GetDecimal(163),
                    BMI_26022 = reader.IsDBNull(164) ? (decimal?)null : reader.GetDecimal(164),
                    Urinalysis_26023 = reader.IsDBNull(165) ? null : reader.GetString(165),
                    Areyourecordingclinicalobservations_26024 = reader.IsDBNull(166) ? null : reader.GetString(166),
                    Areyourecordingclinicalobservations_26024_ResponseChoiceID = reader.IsDBNull(167) ? (int?)null : reader.GetInt32(167),
                    Iamhere_28395 = reader.IsDBNull(168) ? null : reader.GetString(168),
                    Iamhere_28396 = reader.IsDBNull(169) ? null : reader.GetString(169),
                    Didyouadministermedication_28401 = reader.IsDBNull(170) ? null : reader.GetString(170),
                    Didyouadministermedication_28401_ResponseChoiceID = reader.IsDBNull(171) ? (int?)null : reader.GetInt32(171),
                    Didyoucallemergencyservicesaspartofthisengagement_28405 = reader.IsDBNull(172) ? null : reader.GetString(172),
                    Didyoucallemergencyservicesaspartofthisengagement_28405_ResponseChoiceID = reader.IsDBNull(173) ? (int?)null : reader.GetInt32(173),
                    Ifyeswhichoneshavebeencalled_28406 = reader.IsDBNull(174) ? null : reader.GetString(174),
                    Ifyeswhichoneshavebeencalled_28406_ResponseChoiceID = reader.IsDBNull(175) ? (int?)null : reader.GetInt32(175),
                    Whichgoalwasthisfor_29378 = reader.IsDBNull(176) ? (int?)null : reader.GetInt32(176),
                    Whichgoalwasthisfor_29378_SourceFormID = reader.IsDBNull(177) ? (int?)null : reader.GetInt32(177),
                    Whichgoalwasthisfor_29378_DisplayStr = reader.IsDBNull(178) ? null : reader.GetString(178),
                    Whichgoalwasthisfor_29381 = reader.IsDBNull(179) ? (int?)null : reader.GetInt32(179),
                    Whichgoalwasthisfor_29381_SourceFormID = reader.IsDBNull(180) ? (int?)null : reader.GetInt32(180),
                    Whichgoalwasthisfor_29381_DisplayStr = reader.IsDBNull(181) ? null : reader.GetString(181),
                    _2ndactivitiyWhichgoalwasthisfor_29496 = reader.IsDBNull(182) ? (int?)null : reader.GetInt32(182),
                    _2ndactivitiyWhichgoalwasthisfor_29496_SourceFormID = reader.IsDBNull(183) ? (int?)null : reader.GetInt32(183),
                  //  _2ndactivitiyWhichgoalwasthisfor_29496_DisplayStr = reader.IsDBNull(184) ? null : reader.GetString(184),
                    _3AWhichgoalwasthisfor_29497 = reader.IsDBNull(185) ? (int?)null : reader.GetInt32(185),
                    _3AWhichgoalwasthisfor_29497_SourceFormID = reader.IsDBNull(186) ? (int?)null : reader.GetInt32(186),
                  //  _3AWhichgoalwasthisfor_29497_DisplayStr = reader.IsDBNull(187) ? null : reader.GetString(187),
                    _4AWhichgoalwasthisfor_29498 = reader.IsDBNull(188) ? (int?)null : reader.GetInt32(188),
                    _4AWhichgoalwasthisfor_29498_SourceFormID = reader.IsDBNull(189) ? (int?)null : reader.GetInt32(189),
                  //  _4AWhichgoalwasthisfor_29498_DisplayStr = reader.IsDBNull(190) ? null : reader.GetString(190),
                    UserName_29499 = reader.IsDBNull(191) ? null : reader.GetString(191),
                    Whatkindofentryisthis_29502 = reader.IsDBNull(192) ? null : reader.GetString(192),
                    Whatkindofentryisthis_29502_ResponseChoiceID = reader.IsDBNull(193) ? (int?)null : reader.GetInt32(193),
                    Isthisahighlevelcheckin_31616 = reader.IsDBNull(194) ? null : reader.GetString(194),
                    Isthisahighlevelcheckin_31616_ResponseChoiceID = reader.IsDBNull(195) ? (int?)null : reader.GetInt32(195),
                    IsthistheFIRSThighlevelcheckin_31618 = reader.IsDBNull(196) ? null : reader.GetString(196),
                    IsthistheFIRSThighlevelcheckin_31618_ResponseChoiceID = reader.IsDBNull(197) ? (int?)null : reader.GetInt32(197),
                    Aresupportservicesinplaceandstillmeetingtheirneeds_31619 = reader.IsDBNull(198) ? null : reader.GetString(198),
                    Aresupportservicesinplaceandstillmeetingtheirneeds_31619_ResponseChoiceID = reader.IsDBNull(199) ? (int?)null : reader.GetInt32(199),
                    Dotheyneedsupportfromcarefinder_31623 = reader.IsDBNull(200) ? null : reader.GetString(200),
                    Dotheyneedsupportfromcarefinder_31623_ResponseChoiceID = reader.IsDBNull(201) ? (int?)null : reader.GetInt32(201),
                    Reasonsfornotstayingconnectedtoservices_31628 = reader.IsDBNull(202) ? null : reader.GetString(202),
                    Reasonsfornotstayingconnectedtoservices_31628_ResponseChoiceID = reader.IsDBNull(203) ? (int?)null : reader.GetInt32(203),
                    Isthereachronichealthcondition_32752 = reader.IsDBNull(204) ? null : reader.GetString(204),
                    Isthereachronichealthcondition_32752_ResponseChoiceID = reader.IsDBNull(205) ? (int?)null : reader.GetInt32(205),
                    Howwouldyouratethenursingcareprovidedtoyou_32939 = reader.IsDBNull(206) ? null : reader.GetString(206),
                    Howwouldyouratethenursingcareprovidedtoyou_32939_ResponseChoiceID = reader.IsDBNull(207) ? (int?)null : reader.GetInt32(207),
                    ClaimType_33234 = reader.IsDBNull(208) ? null : reader.GetString(208),
                    ClaimType_33234_ResponseChoiceID = reader.IsDBNull(209) ? (int?)null : reader.GetInt32(209),
                    GSTCode_33235 = reader.IsDBNull(210) ? null : reader.GetString(210),
                    GSTCode_33235_ResponseChoiceID = reader.IsDBNull(211) ? (int?)null : reader.GetInt32(211),
                    Isthisascheduledsupport_33236 = reader.IsDBNull(212) ? null : reader.GetString(212),
                    Isthisascheduledsupport_33236_ResponseChoiceID = reader.IsDBNull(213) ? (int?)null : reader.GetInt32(213),
                    ReasonforCancellationatShortNotice_33237 = reader.IsDBNull(214) ? null : reader.GetString(214),
                    ReasonforCancellationatShortNotice_33237_ResponseChoiceID = reader.IsDBNull(215) ? (int?)null : reader.GetInt32(215),
                    TransactionDate_33294 = reader.IsDBNull(216) ? (DateTime?)null : reader.GetDateTime(216),
                    TransactionAmount_33296 = reader.IsDBNull(217) ? (decimal?)null : reader.GetDecimal(217),
                    PaymentforAIHW_33297 = reader.IsDBNull(218) ? null : reader.GetString(218),
                    PaymentforAIHW_33297_ResponseChoiceID = reader.IsDBNull(219) ? (int?)null : reader.GetInt32(219),
                    DateSafetyUpgradeCompleted_33299 = reader.IsDBNull(220) ? (DateTime?)null : reader.GetDateTime(220),
                    IfanymonitoringoreffortiswasrequiredtocompleteSafetyUpgradepleasedescribe_33300 = reader.IsDBNull(221) ? null : reader.GetString(221),
                    ServiceUserDFVOonlyOusterCondition_33301 = reader.IsDBNull(222) ? null : reader.GetString(222),
                    ServiceUserDFVOonlyOusterCondition_33301_ResponseChoiceID = reader.IsDBNull(223) ? (int?)null : reader.GetInt32(223),
                    IstheServiceUsercurrentlylivinginthehome_33302 = reader.IsDBNull(224) ? null : reader.GetString(224),
                    IstheServiceUsercurrentlylivinginthehome_33302_ResponseChoiceID = reader.IsDBNull(225) ? (int?)null : reader.GetInt32(225),
                    NumberofChildrenlivingwiththeServiceUserinhome_33303 = reader.IsDBNull(226) ? (int?)null : reader.GetInt32(226),
                    TransportofParticipanttofromApptorActivitySA1_33304 = reader.IsDBNull(227) ? (int?)null : reader.GetInt32(227),
                    TransportofParticipanttofromApptorActivitySA2_33305 = reader.IsDBNull(228) ? (int?)null : reader.GetInt32(228),
                    TimespenttravellingTransportofParticipanttofromApptorActivitySA3_33306 = reader.IsDBNull(229) ? (int?)null : reader.GetInt32(229),
                    TimespenttravellingTransportofParticipanttofromApptorActivitySA4_33307 = reader.IsDBNull(230) ? (int?)null : reader.GetInt32(230),
                    TimespenttravellingTransportofParticipanttofromApptorActivity_33308 = reader.IsDBNull(231) ? (int?)null : reader.GetInt32(231),
                    TotaltimespenttravellingTransportofParticipanttofromApptorActivity_33309 = reader.IsDBNull(232) ? (int?)null : reader.GetInt32(232),
                    Financeprojectcode_33310 = reader.IsDBNull(233) ? (int?)null : reader.GetInt32(233),
                    Brieftransactiondescription_33311 = reader.IsDBNull(234) ? null : reader.GetString(234),
                    Supplierprovider_33312 = reader.IsDBNull(235) ? (int?)null : reader.GetInt32(235),
                    Ifotherprovidesupplierbusinessname_33313 = reader.IsDBNull(236) ? null : reader.GetString(236),
                    Howwaspaymentmade_33314 = reader.IsDBNull(237) ? null : reader.GetString(237),
                    Howwaspaymentmade_33314_ResponseChoiceID = reader.IsDBNull(238) ? (int?)null : reader.GetInt32(238),
                    Authorisedby_33315 = reader.IsDBNull(239) ? (int?)null : reader.GetInt32(239),
                    Isanyportionofthistransactionrecoverable_33316 = reader.IsDBNull(240) ? null : reader.GetString(240),
                    Isanyportionofthistransactionrecoverable_33316_ResponseChoiceID = reader.IsDBNull(241) ? (int?)null : reader.GetInt32(241),
                    Recoveryinvoicename_33317 = reader.IsDBNull(242) ? null : reader.GetString(242),
                    Amountrecoverablefromthissource_33318 = reader.IsDBNull(243) ? (decimal?)null : reader.GetDecimal(243),
                    Recoveryinvoicecontactname_33319 = reader.IsDBNull(244) ? null : reader.GetString(244),
                    Recoveryinvoicecontactemail_33320 = reader.IsDBNull(245) ? null : reader.GetString(245),
                    Haspaymentalreadybeenmadeordoesfinancestillneedtopay_33321 = reader.IsDBNull(246) ? null : reader.GetString(246),
                    Haspaymentalreadybeenmadeordoesfinancestillneedtopay_33321_ResponseChoiceID = reader.IsDBNull(247) ? (int?)null : reader.GetInt32(247),
                    IsthistransactionrelatedtoHousingandSafetyUpgrades_33322 = reader.IsDBNull(248) ? null : reader.GetString(248),
                    IsthistransactionrelatedtoHousingandSafetyUpgrades_33322_ResponseChoiceID = reader.IsDBNull(249) ? (int?)null : reader.GetInt32(249),
                    Wasbrokeragedoneforthisactivity_33325 = reader.IsDBNull(250) ? null : reader.GetString(250),
                    Wasbrokeragedoneforthisactivity_33325_ResponseChoiceID = reader.IsDBNull(251) ? (int?)null : reader.GetInt32(251),
                    Purpose_33327 = reader.IsDBNull(252) ? null : reader.GetString(252),
                    Purpose_33327_ResponseChoiceID = reader.IsDBNull(253) ? (int?)null : reader.GetInt32(253),
                    WasNaloxone_33329 = reader.IsDBNull(254) ? null : reader.GetString(254),
                    WasNaloxone_33329_ResponseChoiceID = reader.IsDBNull(255) ? (int?)null : reader.GetInt32(255),
                    UploadDocument_33331 = reader.IsDBNull(256) ? (int?)null : reader.GetInt32(256),
                    TESTDONOTCOMPLETEWhichtypeofdwellingdoesthisindividualcurrentlyresideinFOROUTREACHNURSEONLY_33332 = reader.IsDBNull(257) ? null : reader.GetString(257),
                    TESTDONOTCOMPLETEWhichtypeofdwellingdoesthisindividualcurrentlyresideinFOROUTREACHNURSEONLY_33332_ResponseChoiceID = reader.IsDBNull(258) ? (int?)null : reader.GetInt32(258),
                    TESTDONOTCOMPLETEIstheparticipantcurrentlyresidinginastableresidentialdwellingForoutreachnursi_33333 = reader.IsDBNull(259) ? null : reader.GetString(259),
                    TESTDONOTCOMPLETEIstheparticipantcurrentlyresidinginastableresidentialdwellingForoutreachnursi_33333_ResponseChoiceID = reader.IsDBNull(260) ? (int?)null : reader.GetInt32(260),
                    Whichstaffmembersbusinesscardwasused_33337 = reader.IsDBNull(261) ? (int?)null : reader.GetInt32(261),
                    Whichstaffmemberistobereimbursed_33338 = reader.IsDBNull(262) ? null : reader.GetInt32(262),
                    FName = reader.IsDBNull(263) ? null : reader.GetString(263),
                    LName = reader.IsDBNull(264) ? null : reader.GetString(264)
                });
                } catch (Exception ex)
                    {
                        Console.WriteLine($"Exception: {ex.GetType().Name}: {ex.Message}");
                    }
               
            }
            return serviceActivities;
        }
    }
}

