namespace EtoApi.Models
{
    public class AddressBook
    {
        public int? FormResponseID { get; set; }
        public int? FormIdentifier { get; set; }
        public int? SubjectID { get; set; }
        public int? GroupID { get; set; }
        public int? FamilyID { get; set; }
        public int? ResponseSetID { get; set; }
        public int? FormID { get; set; }
        public int? CollectionTypeID { get; set; }
        public int? SubjectTypeID { get; set; }
        public int? CollectionID { get; set; }
        public DateTime? ResponseCreatedDate { get; set; }
        public int? ProgramID { get; set; }
        public int? AuditStaffID { get; set; }
        public DateTime? AuditDate { get; set; }
        public int? DataEnteredByID { get; set; }
        public DateTime? DraftSavedOn { get; set; }
        public DateTime? RemovedDate { get; set; }
        public DateTime? DateThisPersonBecameTheNextOfKin_9372 { get; set; }
        public string? Name_9373 { get; set; }
        public string? Address_9374 { get; set; }
        public string? Relationship_9376 { get; set; }
        public int? Relationship_9376_ResponseChoiceID { get; set; }
        public string? PermissionToContactNextOfKinIfRequired_9377 { get; set; }
        public int? PermissionToContactNextOfKinIfRequired_9377_ResponseChoiceID { get; set; }
        public int? Organisation_9444 { get; set; }
        public string? Role_9446 { get; set; }
        public string? ApartmentunitNumber_9458 { get; set; }
        public string? StreetNumber_9459 { get; set; }
        public string? StreetName_9460 { get; set; }
        public string? Suburblocality_9461 { get; set; }
        public string? State_9462 { get; set; }
        public string? IsThisChildInYourFullTimeCare_9467 { get; set; }
        public int? IsThisChildInYourFullTimeCare_9467_ResponseChoiceID { get; set; }
        public DateTime? Dob_9475 { get; set; }
        public string? Gender_9477 { get; set; }
        public int? Gender_9477_ResponseChoiceID { get; set; }
        public string? CareDetails_9479 { get; set; }
        public string? ChildRelationship_9505 { get; set; }
        public int? ChildRelationship_9505_ResponseChoiceID { get; set; }
        public string? WhoseContactDetailsarethese_9521 { get; set; }
        public int? WhoseContactDetailsarethese_9521_ResponseChoiceID { get; set; }
        public string? MobilePhone_9523 { get; set; }
        public string? WorkPhone_9525 { get; set; }
        public string? HomePhone_9526 { get; set; }
        public int? SelectparticipantinETO_9529 { get; set; }
        public DateTime? DatethispersonceasedbeingNextofKin_9530 { get; set; }
        public string? IsthisthecurrentNextofKin_9533 { get; set; }
        public int? IsthisthecurrentNextofKin_9533_ResponseChoiceID { get; set; }
        public string? CommentsNotes_9534 { get; set; }
        public string? Email_9535 { get; set; }
        public string? ApartmentUnitNo_10903 { get; set; }
        public string? StreetNumber_10904 { get; set; }
        public string? StreetName_10905 { get; set; }
        public string? Suburb_10906 { get; set; }
        public string? PostCode_10910 { get; set; }
        public string? POBox_10911 { get; set; }
        public int? HousingProvider_11403 { get; set; }
        public DateTime? DatethisbecameHousingProvider_12590 { get; set; }
        public DateTime? DatethisceasedasHousingProvider_12591 { get; set; }
        public DateTime? Whendidtheparticipantbegintoresideatthisaddress_12911 { get; set; }
        public DateTime? WhendidtheparticipantceaseresidingatthisaddressLeaveblankifcurrentaddress_12912 { get; set; }
        public int? SelectGeneralPractitioner_13123 { get; set; }
        public DateTime? DatethisbecameyourGP_13127 { get; set; }
        public DateTime? DatethisceasedbeingyourGP_13128 { get; set; }
        public string? WhatistheState_13303 { get; set; }
        public int? WhatistheState_13303_ResponseChoiceID { get; set; }
        public string? SafetocallM_13306 { get; set; }
        public int? SafetocallM_13306_ResponseChoiceID { get; set; }
        public string? SafetocallW_13307 { get; set; }
        public int? SafetocallW_13307_ResponseChoiceID { get; set; }
        public string? SafetocallH_13308 { get; set; }
        public int? SafetocallH_13308_ResponseChoiceID { get; set; }
        public string? Notescommentsaboutphonesemail_13309 { get; set; }
        public string? IsthispersonaprivateguardianfortheparticipantappointedbytheQueenslandCivilandAdministrativeTri_16831 { get; set; }
        public int? IsthispersonaprivateguardianfortheparticipantappointedbytheQueenslandCivilandAdministrativeTri_16831_ResponseChoiceID { get; set; }
        public DateTime? Datethispersonbecameaprivateguardian_16832 { get; set; }
        public DateTime? DatethispersonceasedbeingaPrivateGuardian_16833 { get; set; }
        public string? Isthispersonaninformaldecisionmakeronbehalfoftheparticipant_16834 { get; set; }
        public int? Isthispersonaninformaldecisionmakeronbehalfoftheparticipant_16834_ResponseChoiceID { get; set; }
        public DateTime? Datethispersonbecameaninformaldecisionmaker_16835 { get; set; }
        public DateTime? Datethispersonceasedbeinganinformaldecisionmaker_16836 { get; set; }
        public int? ContactatPublicGuardian_16851 { get; set; }
        public string? AttorneyunderEnduringPowerofAttorneyorAdvanceHealthDirective_16855 { get; set; }
        public int? StatutoryHealthAttorney_16857 { get; set; }
        public DateTime? DatethisentitybecameaSubstituteDecisionMaker_16865 { get; set; }
        public DateTime? DatethisentityceasedbeingaSubstituteDecisionMakerleaveblankifcurrent_16866 { get; set; }
        public string? SafetoM_16872 { get; set; }
        public int? SafetoM_16872_ResponseChoiceID { get; set; }
        public string? SafetoW_16873 { get; set; }
        public int? SafetoW_16873_ResponseChoiceID { get; set; }
        public string? SafetoH_16874 { get; set; }
        public int? SafetoH_16874_ResponseChoiceID { get; set; }
        public int? SelectHealthSpecialist_17361 { get; set; }
        public string? ProgramName_19776 { get; set; }
        public string? Address1_19777 { get; set; }
        public string? Address2_19779 { get; set; }
        public string? AusSuburbLocality_19780 { get; set; }
        public string? StateAus_19781 { get; set; }
        public string? AusPostalCode_19782 { get; set; }
        public string? AusPhoneNumber_19783 { get; set; }
        public string? Address1_19785 { get; set; }
        public string? Address2_19786 { get; set; }
        public string? AusSuburbLocality_19787 { get; set; }
        public string? StateAus_19788 { get; set; }
        public string? AusPostalCode_19789 { get; set; }
        public string? AusPhoneNumber_19790 { get; set; }
        public string? Address1_19792 { get; set; }
        public string? Address2_19793 { get; set; }
        public string? AusSuburbLocality_19794 { get; set; }
        public string? StateAus_19795 { get; set; }
        public string? AusPostalCode_19796 { get; set; }
        public string? AusPhoneNumber_19797 { get; set; }
        public string? Address1_19799 { get; set; }
        public string? Address2_19800 { get; set; }
        public string? AusSuburbLocality_19801 { get; set; }
        public string? StateAus_19802 { get; set; }
        public string? AusPostalCode_19803 { get; set; }
        public string? AusPhoneNumber_19804 { get; set; }
        public string? PostCodet_20568 { get; set; }
        public string? IsthisthecurrentEmergencyContact_21680 { get; set; }
        public int? IsthisthecurrentEmergencyContact_21680_ResponseChoiceID { get; set; }
        public string? Addressbookstatus_23962 { get; set; }
        public DateTime? DatethiscontactbecameNoncurrent_25349 { get; set; }
        public string? AccommodationType_27221 { get; set; }
        public int? AccommodationType_27221_ResponseChoiceID { get; set; }
        public string? IfotherPleasespecify_27223 { get; set; }
        public int? WhichHostelBoardinghouseisit_27224 { get; set; }
        public string? Isthisa_27225 { get; set; }
        public int? Isthisa_27225_ResponseChoiceID { get; set; }
        public string? UsethisaddressforDRCDEXsubmission_28230 { get; set; }
        public int? UsethisaddressforDRCDEXsubmission_28230_ResponseChoiceID { get; set; }
        public string? KeyNumber_28234 { get; set; }
        public int? SuburbandPostCode_28290 { get; set; }
        public DateTime? Datethisceasedasserviceprovider_29299 { get; set; }
    }
}
