namespace EtoApi.Models
{
    public class AIHWFormModel
    {
        public int? FormResponseID { get; set; }
        public string? FormIdentifier { get; set; }
        public int? SubjectID { get; set; }
        public int? GroupID { get; set; }
        public int? FamilyID { get; set; }
        public int? ResponseSetID { get; set; }
        public int? FormID { get; set; }
        public int? CollectionTypeID { get; set; }
        public int? SubjectTypeID { get; set; }
        public int? CollectionID { get; set; }
        public DateTime? ResponseCreatedDate { get; set; }
        public int? ProgramID { get; set; }
        public int? AuditStaffID { get; set; }
        public DateTime? AuditDate { get; set; }
        public int? DataEnteredByID { get; set; }
        public DateTime? DraftSavedOn { get; set; }
        public DateTime? RemovedDate { get; set; }
        public string? WhatReasonsDoesTheParticipantReportForSeekingAssistance_14662 { get; set; }
        public int? WhatReasonsDoesTheParticipantReportForSeekingAssistance_14662_ResponseChoiceID { get; set; }
        public string? WhatOtherReasonsDoesTheParticipantReportForSeekingAssistance_14663 { get; set; }
        public string? IfYourSafetyOrThatOfYourFamilyIsAConcernForYouWouldYouLikeHelpToImproveYourSafety_14664 { get; set; }
        public int? IfYourSafetyOrThatOfYourFamilyIsAConcernForYouWouldYouLikeHelpToImproveYourSafety_14664_ResponseChoiceID { get; set; }
        public string? IfThisParticipantHasACareOrProtectionOrderWhatWereTheCareArrangementsTheWeekBeforePresentingFo_14669 { get; set; }
        public int? IfThisParticipantHasACareOrProtectionOrderWhatWereTheCareArrangementsTheWeekBeforePresentingFo_14669_ResponseChoiceID { get; set; }
        public string? IfThisParticipantHasACareOrProtectionOrderWhatWereTheCareArrangementsWhenPresentingForEachFami_14670 { get; set; }
        public int? IfThisParticipantHasACareOrProtectionOrderWhatWereTheCareArrangementsWhenPresentingForEachFami_14670_ResponseChoiceID { get; set; }
        public string? HaveYouBeenInAnyOfTheseInstitutionsOrFacilitiesInTheLast12MonthsforEachFamilyMember_14671 { get; set; }
        public int? HaveYouBeenInAnyOfTheseInstitutionsOrFacilitiesInTheLast12MonthsforEachFamilyMember_14671_ResponseChoiceID { get; set; }
        public string? DoYouHaveAPhysicalHealthConditionDiagnosedByAHealthProfessionalMp_14673 { get; set; }
        public int? DoYouHaveAPhysicalHealthConditionDiagnosedByAHealthProfessionalMp_14673_ResponseChoiceID { get; set; }
        public int? Confirmthatconsentwasgiventoprovidenonidentifieddataforgovernmentreporting_17491_ResponseChoiceID { get; set; }
        public string? IfYouHaveADiagnosedPhysicalHealthConditionDetailsMp_14674 { get; set; }
        public string? DoYouHaveAMentalHealthConditionDiagnosedByAHealthProfessional_14675 { get; set; }
        public int? DoYouHaveAMentalHealthConditionDiagnosedByAHealthProfessional_14675_ResponseChoiceID { get; set; }
        public string? HaveYouBeenGivenMedicationToHelpManageYourEmotionsOrVoicesthoughtsCap_14676 { get; set; }
        public int? HaveYouBeenGivenMedicationToHelpManageYourEmotionsOrVoicesthoughtsCap_14676_ResponseChoiceID { get; set; }
        public string? DoYouStruggleWithManagingTheseEmotionsCap_14677 { get; set; }
        public int? DoYouStruggleWithManagingTheseEmotionsCap_14677_ResponseChoiceID { get; set; }
        public string? DoYouStruggleWithHearingVoicesAndorHaveProblemsWithYourThoughtsCap_14678 { get; set; }
        public int? DoYouStruggleWithHearingVoicesAndorHaveProblemsWithYourThoughtsCap_14678_ResponseChoiceID { get; set; }
        public string? OverWhatTimePeriodHaveYouReceivedServicesOrAssistanceForYourMentalHealthIssue_14679 { get; set; }
        public int? OverWhatTimePeriodHaveYouReceivedServicesOrAssistanceForYourMentalHealthIssue_14679_ResponseChoiceID { get; set; }
        public string? IsThereAnyAdditionalInformationFormalOrInformalThatIndicatesTheClientHasAMentalHealthIssue_14680 { get; set; }
        public int? IsThereAnyAdditionalInformationFormalOrInformalThatIndicatesTheClientHasAMentalHealthIssue_14680_ResponseChoiceID { get; set; }
        public string? DoYouHaveAnyReasonToBeConcernedAboutYourOwnSafetyOrIfApplicableTheSafetyOfYourChildren_14684 { get; set; }
        public int? DoYouHaveAnyReasonToBeConcernedAboutYourOwnSafetyOrIfApplicableTheSafetyOfYourChildren_14684_ResponseChoiceID { get; set; }
        public string? IfSomeoneIsInDangerWhoIsIt_14685 { get; set; }
        public int? IfSomeoneIsInDangerWhoIsIt_14685_ResponseChoiceID { get; set; }
        public string? AreYouCurrentlyHomeless_14688 { get; set; }
        public int? AreYouCurrentlyHomeless_14688_ResponseChoiceID { get; set; }
        public string? AreYouCurrentlyAtRiskOfHomelessness_14689 { get; set; }
        public int? AreYouCurrentlyAtRiskOfHomelessness_14689_ResponseChoiceID { get; set; }
        public string? IfYouHaveBeenGivenMedicationDetailsCap_14690 { get; set; }
        public string? IfYouHaveADiagnosedDisabilityDetails_14694 { get; set; }
        public string? HaveYouEverUsedAlcoholOrOtherDrugsEgAlcoholIllegalDrugsInhalantsPrescriptionOrOverTheCounterDr_14696 { get; set; }
        public int? HaveYouEverUsedAlcoholOrOtherDrugsEgAlcoholIllegalDrugsInhalantsPrescriptionOrOverTheCounterDr_14696_ResponseChoiceID { get; set; }
        public string? InTheLastThreeMonthsHaveYouFeltThatYouShouldCutDownOrStopDrinkingAlcoholOrUsingDrugsCap_14697 { get; set; }
        public int? InTheLastThreeMonthsHaveYouFeltThatYouShouldCutDownOrStopDrinkingAlcoholOrUsingDrugsCap_14697_ResponseChoiceID { get; set; }
        public string? InTheLastThreeMonthsHasAnyoneAnnoyedYouOrGottenOnYourNervesByTellingYouThatYouShouldCutDownOrS_14698 { get; set; }
        public int? InTheLastThreeMonthsHasAnyoneAnnoyedYouOrGottenOnYourNervesByTellingYouThatYouShouldCutDownOrS_14698_ResponseChoiceID { get; set; }

        public string? InTheLastThreeMonthsHaveYouFeltGuiltyOrBadAboutHowMuchYouAreDrinkingOrUsingDrugsCap_14699 { get; set; }
        public int? InTheLastThreeMonthsHaveYouFeltGuiltyOrBadAboutHowMuchYouAreDrinkingOrUsingDrugsCap_14699_ResponseChoiceID { get; set; }
        public string? InTheLastThreeMonthsHaveYouWokenUpFeelingLikeYouWantDrinkAlcoholOrUseDrugsCap_14700 { get; set; }
        public int? InTheLastThreeMonthsHaveYouWokenUpFeelingLikeYouWantDrinkAlcoholOrUseDrugsCap_14700_ResponseChoiceID { get; set; }
        public string? DoYouNeedHelpsupervisionWithSelfcareEgShoweringOrBathingDressingOrUndressingToiletingOrEatingF_14704 { get; set; }
        public int? DoYouNeedHelpsupervisionWithSelfcareEgShoweringOrBathingDressingOrUndressingToiletingOrEatingF_14704_ResponseChoiceID { get; set; }
        public string? DoYouNeedHelpsupervisionWithMobilityEgMovingAroundTheHouseGettingInAndOutOfAChair_14705 { get; set; }
        public int? DoYouNeedHelpsupervisionWithMobilityEgMovingAroundTheHouseGettingInAndOutOfAChair_14705_ResponseChoiceID { get; set; }
        public string? DoYouNeedHelpsupervisionWithCommunicationEgUnderstandingOrBeingUnderstoodByOtherPeopleIncludin_14706 { get; set; }
        public int? DoYouNeedHelpsupervisionWithCommunicationEgUnderstandingOrBeingUnderstoodByOtherPeopleIncludin_14706_ResponseChoiceID { get; set; }
        public string? LabourForceStatus_14710 { get; set; }
        public int? LabourForceStatus_14710_ResponseChoiceID { get; set; }
        public string? IfTheParticipantIs15yrsWhatIsTheirEmploymentStatus_14711 { get; set; }
        public int? IfTheParticipantIs15yrsWhatIsTheirEmploymentStatus_14711_ResponseChoiceID { get; set; }
        public string? MainSourceOfIncome_14712 { get; set; }
        public int? MainSourceOfIncome_14712_ResponseChoiceID { get; set; }
        public string? IsTheParticipantCurrentlyRegisteredForAGovernmentBenefitPensionOrAllowanceButAwaitingYourFirst_14713 { get; set; }
        public int? IsTheParticipantCurrentlyRegisteredForAGovernmentBenefitPensionOrAllowanceButAwaitingYourFirst_14713_ResponseChoiceID { get; set; }
        public string? IsTheParticipantUndertakingFormalStudyOrTrainingEgSchoolUniversityVocationalStudiesSuchAsTafe_14714 { get; set; }
        public int? IsTheParticipantUndertakingFormalStudyOrTrainingEgSchoolUniversityVocationalStudiesSuchAsTafe_14714_ResponseChoiceID { get; set; }
        public string? WhatTypeOfEducationtrainingIsTheParticipantEnrolledIn_14715 { get; set; }
        public int? WhatTypeOfEducationtrainingIsTheParticipantEnrolledIn_14715_ResponseChoiceID { get; set; }
        public string? LabourForceStatus_14716 { get; set; }
        public int? LabourForceStatus_14716_ResponseChoiceID { get; set; }
        public string? IfTheParticipantIs15yrsWhatIsTheirEmploymentStatus_14717 { get; set; }
        public int? IfTheParticipantIs15yrsWhatIsTheirEmploymentStatus_14717_ResponseChoiceID { get; set; }
        public string? MainSourceOfIncome_14718 { get; set; }
        public int? MainSourceOfIncome_14718_ResponseChoiceID { get; set; }
        public string? IsTheParticipantCurrentlyRegisteredForAGovernmentBenefitPensionOrAllowanceButAwaitingYourFirst_14719 { get; set; }
        public int? IsTheParticipantCurrentlyRegisteredForAGovernmentBenefitPensionOrAllowanceButAwaitingYourFirst_14719_ResponseChoiceID { get; set; }
        public string? IsTheParticipantUndertakingFormalStudyOrTrainingEgSchoolUniversityVocationalStudiesSuchAsTafe_14720 { get; set; }
        public int? IsTheParticipantUndertakingFormalStudyOrTrainingEgSchoolUniversityVocationalStudiesSuchAsTafe_14720_ResponseChoiceID { get; set; }
        public string? WhatTypeOfEducationtrainingIsTheParticipantEnrolledIn_14722 { get; set; }
        public int? WhatTypeOfEducationtrainingIsTheParticipantEnrolledIn_14722_ResponseChoiceID { get; set; }
        public decimal? WhatIsTheTotalOfYouYourFamilysFortnightlyIncomeCap_14723 { get; set; }
        public string? DoYouHaveDebtsMp_14725 { get; set; }
        public int? DoYouHaveDebtsMp_14725_ResponseChoiceID { get; set; }
        public string? DoYouHaveASperDebtMp_14726 { get; set; }
        public int? DoYouHaveASperDebtMp_14726_ResponseChoiceID { get; set; }
        public string? HasThisParticipantEverHadPreviousEpisodesOfHomelessnessUnk_14728 { get; set; }
        public int? HasThisParticipantEverHadPreviousEpisodesOfHomelessnessUnk_14728_ResponseChoiceID { get; set; }
        public decimal? WhatIsTheTotalNumberOfMonthsThatYouHaveEverLivedOnTheStreetsOrInEmergencyAccommodationVispdat_14729 { get; set; }
        public decimal? WhatIsTheTotalNumberOfMonthsThatYouHaveEverLivedWithoutStableAccommodationVispdat_14730 { get; set; }
        public string? EpisodeOfHomelessness_14731 { get; set; }
        public int? EpisodeOfHomelessness_14731_ResponseChoiceID { get; set; }
        public string? EpisodeOfHomelessness_14734 { get; set; }
        public int? EpisodeOfHomelessness_14734_ResponseChoiceID { get; set; }
        public string? HowLongSinceYouHadThisPermanentPlaceToLive_14737 { get; set; }
        public int? HowLongSinceYouHadThisPermanentPlaceToLive_14737_ResponseChoiceID { get; set; }
        public string? WhatWasTheSuburblocalityOfYourMostRecentPermanentPlaceToLive_14738 { get; set; }
        public decimal? WhatWasThePostcodeOfYourMostRecentPermanentPlaceToLive_14739 { get; set; }
        public string? WhatIsTheState_14740 { get; set; }
        public int? WhatIsTheState_14740_ResponseChoiceID { get; set; }
        public string? WhatWasTheSuburbWhereYouResidedLastWeek_14742 { get; set; }
        public decimal? WhatWasThePostcodeWhereYouResidedLastWeek_14743 { get; set; }
        public string? WhatIsTheState_14744 { get; set; }
        public int? WhatIsTheState_14744_ResponseChoiceID { get; set; }
        public decimal? HowManyTimesHaveYouChangedAddressInThePastThreeYearsVispdat_14746 { get; set; }
        public string? WouldYouDescribeYourCurrentHousingAsAdequateAndAffordableEgSafeLongTermSuitableLocationAccessT_14747 { get; set; }
        public int? WouldYouDescribeYourCurrentHousingAsAdequateAndAffordableEgSafeLongTermSuitableLocationAccessT_14747_ResponseChoiceID { get; set; }
        public string? IfCurrentHousingIsNotAdequateDetailsCap_14748 { get; set; }
        public decimal? HowMuchAreYouPayingWeeklyForHousingCap_14749 { get; set; }
        public string? DoYouHaveACurrentDepartmentOfHousingDohApplicationMp_14750 { get; set; }
        public int? DoYouHaveACurrentDepartmentOfHousingDohApplicationMp_14750_ResponseChoiceID { get; set; }
        public string? IfYouHaveACurrentDohApplicationWhatIsTheApplicationNumber_14751 { get; set; }
        public int? OfficeWhereTheDohApplicationWasLodged_14752 { get; set; }
        public string? Tenure_14754 { get; set; }
        public int? Tenure_14754_ResponseChoiceID { get; set; }
        public string? DwellingType_14755 { get; set; }
        public int? DwellingType_14755_ResponseChoiceID { get; set; }
        public string? LivingArrangements_14756 { get; set; }
        public int? LivingArrangements_14756_ResponseChoiceID { get; set; }
        public string? ConditionsOfOccupancy_14757 { get; set; }
        public int? ConditionsOfOccupancy_14757_ResponseChoiceID { get; set; }
        public string? DwellingType_14758 { get; set; }
        public int? DwellingType_14758_ResponseChoiceID { get; set; }
        public string? LivingArrangements_14759 { get; set; }
        public int? LivingArrangements_14759_ResponseChoiceID { get; set; }
        public string? ConditionsOfOccupancy_14760 { get; set; }
        public int? ConditionsOfOccupancy_14760_ResponseChoiceID { get; set; }
        public string? Tenure_14761 { get; set; }
        public int? Tenure_14761_ResponseChoiceID { get; set; }
        public string? AreYouPregnantOrPlanningToHaveAChildInTheComingYear_14764 { get; set; }
        public int? AreYouPregnantOrPlanningToHaveAChildInTheComingYear_14764_ResponseChoiceID { get; set; }
        public DateTime? IfPregnantWhatIsYourDueDate_14765 { get; set; }
        public decimal? HowManyWeeksPregnantAreYou_14766 { get; set; }
        public decimal? HowManyChildrenCurrentlyInYourFullTimePrimaryCareWhetherTheyAreParticipantsAtMicahOrNot_14768 { get; set; }
        public decimal? HowManyChildrenDoYouHaveWhoAreNotCurrentlyInYourFullTimeCareWhetherTheyAreParticipantsAtMicahO_14769 { get; set; }
        public decimal? TotalNumberOfChildrenIncludingThoseInYourfullTimeCareAndThoseNotInFullTimeCare_14770 { get; set; }
        public string? AreYouCurrentlyReceivingServicesToAssistYouWithYourParenting_14772 { get; set; }
        public int? AreYouCurrentlyReceivingServicesToAssistYouWithYourParenting_14772_ResponseChoiceID { get; set; }
        public int? IfYouAreReceivingSupportFromServicesWhoIsThePrimaryServiceAssistingYou_14773 { get; set; }
        public int? IfYouAreReceivingSupportFromServicesWhichOtherServiceIsAssistingYouIfApplicable_14774 { get; set; }
        public string? WhatOtherSupportsFamilyFriendsOtherDoYouHaveToHelpYouWithYourParenting_14775 { get; set; }
        public string? DoYouHaveAnyCurrentConcernsAboutYourParenting_14776 { get; set; }
        public int? DoYouHaveAnyCurrentConcernsAboutYourParenting_14776_ResponseChoiceID { get; set; }
        public string? WhatDoYouThinkIsWorkingWellInRegardToyourParenting_14777 { get; set; }
        public string? WhatDoYouThinkIsNotWorkingWellInRegardToYourParenting_14778 { get; set; }
        public string? WouldYouLikeHelpOrFeelYouNeedSupportInAnyOfTheFollowingAreas_14780 { get; set; }
        public int? WouldYouLikeHelpOrFeelYouNeedSupportInAnyOfTheFollowingAreas_14780_ResponseChoiceID { get; set; }
        public string? HasChildSafetyEverBeenInvolvedWithTheFamilyInThePast_14781 { get; set; }
        public int? HasChildSafetyEverBeenInvolvedWithTheFamilyInThePast_14781_ResponseChoiceID { get; set; }
        public string? IfChildSafetyHasBeenInvolvedInThePastDetails_14782 { get; set; }
        public int? IfChildSafetyHasBeenInvolvedInThePastDetails_14782_ResponseChoiceID { get; set; }
        public string? IsChildSafetyCurrentlyInvolvedWithTheFamily_14783 { get; set; }
        public int? IsChildSafetyCurrentlyInvolvedWithTheFamily_14783_ResponseChoiceID { get; set; }
        public string? IfChildSafetyIsCurrentlyInvolvedWithTheFamilyDetails_14784 { get; set; }
        public int? IfChildSafetyIsCurrentlyInvolvedWithTheFamilyDetails_14784_ResponseChoiceID { get; set; }
        public int? WhichChildSafetyOfficeIsInvolved_14785 { get; set; }
        public string? WhatIsTheNameOfTheChildSafetyOfficerCso_14786 { get; set; }
        public string? DoYouAttendRegularPreAndorAntenatalAppointments_14787 { get; set; }
        public int? DoYouAttendRegularPreAndorAntenatalAppointments_14787_ResponseChoiceID { get; set; }
        public string? AreYouReceivingAssistanceWithTheseConcernsFromProfessionalsUnk_14788 { get; set; }
        public int? AreYouReceivingAssistanceWithTheseConcernsFromProfessionalsUnk_14788_ResponseChoiceID { get; set; }
        public string? AreYouReceivingInformalSupportAndAssistanceFromAnyoneUnk_14789 { get; set; }
        public int? AreYouReceivingInformalSupportAndAssistanceFromAnyoneUnk_14789_ResponseChoiceID { get; set; }
        public string? IfYouAreReceivingInformalSupportDetailsUnk_14790 { get; set; }
        public string? DoesYourUseOfAlcoholOrDrugsContributeToAnyDifficultiesForYouInAnyOfTheFollowingAreasCap_14791 { get; set; }
        public int? DoesYourUseOfAlcoholOrDrugsContributeToAnyDifficultiesForYouInAnyOfTheFollowingAreasCap_14791_ResponseChoiceID { get; set; }
        public string? IfYesByWho_14792 { get; set; }
        public string? AreYouReceivingAppropriateSupportAndTreatmentForThisCondition_14794 { get; set; }
        public int? AreYouReceivingAppropriateSupportAndTreatmentForThisCondition_14794_ResponseChoiceID { get; set; }
        public string? WouldYouLikeAssistanceAccessingAppropriateCaretreatmentsupportForYourDisability_14795 { get; set; }
        public int? WouldYouLikeAssistanceAccessingAppropriateCaretreatmentsupportForYourDisability_14795_ResponseChoiceID { get; set; }
        public string? OtherNotesAboutCareProtectionIssues_14796 { get; set; }
        public string? OtherNotesAboutEducationEmploymentAndFinances_14797 { get; set; }
        public string? OtherNotesAboutHousingIssues_14798 { get; set; }
        public string? IfThereIsPresenceOfDomesticViolencedisruptionToFamilyRelationshipsAndTheParticipantHasRequeste_14799 { get; set; }
        public int? IfThereIsPresenceOfDomesticViolencedisruptionToFamilyRelationshipsAndTheParticipantHasRequeste_14799_ResponseChoiceID { get; set; }
        public string? IfYesWhatDisabilityDiagnosedByAHealthProfessionalDoYouHaveMp_14800 { get; set; }
        public int? IfYesWhatDisabilityDiagnosedByAHealthProfessionalDoYouHaveMp_14800_ResponseChoiceID { get; set; }
        public string? DoYouHaveADisabilityDiagnosedByAHealthProfessionalMp_14801 { get; set; }
        public int? DoYouHaveADisabilityDiagnosedByAHealthProfessionalMp_14801_ResponseChoiceID { get; set; }
        public decimal? Age_14803 { get; set; }
        public string? IfSomeoneIsInDangerWhatType_14806 { get; set; }
        public int? IfSomeoneIsInDangerWhatType_14806_ResponseChoiceID { get; set; }
        public string? IfYesByWhom_14807 { get; set; }
        public string? DoesYourMentalHealthConditionsContributeToAnyDifficultiesForYouInAnyOfTheFollowingAreasCap_14808 { get; set; }
        public int? DoesYourMentalHealthConditionsContributeToAnyDifficultiesForYouInAnyOfTheFollowingAreasCap_14808_ResponseChoiceID { get; set; }
        public string? Details_14809 { get; set; }
        public string? AreYouReceivingAppropriateCaretreatmentsupportInRegardToYourDisabilityMp_14810 { get; set; }
        public int? AreYouReceivingAppropriateCaretreatmentsupportInRegardToYourDisabilityMp_14810_ResponseChoiceID { get; set; }
        public string? Details_14811 { get; set; }
        public string? IfYesDetails_14812 { get; set; }
        public string? IsTheParticipantChildEnrolledInOneOfTheFollowing_14814 { get; set; }
        public int? IsTheParticipantChildEnrolledInOneOfTheFollowing_14814_ResponseChoiceID { get; set; }
        public string? DoesTheParticipantHaveAccessToThreeHealthyMealsADayEveryDayEgHotMealsForDinnerDietThatIncludes_14816 { get; set; }
        public int? DoesTheParticipantHaveAccessToThreeHealthyMealsADayEveryDayEgHotMealsForDinnerDietThatIncludes_14816_ResponseChoiceID { get; set; }
        public string? WouldYouLikeHelpAccessingFoodForYourFamily_14817 { get; set; }
        public int? WouldYouLikeHelpAccessingFoodForYourFamily_14817_ResponseChoiceID { get; set; }
        public string? Details_14818 { get; set; }
        public string? IfSoHowOftenDoesTheParticipantChildGetThere_14819 { get; set; }
        public int? IfSoHowOftenDoesTheParticipantChildGetThere_14819_ResponseChoiceID { get; set; }
        public string? WouldTheFamilyLikeHelpWithAccessingSchoolOrKindergartenOrAttendingMoreRegularly_14820 { get; set; }
        public int? WouldTheFamilyLikeHelpWithAccessingSchoolOrKindergartenOrAttendingMoreRegularly_14820_ResponseChoiceID { get; set; }
        public string? Details_14821 { get; set; }
        public string? AreImmunisationsUpToDate_14823 { get; set; }
        public int? AreImmunisationsUpToDate_14823_ResponseChoiceID { get; set; }
        public string? DoesTheParticipantChildhaveAnyOfTheFollowingDiagnosedconditions_14824 { get; set; }
        public int? DoesTheParticipantChildhaveAnyOfTheFollowingDiagnosedconditions_14824_ResponseChoiceID { get; set; }
        public string? Details_14825 { get; set; }
        public string? IfYouHaveADiagnosedMentalHealthConditionDetails_14826 { get; set; }
        public string? OfTheseReasonsWhichDoesTheParticipantReportAsBeingTheMainReasonForSeekingAssistance_14827 { get; set; }
        public int? OfTheseReasonsWhichDoesTheParticipantReportAsBeingTheMainReasonForSeekingAssistance_14827_ResponseChoiceID { get; set; }
        public string? DoesThePublicTrusteeAdministerTheParticipantsPersonalFinancesMp_14829 { get; set; }
        public int? DoesThePublicTrusteeAdministerTheParticipantsPersonalFinancesMp_14829_ResponseChoiceID { get; set; }
        public string? WithinDemographicsMedicareNumberWasAnsweredAs_14837 { get; set; }
        public string? WithinDemographicsMedicareNoIndividualIdWasAnsweredAs_14838 { get; set; }
        public int? AtSpdatIndiividualHowManyTimesHaveYouChangedAddressesWasAnsweredAs_14840 { get; set; }
        public string? AtSpdatIndiividualHowManyTimesHaveYouChangedAddressesWasAnsweredAs_14840_DisplayStr { get; set; }
        public string? AsAChildWereYouEverInTheFollowingInstitutions_14841 { get; set; }
        public int? AsAChildWereYouEverInTheFollowingInstitutions_14841_ResponseChoiceID { get; set; }
        public int? AtSpdatIndividualAsAChildWereYouEverInTheFollowingInstitutionsWasAnsweredAsUseResponsesToThisQ_14842 { get; set; }
        public string? AtSpdatIndividualAsAChildWereYouEverInTheFollowingInstitutionsWasAnsweredAsUseResponsesToThisQ_14842_DisplayStr { get; set; }
        public string? AsAnAdultHaveYouEverBeenInTheFollowingInstitutions_14843 { get; set; }
        public int? AsAnAdultHaveYouEverBeenInTheFollowingInstitutions_14843_ResponseChoiceID { get; set; }
        public int? AtSpdatIndividualMainSourceOfIncomeWasAnsweredAs_14846 { get; set; }
        public string? AtSpdatIndividualMainSourceOfIncomeWasAnsweredAs_14846_DisplayStr { get; set; }
        public string? WhatWasTheSchoolEnrolmentAndAttendanceStatusOnPresentation_14847 { get; set; }
        public int? WhatWasTheSchoolEnrolmentAndAttendanceStatusOnPresentation_14847_ResponseChoiceID { get; set; }
        public string? WhatIsTheHighestYearOfSchoolYouCompletedVispdat_14849 { get; set; }
        public int? WhatIsTheHighestYearOfSchoolYouCompletedVispdat_14849_ResponseChoiceID { get; set; }
        public int? MostRecentQhipConsentWasSignedByParticipantOn_14854 { get; set; }
        public string? MostRecentQhipConsentWasSignedByParticipantOn_14854_DisplayStr { get; set; }
        public int? MostRecentMicahStandardConsentWasSignedByParticipantOn_14855 { get; set; }
        public string? MostRecentMicahStandardConsentWasSignedByParticipantOn_14855_DisplayStr { get; set; }
        public int? AtFamilySpdatWhatIsTheTotalLengthOfTimeYouAndYourFamilyHaveNotHadYourOwnTenancyWasAnsweredAs_14857 { get; set; }
        public string? AtFamilySpdatWhatIsTheTotalLengthOfTimeYouAndYourFamilyHaveNotHadYourOwnTenancyWasAnsweredAs_14857_DisplayStr { get; set; }
        public int? AtIndividualSpdatWhatIsTheTotalLengthOfTimeYouHaveLivedOnTheStreetsOrInEmergencyAccommodationW_14858 { get; set; }
        public string? AtIndividualSpdatWhatIsTheTotalLengthOfTimeYouHaveLivedOnTheStreetsOrInEmergencyAccommodationW_14858_DisplayStr { get; set; }
        public decimal? KeepMeEmpty_14860 { get; set; }
        public decimal? VariableAtIndividualSpdatWhatIsTheTotalLengthOfTimeYouHaveLivedOnTheStreetsOrInEmergencyAccomm_14861 { get; set; }
        public decimal? VariableAtFamilySpdatWhatIsTheTotalLengthOfTimeYouAndYourFamilyHaveNotHadYourOwnTenancyWasAnsw_14862 { get; set; }
        public decimal? VariableAtSpdatIndividualAsAChildWereYouEverInTheFollowingInstitutionsWasAnsweredAs_14865 { get; set; }
        public decimal? VariableAtSpdatIndividualAsAnAdultHaveYouBeenInTheFollowingInstitutionsWasAnsweredAs_14866 { get; set; }
        public decimal? VariableAtSpdatIndividualDoYouHaveADisabilityDiagnosedByAHealthProfessionalWasAnsweredAs_14867 { get; set; }
        public decimal? VariableAtSpdatIndividualMainSourceOfIncomeWasAnsweredAs_14868 { get; set; }
        public decimal? VariableAtSpdatFamilyMainSourceOfIncomeWasAnsweredAs_14869 { get; set; }
        public decimal? VariableAtSpdatIndividualWhatIsTheHighestYearOfSchoolYouCompletedWasAnsweredAs_14870 { get; set; }
        public decimal? VariableAtSpdatFamilyWhatIsTheHighestYearOfSchoolYouCompletedWasAnsweredAs_14871 { get; set; }
        public decimal? VariableAtSpdatIndividualWhatWasTheSchoolEnrolmentAndAttendanceStatusOnPresentationWasAnswered_14872 { get; set; }
        public decimal? VariableAtSpdatIndividualHowManyTimesHaveYouChangedAddressesWasAnsweredAs_14873 { get; set; }
        public decimal? VariableAtSpdatFamilyHowManyTimesHaveYouChangedAddressesWasAnsweredAs_14874 { get; set; }
        public int? AtSpdatFamilyMainSourceOfIncomeWasAnsweredAs_14876 { get; set; }
        public string? AtSpdatFamilyMainSourceOfIncomeWasAnsweredAs_14876_DisplayStr { get; set; }
        public int? AtSpdatFamilyHowManyTimesHaveYouChangedAddressesWasAnsweredAs_14878 { get; set; }
        public string? AtSpdatFamilyHowManyTimesHaveYouChangedAddressesWasAnsweredAs_14878_DisplayStr { get; set; }
        public string? FrequentPresenterHospitalConsent_14881 { get; set; }
        public int? FrequentPresenterHospitalConsent_14881_ResponseChoiceID { get; set; }
        public string? HospitalUrNumber_14882 { get; set; }
        public DateTime? HospitalDischargeDate_14883 { get; set; }
        public string? HospitalDischargeSummary_14884 { get; set; }
        public int? HospitalDischargeSummary_14884_ResponseChoiceID { get; set; }
        public string? SupportiveHousingHopeStreetLowIncomeOrFormerlyHomeless_14885 { get; set; }
        public int? SupportiveHousingHopeStreetLowIncomeOrFormerlyHomeless_14885_ResponseChoiceID { get; set; }
        public DateTime? LeaseSignDate_14886 { get; set; }
        public DateTime? MoveInDate_14887 { get; set; }
        public string? AreYouTicaListedMp_14888 { get; set; }
        public int? AreYouTicaListedMp_14888_ResponseChoiceID { get; set; }
        public int? WithinAddressBookGpHasBeenEnteredAs_14891 { get; set; }
        public string? WithinAddressBookGpHasBeenEnteredAs_14891_DisplayStr { get; set; }
        public string? AtIntakeDoYouHaveARegularGpThatYouAttend_14893 { get; set; }
        public int? AtIntakeDoYouHaveARegularGpThatYouAttend_14893_ResponseChoiceID { get; set; }
        public string? Doyouhaveanappointedsubstitutedecisionmakermp_14902 { get; set; }
        public int? Doyouhaveanappointedsubstitutedecisionmakermp_14902_ResponseChoiceID { get; set; }
        public string? SHSTypeOfServiceActivityTxt_15117 { get; set; }
        public int? Totalefforttimeforparticipant_15588 { get; set; }
        public string? SHSTypeOfServiceActivityNum_16051 { get; set; }
        public decimal? HowmanystaffdidthistogetherAtmost4_16157 { get; set; }
        public int? Selectyourname_16158 { get; set; }
        public string? MicahTeam_16159 { get; set; }
        public string? Start_16161 { get; set; }
        public string? Endoptional_16162 { get; set; }
        public int? Selectthe2ndstaffperson_16163 { get; set; }
        public int? Whatotherteamassisted_16164 { get; set; }
        public string? WasthisaPATpersonalvisit_16165 { get; set; }
        public int? WasthisaPATpersonalvisit_16165_ResponseChoiceID { get; set; }
        public int? TimespentonbehalfofparticipantPerstaffmember_16166 { get; set; }
        public int? TimespenttravellingNotwithparticipantPerstaffmember_16167 { get; set; }
        public int? TimespentwithparticipantPerstaffmember_16168 { get; set; }
        public string? WastheparticipantfamilypresentduringthisactivityAnswerYesifconversingwithParticipantFamilyonph_16169 { get; set; }
        public int? WastheparticipantfamilypresentduringthisactivityAnswerYesifconversingwithParticipantFamilyonph_16169_ResponseChoiceID { get; set; }
        public string? ContactLocation_16170 { get; set; }
        public int? ContactLocation_16170_ResponseChoiceID { get; set; }
        public string? ContactMethod_16171 { get; set; }
        public int? ContactMethod_16171_ResponseChoiceID { get; set; }
        public string? Ifcontactlocationisotherpleasespecify_16172 { get; set; }
        public string? PhoneContactType_16173 { get; set; }
        public int? PhoneContactType_16173_ResponseChoiceID { get; set; }
        public int? Totaltimespentonbehalfofparticipant_16174 { get; set; }
        public int? Totaltimespenttravelling_16175 { get; set; }
        public int? Totaltimespentwithparticipant_16176 { get; set; }
        public int? Selectthedischargesummaryuploaded_16837 { get; set; }
        public int? Selectthedischargesummaryuploaded_16837_SourceFormID { get; set; }
        public string? Selectthedischargesummaryuploaded_16837_DisplayStr { get; set; }
        public int? SelecttheEDFPConsentuploaded_16838 { get; set; }
        public int? SelecttheEDFPConsentuploaded_16838_SourceFormID { get; set; }
        public string? SelecttheEDFPConsentuploaded_16838_DisplayStr { get; set; }
        public string? Whatisthesourceofinformationthatthispersonmayhaveamentalillnessormentalhealthcondition_16936 { get; set; }
        public int? Whatisthesourceofinformationthatthispersonmayhaveamentalillnessormentalhealthcondition_16936_ResponseChoiceID { get; set; }
        public string? Whatistheparticipantsprimarygoalforenrollinginthisprogram_19812 { get; set; }
        public int? Whatistheparticipantsprimarygoalforenrollinginthisprogram_19812_ResponseChoiceID { get; set; }
        public string? Theskillsoutlinedbelowarerequiredtocompletethisprogrampleaseindicatewhichoftheseskillstheparti_19814 { get; set; }
        public int? Theskillsoutlinedbelowarerequiredtocompletethisprogrampleaseindicatewhichoftheseskillstheparti_19814_ResponseChoiceID { get; set; }
        public string? Whichofthefollowingfearsconcernsassociatedwithcompletingthisprogramapplytothisparticipant_19815 { get; set; }
        public int? Whichofthefollowingfearsconcernsassociatedwithcompletingthisprogramapplytothisparticipant_19815_ResponseChoiceID { get; set; }
        public string? Isthereanyadditionalsupportthatthisparticipantwillrequiretocompletetheprogram_19816 { get; set; }
        public string? Doyouhavedebtsynump_20360 { get; set; }
        public int? Doyouhavedebtsynump_20360_ResponseChoiceID { get; set; }
        public string? DoyouhaveaSPERdebtynump_20361 { get; set; }
        public int? DoyouhaveaSPERdebtynump_20361_ResponseChoiceID { get; set; }
        public string? Whatwasthepostcodeofyourmostrecentpermanentplacetolivet_20362 { get; set; }
        public string? Whatwasthepostcodewhereyouresidedlastweekt_20363 { get; set; }
        public string? AIHWOrganisationID_21823 { get; set; }
        public int? Whatwasthesuburblocalityofyourmostrecentpermanentplacetolive_21824 { get; set; }

        public int? Whatwasthesuburbwhereyouresidedlastweek_21825 { get; set; }
        public string? SubmitsSHSAIHWreports_21832 { get; set; }
        public string? SummaryObservations_23040 { get; set; }
        public string? IstheparticipantcurrentlyreceivinganagreedpackageofsupportthroughtheNationalDisabilityInsuranc_24805 { get; set; }
        public int? IstheparticipantcurrentlyreceivinganagreedpackageofsupportthroughtheNationalDisabilityInsuranc_24805_ResponseChoiceID { get; set; }
        public string? FName { get; set; }
        public string? LName { get; set; }
        public string? SubjectName { get; set; }
        public string? ProgramName { get; set; }

        
    }
}