namespace EtoApi.Models
{
    public class BrokeragePaymentModel
    {
        public int? FormResponseID { get; set; }
        public string? FormIdentifier { get; set; }
        public int? SubjectID { get; set; }
        public int? GroupID { get; set; }
        public int? FamilyID { get; set; }
        public int? ResponseSetID { get; set; }
        public int? FormID { get; set; }
        public int? CollectionTypeID { get; set; }
        public int? SubjectTypeID { get; set; }
        public int? CollectionID { get; set; }
        public DateTime? ResponseCreatedDate { get; set; }
        public int? ProgramID { get; set; }
        public int? AuditStaffID { get; set; }
        public DateTime? AuditDate { get; set; }
        public int? DataEnteredByID { get; set; }
        public DateTime? DraftSavedOn { get; set; }
        public DateTime? RemovedDate { get; set; }
        public string? Purpose_6508 { get; set; }
        public int? Purpose_6508_ResponseChoiceID { get; set; }
        public string? Context_6510 { get; set; }
        public int? Context_6510_ResponseChoiceID { get; set; }
        public string? PaymentMethod_6511 { get; set; }
        public int? PaymentMethod_6511_ResponseChoiceID { get; set; }
        public decimal? NumberOfAdults_6514 { get; set; }
        public decimal? NumberOfChildren_6515 { get; set; }
        public decimal? NumberOfNightsOfaccommodation_6516 { get; set; }
        public decimal? AmountRecovered_6518 { get; set; }
        public DateTime? TransactionDate_6525 { get; set; }
        public string? Shouldthepaperformbeanonymous_6527 { get; set; }
        public int? Shouldthepaperformbeanonymous_6527_ResponseChoiceID { get; set; }
        public string? JobCode_6528 { get; set; }
        public int? JobCode_6528_ResponseChoiceID { get; set; }
        public decimal? TransactionAmount_6530 { get; set; }
        public string? IsGSTincluded_6531 { get; set; }
        public int? IsGSTincluded_6531_ResponseChoiceID { get; set; }
        public decimal? NonGSTAmount_6532 { get; set; }
        public string? DetailsofTransaction_6533 { get; set; }
        public string? PaymentforAIHW_6535 { get; set; }
        public int? PaymentforAIHW_6535_ResponseChoiceID { get; set; }
        public string? PurposeOther_6537 { get; set; }
        public string? HUBReason_6541 { get; set; }
        public int? HUBReason_6541_ResponseChoiceID { get; set; }
        public string? Haspaymentalreadybeenmadeordoesfinancestillneedtopay_6548 { get; set; }
        public int? Haspaymentalreadybeenmadeordoesfinancestillneedtopay_6548_ResponseChoiceID { get; set; }
        public string? PaymentMethod_6550 { get; set; }
        public int? PaymentMethod_6550_ResponseChoiceID { get; set; }
        public string? WhoseBusinessCreditCard_6551 { get; set; }
        public string? Vouchertype_6553 { get; set; }
        public int? Vouchertype_6553_ResponseChoiceID { get; set; }
        public string? ChequePayableTo_6554 { get; set; }
        public string? ChequeDeliveryPostInstructions_6555 { get; set; }
        public string? ChequeDeliveryPickupInstructions_6556 { get; set; }
        public string? EFTAccountName_6558 { get; set; }
        public decimal? EFTBSB_6559 { get; set; }
        public decimal? EFTAccountNumber_6560 { get; set; }
        public decimal? BPayBillerCode_6561 { get; set; }
        public string? BPayBillerReference_6562 { get; set; }
        public string? Isanyportionofthistransactionrecoverable_6563 { get; set; }
        public int? Isanyportionofthistransactionrecoverable_6563_ResponseChoiceID { get; set; }
        public decimal? AmountRecovered2_6570 { get; set; }
        public string? AuthorisingContact1_6571 { get; set; }
        public string? AuthorisingContact2_6572 { get; set; }
        public string? AuthorisingContactEmail1_6573 { get; set; }
        public string? AuthorisingContactEmail2_6574 { get; set; }
        public string? RecoveryInvoiceAddress1_6577 { get; set; }
        public string? RecoveryInvoiceAddress2_6578 { get; set; }
        public int? Worker1_7379 { get; set; }
        public int? Worker2_7380 { get; set; }
        public int? Ifpaidbystaffpersonallywhichstaff_7384 { get; set; }
        public string? RecoveryInvoiceFax1_7389 { get; set; }
        public string? AuthorisingContactPhone1_7390 { get; set; }
        public string? RecoveryInvoiceFax2_7394 { get; set; }
        public string? AuthorisingContactPhone2_7395 { get; set; }
        public string? TeamLeaderSignOff_8255 { get; set; }
        public string? TeamLeaderSignOff_8255_Signee { get; set; }
        public byte[]? TeamLeaderSignOff_8255_Image { get; set; }
        public string? MicahTeam_8276 { get; set; }
        public int? MicahTeam_8276_ResponseChoiceID { get; set; }
        public int? SupplierProvider_8871 { get; set; }
        public int? RecoveryInvoiceName1_8872 { get; set; }
        public int? RecoveryInvoiceName2_8873 { get; set; }
        public string? HUBPurpose_9316 { get; set; }
        public int? HUBPurpose_9316_ResponseChoiceID { get; set; }
        public string? HUBExpenseType_9317 { get; set; }
        public int? HUBExpenseType_9317_ResponseChoiceID { get; set; }
        public int? MicahTeam_11295 { get; set; }
        public string? TenancyAccessorSustainment_13318 { get; set; }
        public int? TenancyAccessorSustainment_13318_ResponseChoiceID { get; set; }
        public string? AuthorizedBy_16942 { get; set; }
        public string? AuthorizedBy_16942_Signee { get; set; }
        public byte[]? AuthorizedBy_16942_Image { get; set; }
        public int? AuthorizedBy_16943 { get; set; }
        public int? FinanceJobCode_16945 { get; set; }
        public string? FinanceShortJobCode_16946 { get; set; }
        public string? SignatureofCreditCardHolder_16947 { get; set; }
        public string? SignatureofCreditCardHolder_16947_Signee { get; set; }
        public byte[]? SignatureofCreditCardHolder_16947_Image { get; set; }
        public int? SelectBusinessCreditCardHolder_16948 { get; set; }
        public int? WhichPettyCashTin_16959 { get; set; }
        public string? Willthistransactionbenefitonlythisindividualorisitforanentirefamily_21917 { get; set; }
        public int? Willthistransactionbenefitonlythisindividualorisitforanentirefamily_21917_ResponseChoiceID { get; set; }
        public string? ServiceUserDFVOonlyOusterCondition_22992 { get; set; }
        public int? ServiceUserDFVOonlyOusterCondition_22992_ResponseChoiceID { get; set; }
        public string? IstheServiceUsercurrentlylivinginthehome_22993 { get; set; }
        public int? IstheServiceUsercurrentlylivinginthehome_22993_ResponseChoiceID { get; set; }
        public decimal? NumberofChildrenlivingwiththeServiceUserinhome_22995 { get; set; }
        public DateTime? DateSafetyUpgradeCompleted_22996 { get; set; }
        public string? SafetyUpgradeComments_22997 { get; set; }
        public int? AttachDocumentssuchasInvoicesorreceipts_23268 { get; set; }
        public string? IfotherWhatisit_23527 { get; set; }
        public string? ABN_23535 { get; set; }
        public string? BSBNumber_26963 { get; set; }
        public string? BrokerageTypeShouldbeansweredonlybytheLotusDRCteam_27196 { get; set; }
        public int? BrokerageTypeShouldbeansweredonlybytheLotusDRCteam_27196_ResponseChoiceID { get; set; }
        public string? Category_28340 { get; set; }
        public int? Category_28340_ResponseChoiceID { get; set; }
        public string? AIHWpurpose_28341 { get; set; }
        public int? AIHWpurpose_28341_ResponseChoiceID { get; set; }
        public decimal? Ofchildrenunder5_32024 { get; set; }
        public decimal? childrenbetween6and12_32025 { get; set; }
        public decimal? childrenbetween13and18_32026 { get; set; }

    }
}