namespace EtoApi.Models
{
    public class DemographicsDetails
    {
        public int? CLID { get; set; }
        public string? CDID_3752 { get; set; }
        public string? CDID_3754 { get; set; }
        public string? CDID_3755 { get; set; }
        public string? CDID_3756 { get; set; }
        public string? CDID_3757 { get; set; }
        public string? CDID_3758 { get; set; }
        public string? CDID_3759 { get; set; }
        public string? CDID_3760 { get; set; }
        public string? CDID_3761 { get; set; }
        public string? CDID_3762 { get; set; }
        public string? CDID_3763 { get; set; }
        public string? CDID_3764 { get; set; }
        public string? CDID_3765 { get; set; }
        public string? CDID_3766 { get; set; }
        public string? CDID_3767 { get; set; }
        public string? CDID_3768 { get; set; }
        public string? CDID_3769 { get; set; }
        public string? CDID_3770 { get; set; }
        public string? CDID_3771 { get; set; }
        public string? CDID_3772 { get; set; }
        public string? CDID_3773 { get; set; }
        public string? CDID_3774 { get; set; }
        public string? CDID_3775 { get; set; }
        public string? CDID_3777 { get; set; }
        public string? CDID_3778 { get; set; }
        public string? CDID_3779 { get; set; }
        public DateTime? CDID_3780 { get; set; }
        public string? CDID_3781 { get; set; }
        public decimal? CDID_3782 { get; set; }
        public string? CDID_3783 { get; set; }
        public string? CDID_3784 { get; set; }
        public string? CDID_3785 { get; set; }
        public string? CDID_3786 { get; set; }
        public string? CDID_3787 { get; set; }
        public string? CDID_3788 { get; set; }
        public string? CDID_3789 { get; set; }
        public string? CDID_3790 { get; set; }
        public string? CDID_3791 { get; set; }
        public string? CDID_3792 { get; set; }
        public string? CDID_3793 { get; set; }
        public string? CDID_3794 { get; set; }
        public string? CDID_3795 { get; set; }
        public string? CDID_3796 { get; set; }
        public string? CDID_3797 { get; set; }
        public string? CDID_3798 { get; set; }
        public string? CDID_3799 { get; set; }
        public string? CDID_3800 { get; set; }
        public string? CDID_3801 { get; set; }
        public string? CDID_3802 { get; set; }
        public string? CDID_3803 { get; set; }
        public string? CDID_3804 { get; set; }
        public string? CDID_3805 { get; set; }
        public string? CDID_3806 { get; set; }
        public DateTime? CDID_3807 { get; set; }
        public string? CDID_3808 { get; set; }
        public string? CDID_3809 { get; set; }
        public string? CDID_3810 { get; set; }
        public string? CDID_3811 { get; set; }
        public decimal? CDID_3812 { get; set; }
        public string? CDID_3813 { get; set; }
        public string? CDID_3814 { get; set; }
        public string? CDID_3815 { get; set; }
        public string? CDID_3816 { get; set; }
        public string? CDID_3817 { get; set; }
        public string? CDID_3818 { get; set; }
        public string? CDID_3819 { get; set; }
        public string? CDID_3820 { get; set; }
        public string? CDID_3821 { get; set; }
        public DateTime? CDID_3822 { get; set; }
        public decimal? CDID_3823 { get; set; }
        public string? CDID_3824 { get; set; }
        public string? CDID_3825 { get; set; }
        public string? CDID_3826 { get; set; }
        public string? CDID_3827 { get; set; }
        public string? CDID_3830 { get; set; }
        public string? CDID_3831 { get; set; }
        public string? CDID_3832 { get; set; }
        public string? CDID_3833 { get; set; }
        public string? CDID_3838 { get; set; }
        public string? CDID_3839 { get; set; }
        public string? CDID_3840 { get; set; }
        public string? CDID_3842 { get; set; }
    }
}
