namespace EtoApi.Models
{
public class LotusNotes
{
    public int? FormResponseID { get; set; }
    public string FormIdentifier { get; set; }
    public int? SubjectID { get; set; }
    public int? GroupID { get; set; }
    public int? FamilyID { get; set; }
    public int? ResponseSetID { get; set; }
    public int? FormID { get; set; }
    public int? CollectionTypeID { get; set; }
    public int? SubjectTypeID { get; set; }
    public int? CollectionID { get; set; }
    public DateTime? ResponseCreatedDate { get; set; }
    public int? ProgramID { get; set; }
    public int? AuditStaffID { get; set; }
    public DateTime? AuditDate { get; set; }
    public int? DataEnteredByID { get; set; }
    public DateTime? DraftSavedOn { get; set; }
    public DateTime? RemovedDate { get; set; }
    public string ContactMethod_27348 { get; set; }
    public int? ContactMethod_27348_ResponseChoiceID { get; set; }
    public string ContactLocation_27349 { get; set; }
    public int? ContactLocation_27349_ResponseChoiceID { get; set; }
    public decimal? HowmanystaffdidthistogetherAtmost4_27350 { get; set; }
    public int? TimespentwithparticipantPerstaffmember_27351 { get; set; }
    public int? TimespentonbehalfofparticipantPerstaffmember_27352 { get; set; }
    public int? TimespenttravellingNotwithparticipantPerstaffmember_27353 { get; set; }
    public int? Totaltimespentwithparticipant_27354 { get; set; }
    public int? Totaltimespentonbehalfofparticipant_27355 { get; set; }
    public int? Totaltimespenttravelling_27356 { get; set; }
    public int? Totalefforttimeforparticipant_27357 { get; set; }
    public int? Selectyourname_27358 { get; set; }
    public int? MicahTeam_27359 { get; set; }
    public int? Selectthe2ndstaffperson_27360 { get; set; }
    public int? Whatotherteamassisted_27361 { get; set; }
    public string ServiceType_27366 { get; set; }
    public int? ServiceType_27366_ResponseChoiceID { get; set; }
    public string ServiceSetting_27367 { get; set; }
    public int? ServiceSetting_27367_ResponseChoiceID { get; set; }
    public string InterpreterPresent_27368 { get; set; }
    public int? InterpreterPresent_27368_ResponseChoiceID { get; set; }
    public string Notes_27369 { get; set; }
    public string Disabilityimpairmentorconditionindicator_27372 { get; set; }
    public int? Disabilityimpairmentorconditionindicator_27372_ResponseChoiceID { get; set; }
    public string Selectallofthereasonsforseekingassistance_27378 { get; set; }
    public int? Selectallofthereasonsforseekingassistance_27378_ResponseChoiceID { get; set; }
    public string SelectDomain_27386 { get; set; }
    public int? SelectDomain_27386_ResponseChoiceID { get; set; }
    public string SelectthemainreasonforseekingassistanceNotethemainreasonmustbeoneofthereasonstickedabove_27408 { get; set; }
    public int? SelectthemainreasonforseekingassistanceNotethemainreasonmustbeoneofthereasonstickedabove_27408_ResponseChoiceID { get; set; }
    public string Selectyourlocation_27412 { get; set; }
    public int? Selectyourlocation_27412_ResponseChoiceID { get; set; }
    public string? StartTime_27430 { get; set; }
    public string? EndTimeoptional_27431 { get; set; }
    public string ContactCategory_27854 { get; set; }
    public int? ContactCategory_27854_ResponseChoiceID { get; set; }
    public string ContactDomain_27855 { get; set; }
    public int? ContactDomain_27855_ResponseChoiceID { get; set; }
    public int? WhatWDYNwasthisactioninresponseto_27856 { get; set; }
    public int? WhatWDYNwasthisactioninresponseto_27856_SourceFormID { get; set; }
    public string WhatWDYNwasthisactioninresponseto_27856_DisplayStr { get; set; }
    public string ContactLocation_28145 { get; set; }
    public int? ContactLocation_28145_ResponseChoiceID { get; set; }
    public string Program_28235 { get; set; }
    public int? Program_28235_ResponseChoiceID { get; set; }
    public string TypeofNote_28236 { get; set; }
    public int? TypeofNote_28236_ResponseChoiceID { get; set; }
    public string Checkallfurtherassessmentsthatneedtobecompleted_29024 { get; set; }
    public int? Checkallfurtherassessmentsthatneedtobecompleted_29024_ResponseChoiceID { get; set; }
    public string Scoreassessedby_29027 { get; set; }
    public int? Scoreassessedby_29027_ResponseChoiceID { get; set; }
    public string Isthisthefirstpreorlastpostscore_29028 { get; set; }
    public int? Isthisthefirstpreorlastpostscore_29028_ResponseChoiceID { get; set; }
    public string DomainGoals_29029 { get; set; }
    public int? DomainGoals_29029_ResponseChoiceID { get; set; }
    public string ChangedbehavioursScore1Noprogressinchangingbehavioursinareasrelevanttoclientsneedsandcircumsta_29032 { get; set; }
    public int? ChangedbehavioursScore1Noprogressinchangingbehavioursinareasrelevanttoclientsneedsandcircumsta_29032_ResponseChoiceID { get; set; }
    public string ChangedimmediatecrisisScore1NoprogressinreducingthenegativeimpactoftheimmediatecrisisScore2Lim_29033 { get; set; }
    public int? ChangedimmediatecrisisScore1NoprogressinreducingthenegativeimpactoftheimmediatecrisisScore2Lim_29033_ResponseChoiceID { get; set; }
    public string ChangedknowledgeandaccesstoinformationScore1Noprogressinincreasingaccesstoinformationandknowle_29103 { get; set; }
    public int? ChangedknowledgeandaccesstoinformationScore1Noprogressinincreasingaccesstoinformationandknowle_29103_ResponseChoiceID { get; set; }
    public string ChangedSkillsScore1NoprogressinincreasingskillsinareasrelevanttoclientsneedsandcircumstancesSc_29104 { get; set; }
    public int? ChangedSkillsScore1NoprogressinincreasingskillsinareasrelevanttoclientsneedsandcircumstancesSc_29104_ResponseChoiceID { get; set; }
    public string EmpowermentchoiceandcontroltomakeowndecisionsScore1Noprogressinincreasingconfidenceandexercisi_29105 { get; set; }
    public int? EmpowermentchoiceandcontroltomakeowndecisionsScore1Noprogressinincreasingconfidenceandexercisi_29105_ResponseChoiceID { get; set; }
    public string EngagementwithrelevantsupportservicesScore1Noprogressinincreasingengagementwithsupportservices_29106 { get; set; }
    public int? EngagementwithrelevantsupportservicesScore1Noprogressinincreasingengagementwithsupportservices_29106_ResponseChoiceID { get; set; }
    public string DomainCircumstances_29107 { get; set; }
    public int? DomainCircumstances_29107_ResponseChoiceID { get; set; }
    public string AgeappropriatedevelopmentScore1Significantnegativeimpactofpoorageappropriatedevelopmentonindep_29109 { get; set; }
    public int? AgeappropriatedevelopmentScore1Significantnegativeimpactofpoorageappropriatedevelopmentonindep_29109_ResponseChoiceID { get; set; }
    public string CommunityparticipationnetworksScore1Significantnegativeimpactofpoorcommunityparticipationnetwo_29110 { get; set; }
    public int? CommunityparticipationnetworksScore1Significantnegativeimpactofpoorcommunityparticipationnetwo_29110_ResponseChoiceID { get; set; }
    public string EducationandskillstrainingScore1Significantnegativeimpactoflackofengagementwitheducationandtra_29111 { get; set; }
    public int? EducationandskillstrainingScore1Significantnegativeimpactoflackofengagementwitheducationandtra_29111_ResponseChoiceID { get; set; }
    public string EmploymentScore1Significantnegativeimpactoflackofemploymentonindependenceparticipationandwellb_29112 { get; set; }
    public int? EmploymentScore1Significantnegativeimpactoflackofemploymentonindependenceparticipationandwellb_29112_ResponseChoiceID { get; set; }
    public string FamilyFunctioningScore1Significantnegativeimpactofpoorfamilyfunctioningonindependenceparticipa_29113 { get; set; }
    public int? FamilyFunctioningScore1Significantnegativeimpactofpoorfamilyfunctioningonindependenceparticipa_29113_ResponseChoiceID { get; set; }
    public string FinancialresilienceScore1Significantnegativeimpactofpoorfinancialresilienceonindependenceparti_29114 { get; set; }
    public int? FinancialresilienceScore1Significantnegativeimpactofpoorfinancialresilienceonindependenceparti_29114_ResponseChoiceID { get; set; }
    public string HousingScore1Significantnegativeimpactofpoorhousingonindependenceparticipationandwellbeingegro_29115 { get; set; }
    public int? HousingScore1Significantnegativeimpactofpoorhousingonindependenceparticipationandwellbeingegro_29115_ResponseChoiceID { get; set; }
    public string MaterialwellbeingandbasicnecessitiesScore1Significantnegativeimpactoflackofbasicmaterialresour_29116 { get; set; }
    public int? MaterialwellbeingandbasicnecessitiesScore1Significantnegativeimpactoflackofbasicmaterialresour_29116_ResponseChoiceID { get; set; }
    public string MentalhealthwellbeingandselfcareScore1Significantnegativeimpactofpoormentalhealthwellbeingands_29117 { get; set; }
    public int? MentalhealthwellbeingandselfcareScore1Significantnegativeimpactofpoormentalhealthwellbeingands_29117_ResponseChoiceID { get; set; }
    public string PersonalsafetyScore1Significantnegativeimpactofpoorpersonalandfamilysafetyonindependencepartic_29118 { get; set; }
    public int? PersonalsafetyScore1Significantnegativeimpactofpoorpersonalandfamilysafetyonindependencepartic_29118_ResponseChoiceID { get; set; }
    public string PhysicalhealthScore1Significantnegativeimpactofpoorphysicalhealthonindependenceparticipationan_29119 { get; set; }
    public int? PhysicalhealthScore1Significantnegativeimpactofpoorphysicalhealthonindependenceparticipationan_29119_ResponseChoiceID { get; set; }
    public string DomainSatisfaction_29120 { get; set; }
    public int? DomainSatisfaction_29120_ResponseChoiceID { get; set; }
    public string Iambetterabletodealwithissuesthatsoughthelpwith_29122 { get; set; }
    public int? Iambetterabletodealwithissuesthatsoughthelpwith_29122_ResponseChoiceID { get; set; }
    public string IamsatisfiedwiththeservicesIhavereceived_29123 { get; set; }
    public int? IamsatisfiedwiththeservicesIhavereceived_29123_ResponseChoiceID { get; set; }
    public string Theservicelistenedtomeandunderstoodmyissues_29124 { get; set; }
    public int? Theservicelistenedtomeandunderstoodmyissues_29124_ResponseChoiceID { get; set; }
    public string Partofthisengagementwasareferraldone_29458 { get; set; }
    public int? Partofthisengagementwasareferraldone_29458_ResponseChoiceID { get; set; }
    public string Referredto_29459 { get; set; }
    public string Scoring_31496 { get; set; }
    public string ProgramName { get; set; }
    public string EntityName { get; set; }
    public string FName { get; set; }
    public string LName { get; set; }
}
}