namespace EtoApi.Models
{
public class LotusInitialForm
{
    public int? FormResponseID { get; set; }
    public string FormIdentifier { get; set; }
    public int? SubjectID { get; set; }
    public int? GroupID { get; set; }
    public int? FamilyID { get; set; }
    public int? ResponseSetID { get; set; }
    public int? FormID { get; set; }
    public int? CollectionTypeID { get; set; }
    public int? SubjectTypeID { get; set; }
    public int? CollectionID { get; set; }
    public DateTime? ResponseCreatedDate { get; set; }
    public int? ProgramID { get; set; }
    public int? AuditStaffID { get; set; }
    public DateTime? AuditDate { get; set; }
    public int? DataEnteredByID { get; set; }
    public DateTime? DraftSavedOn { get; set; }
    public DateTime? RemovedDate { get; set; }
    public string ContactMethod_27264 { get; set; }
    public int? ContactMethod_27264_ResponseChoiceID { get; set; }
    public string ContactLocation_27265 { get; set; }
    public int? ContactLocation_27265_ResponseChoiceID { get; set; }
    public string PhoneContactType_27266 { get; set; }
    public int? PhoneContactType_27266_ResponseChoiceID { get; set; }
    public string Ifcontactlocationisotherpleasespecify_27267 { get; set; }
    public decimal? HowmanystaffdidthistogetherAtmost4_27268 { get; set; }
    public int? TimespentwithparticipantPerstaffmember_27269 { get; set; }
    public int? TimespentonbehalfofparticipantPerstaffmember_27270 { get; set; }
    public int? TimespenttravellingNotwithparticipantPerstaffmember_27271 { get; set; }
    public int? Totaltimespentwithparticipant_27272 { get; set; }
    public int? Totaltimespentonbehalfofparticipant_27273 { get; set; }
    public int? Totaltimespenttravelling_27274 { get; set; }
    public int? Totalefforttimeforparticipant_27275 { get; set; }
    public int? Selectyourname_27276 { get; set; }
    public int? MicahTeam_27277 { get; set; }
    public int? Selectthe2ndstaffperson_27278 { get; set; }
    public int? Whatotherteamassisted_27279 { get; set; }
    public string Howdidyoufindoutaboutourservice_27283 { get; set; }
    public int? Howdidyoufindoutaboutourservice_27283_ResponseChoiceID { get; set; }
    public string Preferredcounsellingsupportvia_27293 { get; set; }
    public int? Preferredcounsellingsupportvia_27293_ResponseChoiceID { get; set; }
    public string Areyouthepersonwithadisability_27299 { get; set; }
    public int? Areyouthepersonwithadisability_27299_ResponseChoiceID { get; set; }
    public string Disabilityimpairmentorconditionindicator_27304 { get; set; }
    public int? Disabilityimpairmentorconditionindicator_27304_ResponseChoiceID { get; set; }
    public int? LanguageSpokenatHomeotherthanEnglish_27305 { get; set; }
    public string Mainsourceofincome_27313 { get; set; }
    public int? Mainsourceofincome_27313_ResponseChoiceID { get; set; }
    public string Selectallofthereasonsforseekingassistance_27321 { get; set; }
    public int? Selectallofthereasonsforseekingassistance_27321_ResponseChoiceID { get; set; }
    public string Selectyourlocation_27324 { get; set; }
    public int? Selectyourlocation_27324_ResponseChoiceID { get; set; }
    public string MailingList_27329 { get; set; }
    public int? MailingList_27329_ResponseChoiceID { get; set; }
    public string Areyouworkingwithanyotherservices_27331 { get; set; }
    public string Referredby_27332 { get; set; }
    public string EligibleforLotusServices_27333 { get; set; }
    public int? EligibleforLotusServices_27333_ResponseChoiceID { get; set; }
    public DateTime? EligibleDate_27334 { get; set; }
    public DateTime? IneligibleDate_27335 { get; set; }
    public string OtherReasons_27336 { get; set; }
    public string Historyasachild_27338 { get; set; }
    public int? Historyasachild_27338_ResponseChoiceID { get; set; }
    public string Historyasanadult_27340 { get; set; }
    public int? Historyasanadult_27340_ResponseChoiceID { get; set; }
    public string ChildProtection_27342 { get; set; }
    public int? ChildProtection_27342_ResponseChoiceID { get; set; }
    public string Otherorders_27343 { get; set; }
    public int? Otherorders_27343_ResponseChoiceID { get; set; }
    public string Name_27476 { get; set; }
    public string ContactDetails_27478 { get; set; }
    public string PermissiontoContact_27479 { get; set; }
    public int? PermissiontoContact_27479_ResponseChoiceID { get; set; }
    public string BirthCertificate_27482 { get; set; }
    public string MedicareCard_27483 { get; set; }
    public decimal? DriversLicense18Card_27484 { get; set; }
    public string Other_27485 { get; set; }
    public string EducationStatus_27487 { get; set; }
    public int? EducationStatus_27487_ResponseChoiceID { get; set; }
    public string Detailsofbeinginstitutionalizedasachild_27857 { get; set; }
    public string Detailsonhistoryofbeinginstitutionalizedasanadult_27858 { get; set; }
    public string DoestheParticipantspeakalanguageotherthanEnglishathome_28294 { get; set; }
    public int? DoestheParticipantspeakalanguageotherthanEnglishathome_28294_ResponseChoiceID { get; set; }
    public string ProgramName { get; set; }
    public string EntityName { get; set; }
    public string FName { get; set; }
    public string LName { get; set; }
}
}