using System;

namespace EtoApi.Models
{
    public class RedressNotesModel
    {
        public int? FormResponseID { get; set; }
        public string? FormIdentifier { get; set; }
        public int? SubjectID { get; set; }
        public int? GroupID { get; set; }
        public int? FamilyID { get; set; }
        public int? ResponseSetID { get; set; }
        public int? FormID { get; set; }
        public int? CollectionTypeID { get; set; }
        public int? SubjectTypeID { get; set; }
        public int? CollectionID { get; set; }
        public DateTime? ResponseCreatedDate { get; set; }
        public int? ProgramID { get; set; }
        public int? AuditStaffID { get; set; }
        public DateTime? AuditDate { get; set; }
        public int? DataEnteredByID { get; set; }
        public DateTime? DraftSavedOn { get; set; }
        public DateTime? RemovedDate { get; set; }
        public string? ContactMethod_28605 { get; set; }
        public int? ContactMethod_28605_ResponseChoiceID { get; set; }
        public string? ContactLocation_28606 { get; set; }
        public int? ContactLocation_28606_ResponseChoiceID { get; set; }
        public string? ServiceType_28607 { get; set; }
        public int? ServiceType_28607_ResponseChoiceID { get; set; }
        public string? ServiceSetting_28608 { get; set; }
        public int? ServiceSetting_28608_ResponseChoiceID { get; set; }
        public string? InterpreterPresent_28609 { get; set; }
        public int? InterpreterPresent_28609_ResponseChoiceID { get; set; }
        public string? Selectyourlocation_28614 { get; set; }
        public int? Selectyourlocation_28614_ResponseChoiceID { get; set; }
        public string? ContactLocation_28617 { get; set; }
        public int? ContactLocation_28617_ResponseChoiceID { get; set; }
        public string? TypeofNote_28619 { get; set; }
        public int? TypeofNote_28619_ResponseChoiceID { get; set; }
        public string? Notes_28620 { get; set; }
        public decimal? HowmanystaffdidthistogetherAtmost4_28621 { get; set; }
        public int? TimespentwithparticipantPerstaffmember_28625 { get; set; }
        public int? TimespentonbehalfofparticipantPerstaffmember_28626 { get; set; }
        public int? TimespenttravellingNotwithparticipantPerstaffmember_28627 { get; set; }
        public int? Totaltimespentwithparticipant_28628 { get; set; }
        public int? Totaltimespentonbehalfofparticipant_28629 { get; set; }
        public int? Totaltimespenttravelling_28630 { get; set; }
        public int? Totalefforttimeforparticipant_28631 { get; set; }
        public int? Selectyourname_28632 { get; set; }
        public int? MicahTeam_28633 { get; set; }
        public int? Selectthe2ndstaffperson_28634 { get; set; }
        public int? Whatotherteamassisted_28635 { get; set; }
        public int? WhatWDYNwasthisactioninresponseto_28639 { get; set; }
        public int? WhatWDYNwasthisactioninresponseto_28639_SourceFormID { get; set; }
        public string? WhatWDYNwasthisactioninresponseto_28639_DisplayStr { get; set; }
        public string? StatusofNRSapplication_28727 { get; set; }
        public int? StatusofNRSapplication_28727_ResponseChoiceID { get; set; }
        public string? IftheparticipantisunabletoaccesstheSchemewasawarmreferraltoanothersuitableservicegiven_28728 { get; set; }
        public int? IftheparticipantisunabletoaccesstheSchemewasawarmreferraltoanothersuitableservicegiven_28728_ResponseChoiceID { get; set; }
        public string? Whatistheserviceprovidersnamesparticipantwasreferredto_28729 { get; set; }
        public string? Wastheparticipantsupportedwerereferredtoknowmorelegalorfinancialcounsellingservice_28730 { get; set; }
        public int? Wastheparticipantsupportedwerereferredtoknowmorelegalorfinancialcounsellingservice_28730_ResponseChoiceID { get; set; }
        public string? Referredto_28731 { get; set; }
        public int? Referredto_28731_ResponseChoiceID { get; set; }
        public string? Otherservices_28732 { get; set; }
        public string? Wastheparticipantreferredtoamainstreamorspecialistsupportservice_28736 { get; set; }
        public int? Wastheparticipantreferredtoamainstreamorspecialistsupportservice_28736_ResponseChoiceID { get; set; }
        public string? Wastheparticipantreferredtoacounsellingserviceduringtheapplicationprocess_28737 { get; set; }
        public int? Wastheparticipantreferredtoacounsellingserviceduringtheapplicationprocess_28737_ResponseChoiceID { get; set; }
        public string? Wastheparticipantreferredtoamainstreamorspecialistsupportservice_28738 { get; set; }
        public int? Wastheparticipantreferredtoamainstreamorspecialistsupportservice_28738_ResponseChoiceID { get; set; }
        public string? CounsellingService_28739 { get; set; }
        public int? CounsellingService_28739_ResponseChoiceID { get; set; }
        public string? Recognitionofsexualabuse_28743 { get; set; }
        public int? Recognitionofsexualabuse_28743_ResponseChoiceID { get; set; }
        public string? Recognitionofimpactofsexualabuse_28744 { get; set; }
        public int? Recognitionofimpactofsexualabuse_28744_ResponseChoiceID { get; set; }
        public string? Recognitionofrelatednonsexualabuse_28745 { get; set; }
        public int? Recognitionofrelatednonsexualabuse_28745_ResponseChoiceID { get; set; }
        public string? Recognitionpersonwasinstitutionallyvulnerable_28746 { get; set; }
        public int? Recognitionpersonwasinstitutionallyvulnerable_28746_ResponseChoiceID { get; set; }
        public string? Recognitionofextremecircumstancesofsexualabuse_28747 { get; set; }
        public int? Recognitionofextremecircumstancesofsexualabuse_28747_ResponseChoiceID { get; set; }
        public string? HasparticipantacceptedDPR_28749 { get; set; }
        public int? HasparticipantacceptedDPR_28749_ResponseChoiceID { get; set; }
        public string? HasDPRcommenced_28750 { get; set; }
        public int? HasDPRcommenced_28750_ResponseChoiceID { get; set; }
        public string? Whoisthefacilitator_28751 { get; set; }
        public DateTime? Datesetforapology_28752 { get; set; }
        public string? Followuprequirednotes_28753 { get; set; }
        public string? HasparticipantaccpetedCPC_28755 { get; set; }
        public int? HasparticipantaccpetedCPC_28755_ResponseChoiceID { get; set; }
        public string? HasCPCcommenced_28756 { get; set; }
        public int? HasCPCcommenced_28756_ResponseChoiceID { get; set; }
        public string? Whoisthepractitioner_28757 { get; set; }
        public string? Hasawarmreferralbeenmade_28861 { get; set; }
        public int? Hasawarmreferralbeenmade_28861_ResponseChoiceID { get; set; }
        public string? HasaNRSofferbeenreceived_28862 { get; set; }
        public int? HasaNRSofferbeenreceived_28862_ResponseChoiceID { get; set; }
        public string? Scoreassessedby_29634 { get; set; }
        public int? Scoreassessedby_29634_ResponseChoiceID { get; set; }
        public string? Isthisthefirstpreorlastpostscore_29635 { get; set; }
        public int? Isthisthefirstpreorlastpostscore_29635_ResponseChoiceID { get; set; }
        public string? DomainGoals_29636 { get; set; }
        public int? DomainGoals_29636_ResponseChoiceID { get; set; }
        public string? ChangedknowledgeandaccesstoinformationScore1Noprogressinincreasingaccesstoinformationandknowle_29638 { get; set; }
        public int? ChangedknowledgeandaccesstoinformationScore1Noprogressinincreasingaccesstoinformationandknowle_29638_ResponseChoiceID { get; set; }
        public string? EmpowermentchoiceandcontroltomakeowndecisionsScore1Noprogressinincreasingconfidenceandexercisi_29639 { get; set; }
        public int? EmpowermentchoiceandcontroltomakeowndecisionsScore1Noprogressinincreasingconfidenceandexercisi_29639_ResponseChoiceID { get; set; }
        public string? EngagementwithrelevantsupportservicesScore1Noprogressinincreasingengagementwithsupportservices_29640 { get; set; }
        public int? EngagementwithrelevantsupportservicesScore1Noprogressinincreasingengagementwithsupportservices_29640_ResponseChoiceID { get; set; }
        public string? DomainCircumstances_29641 { get; set; }
        public int? DomainCircumstances_29641_ResponseChoiceID { get; set; }
        public string? CommunityparticipationnetworksScore1Significantnegativeimpactofpoorcommunityparticipationnetwo_29643 { get; set; }
        public int? CommunityparticipationnetworksScore1Significantnegativeimpactofpoorcommunityparticipationnetwo_29643_ResponseChoiceID { get; set; }
        public string? MentalhealthwellbeingandselfcareScore1Significantnegativeimpactofpoormentalhealthwellbeingands_29644 { get; set; }
        public int? MentalhealthwellbeingandselfcareScore1Significantnegativeimpactofpoormentalhealthwellbeingands_29644_ResponseChoiceID { get; set; }
        public string? PersonalandfamilysafetyScore1Significantnegativeimpactofpoorpersonalandfamilysafetyonindepende_29645 { get; set; }
        public int? PersonalandfamilysafetyScore1Significantnegativeimpactofpoorpersonalandfamilysafetyonindepende_29645_ResponseChoiceID { get; set; }
        public string? DomainSatisfaction_29646 { get; set; }
        public int? DomainSatisfaction_29646_ResponseChoiceID { get; set; }
        public string? Iambetterabletodealwithissuesthatsoughthelpwith_29648 { get; set; }
        public int? Iambetterabletodealwithissuesthatsoughthelpwith_29648_ResponseChoiceID { get; set; }
        public string? IamsatisfiedwiththeservicesIhavereceived_29649 { get; set; }
        public int? IamsatisfiedwiththeservicesIhavereceived_29649_ResponseChoiceID { get; set; }
        public string? Theservicelistenedtomeandunderstoodmyissues_29650 { get; set; }
        public int? Theservicelistenedtomeandunderstoodmyissues_29650_ResponseChoiceID { get; set; }
        public string? ChangedbehavioursScore1Noprogressinchangingbehavioursinareasrelevanttoclientsneedsandcircumsta_29651 { get; set; }
        public int? ChangedbehavioursScore1Noprogressinchangingbehavioursinareasrelevanttoclientsneedsandcircumsta_29651_ResponseChoiceID { get; set; }
        public string? ChangedimmediatecrisisScore1NoprogressinreducingthenegativeimpactoftheimmediatecrisisScore2Lim_29652 { get; set; }
        public int? ChangedimmediatecrisisScore1NoprogressinreducingthenegativeimpactoftheimmediatecrisisScore2Lim_29652_ResponseChoiceID { get; set; }
        public string? ChangedSkillsScore1NoprogressinincreasingskillsinareasrelevanttoclientsneedsandcircumstancesSc_29653 { get; set; }
        public int? ChangedSkillsScore1NoprogressinincreasingskillsinareasrelevanttoclientsneedsandcircumstancesSc_29653_ResponseChoiceID { get; set; }
        public string? AgeappropriatedevelopmentScore1Significantnegativeimpactofpoorageappropriatedevelopmentonindep_29654 { get; set; }
        public int? AgeappropriatedevelopmentScore1Significantnegativeimpactofpoorageappropriatedevelopmentonindep_29654_ResponseChoiceID { get; set; }
        public string? EducationandskillstrainingScore1Significantnegativeimpactoflackofengagementwitheducationandtra_29655 { get; set; }
        public int? EducationandskillstrainingScore1Significantnegativeimpactoflackofengagementwitheducationandtra_29655_ResponseChoiceID { get; set; }
        public string? EmploymentScore1Significantnegativeimpactoflackofemploymentonindependenceparticipationandwellb_29657 { get; set; }
        public int? EmploymentScore1Significantnegativeimpactoflackofemploymentonindependenceparticipationandwellb_29657_ResponseChoiceID { get; set; }
        public string? FamilyFunctioningScore1Significantnegativeimpactofpoorfamilyfunctioningonindependenceparticipa_29658 { get; set; }
        public int? FamilyFunctioningScore1Significantnegativeimpactofpoorfamilyfunctioningonindependenceparticipa_29658_ResponseChoiceID { get; set; }
        public string? FinancialresilienceScore1Significantnegativeimpactofpoorfinancialresilienceonindependenceparti_29659 { get; set; }
        public int? FinancialresilienceScore1Significantnegativeimpactofpoorfinancialresilienceonindependenceparti_29659_ResponseChoiceID { get; set; }
        public string? HousingScore1Significantnegativeimpactofpoorhousingonindependenceparticipationandwellbeingegro_29660 { get; set; }
        public int? HousingScore1Significantnegativeimpactofpoorhousingonindependenceparticipationandwellbeingegro_29660_ResponseChoiceID { get; set; }
        public string? MaterialwellbeingandbasicnecessitiesScore1Significantnegativeimpactoflackofbasicmaterialresour_29661 { get; set; }
        public int? MaterialwellbeingandbasicnecessitiesScore1Significantnegativeimpactoflackofbasicmaterialresour_29661_ResponseChoiceID { get; set; }
        public string? PhysicalhealthScore1Significantnegativeimpactofpoorphysicalhealthonindependenceparticipationan_29662 { get; set; }
        public int? PhysicalhealthScore1Significantnegativeimpactofpoorphysicalhealthonindependenceparticipationan_29662_ResponseChoiceID { get; set; }
        public string? Scoring_31497 { get; set; }


        public string? FName { get; set; }
        public string? LName { get; set; }
        public string? SubjectName { get; set; }
        public string? ProgramName { get; set; }

        public string? EntityName { get; set; }
        

    }
}