public class ServiceActivity
{
    public int? FormResponseID { get; set; }
    public string? FormIdentifier { get; set; }
    public int? SubjectID { get; set; }
    public int? GroupID { get; set; }
    public int? FamilyID { get; set; }
    public int? ResponseSetID { get; set; }
    public int? FormID { get; set; }
    public int? CollectionTypeID { get; set; }
    public int? SubjectTypeID { get; set; }
    public int? CollectionID { get; set; }
    public DateTime? ResponseCreatedDate { get; set; }
    public string? ProgramName { get; set; }
    public int? DataEnteredByID { get; set; }
    public DateTime? DraftSavedOn { get; set; }
    public DateTime? RemovedDate { get; set; }
    public string? ShsGeneralAssistanceAndSupportActivities_16201 { get; set; }
    public int? ShsGeneralAssistanceAndSupportActivities_16201_ResponseChoiceID { get; set; }
    public string? Notes_16203 { get; set; }
    public string? VisitSite_16219 { get; set; }
    public int? VisitSite_16219_ResponseChoiceID { get; set; }
    public string? PresentingReason_16220 { get; set; }
    public int? InclusiveHealthReferralSource_16221 { get; set; }
    public decimal? PostcodeOfServiceDelivery_16230 { get; set; }
    public string? EpisodeOfCareOutcome_16231 { get; set; }
    public int? EpisodeOfCareOutcome_16231_ResponseChoiceID { get; set; }
    public DateTime? AccommodationStartDate_16236 { get; set; }
    public int? AccommodationProvider_16237 { get; set; }
    public DateTime? AccommodationExitDate_16238 { get; set; }
    public decimal? NumberNights_16239 { get; set; }
    public string? WasTheParticipantFamilyPresentDuringThisActivityAnswerYesIfConversingWithParticipantFamilyOnPh_16241 { get; set; }
    public int? WasTheParticipantFamilyPresentDuringThisActivityAnswerYesIfConversingWithParticipantFamilyOnPh_16241_ResponseChoiceID { get; set; }
    public string? ContactMethod_16242 { get; set; }
    public int? ContactMethod_16242_ResponseChoiceID { get; set; }
    public string? ContactLocation_16243 { get; set; }
    public int? ContactLocation_16243_ResponseChoiceID { get; set; }
    public string? IfContactLocationIsOtherPleaseIndicate_16244 { get; set; }
    public string? PhoneContactType_16245 { get; set; }
    public int? PhoneContactType_16245_ResponseChoiceID { get; set; }
    public string? IfSupportTypeisOtherPleaseIndicate_16250 { get; set; }
    public string? HousingaccommodationShs_16262 { get; set; }
    public int? HousingaccommodationShs_16262_ResponseChoiceID { get; set; }
    public int? WithWhichProviderDidYouLiaiseCoordinateOrAdvocate_16263 { get; set; }
    public string? NeedsIdentifiedHousingaccommodation_16267 { get; set; }
    public int? NeedsIdentifiedHousingaccommodation_16267_ResponseChoiceID { get; set; }
    public string? NeedsIdentifiedGeneralAssistanceAndSupport_16268 { get; set; }
    public int? NeedsIdentifiedGeneralAssistanceAndSupport_16268_ResponseChoiceID { get; set; }
    public string? NeedsIdentifiedSpecialisedServices_16269 { get; set; }
    public int? NeedsIdentifiedSpecialisedServices_16269_ResponseChoiceID { get; set; }
    public string? EntityName { get; set; }
    public string? Start_16282 { get; set; }
    public string? EndOptional_16283 { get; set; }
    public decimal? HowManyStaffDidThisTogetherAtMost4_16284 { get; set; }
    public int? SelectThe2ndStaffPerson_16285 { get; set; }
    public string? WasThisAPatPersonalVisit_16295 { get; set; }
    public int? WasThisAPatPersonalVisit_16295_ResponseChoiceID { get; set; }
    public int? SelectYourName_16296 { get; set; }
    public string? ShsSpecialisedActivities_16338 { get; set; }
    public int? ShsSpecialisedActivities_16338_ResponseChoiceID { get; set; }
    public int? WhatOtherTeamAssisted_16352 { get; set; }
    public decimal? KeepNullCondition_16354 { get; set; }
    public int? TimespentwithparticipantPerstaffmember_16356 { get; set; }
    public int? TimespentonbehalfofparticipantPerstaffmember_16357 { get; set; }
    public int? TimespenttravellingNotwithparticipantPerstaffmember_16358 { get; set; }
    public int? Totalefforttimeforparticipant_16362 { get; set; }
    public int? ParentFormResponseID_293 { get; set; }
    public int? SupportTypewhatdidyouprovideprimarily_16505 { get; set; }
    public int? ScopeofNeedGoal_16580 { get; set; }
    public string? ScopeofNeedGoal_16580_DisplayStr { get; set; }
    public int? Domain_16582 { get; set; }
    public string? Domain_16582_DisplayStr { get; set; }
    public int? LongTermGoal_16583 { get; set; }
    public string? LongTermGoal_16583_DisplayStr { get; set; }
    public int? CrisisGoalNeed_16585 { get; set; }
    public string? CrisisGoalNeed_16585_DisplayStr { get; set; }
    public int? OtherGoalNeed_16586 { get; set; }
    public string? OtherGoalNeed_16586_DisplayStr { get; set; }
    public int? TimespentwithparticipantPerstaffmemberSA1_16588 { get; set; }
    public int? TimespentonbehalfofparticipantPerstaffmemberSA1_16589 { get; set; }
    public int? TimespenttravellingNotwithparticipantPerstaffmemberSA2_16590 { get; set; }
    public int? Ifyouprovidedasecondserviceoractivityselectithere_16591 { get; set; }
    public string? If2ndServiceorActivitytypeisOtherpleaseindicate_16592 { get; set; }
    public int? TimespentwithparticipantPerstaffmemberSA2_16593 { get; set; }
    public int? TimespentonbehalfofparticipantPerstaffmemberSA2_16594 { get; set; }
    public int? TimespenttravellingNotwithparticipantPerstaffmemberSA2_16595 { get; set; }
    public int? Ifyouprovidedathirdserviceoractivityselectithere_16596 { get; set; }
    public string? If3rdServiceorActivityisOtherpleasespecify_16600 { get; set; }
    public int? TimespentwithparticipantPerstaffmemberSA3_16601 { get; set; }
    public int? TimespentonbehalfofparticipantPerstaffmemberSA3_16602 { get; set; }
    public int? TimespenttravellingNotwithparticipantPerstaffmemberSA3_16603 { get; set; }
    public int? IfyouprovidedafourthServiceorActivityselectithere_16604 { get; set; }
    public string? If4thServiceorActivityisOtherpleasespecify_16605 { get; set; }
    public int? TimespentwithparticipantPerstaffmemberSA4_16606 { get; set; }
    public int? TimespentonbehalfofparticipantPerstaffmemberSA4_16607 { get; set; }
    public int? TimespenttravellingNotwithparticipantPerstaffmemberSA4_16608 { get; set; }
    public int? Totaltimespentwithparticipant_16609 { get; set; }
    public int? Totaltimespentonbehalfofparticipant_16610 { get; set; }
    public int? Totaltimespenttravelling_16611 { get; set; }
    public string? AIHWServiceActivitySA1_16698 { get; set; }
    public string? AIHWServiceActivitySA2_16699 { get; set; }
    public string? AIHWServiceActivitySA3_16700 { get; set; }
    public string? AIHWServiceActivitySA4_16701 { get; set; }
    public string? ShowHousingTabinSA1_16702 { get; set; }
    public string? ShowHousingTabinSA2_16703 { get; set; }
    public string? ShowHousingTabinSA3_16704 { get; set; }
    public string? ShowHousingTabinSA4_16705 { get; set; }
    public string? ShowInclusiveHealthtab1_16706 { get; set; }
    public string? ShowInclusiveHealthtab3_16707 { get; set; }
    public string? ShowInclusiveHealthtab2_16708 { get; set; }
    public string? ShowInclusiveHealthtab1_16709 { get; set; }
    public string? Isthisahousinggoalandhasthispersonfamilybeenhoused_16810 { get; set; }
    public int? Isthisahousinggoalandhasthispersonfamilybeenhoused_16810_ResponseChoiceID { get; set; }
    public string? Progresstowardsthisgoalinthepasttwoweekshasbeen_16819 { get; set; }
    public int? Progresstowardsthisgoalinthepasttwoweekshasbeen_16819_ResponseChoiceID { get; set; }
    public string? Participantlevelofmotivationforthisgoal_16821 { get; set; }
    public int? Participantlevelofmotivationforthisgoal_16821_ResponseChoiceID { get; set; }
    public string? InclusiveHealthReferralSource_17548 { get; set; }
    public int? InclusiveHealthReferralSource_17548_ResponseChoiceID { get; set; }
    public string? InclusiveHealthReferralMade_17549 { get; set; }
    public int? InclusiveHealthReferralMade_17549_ResponseChoiceID { get; set; }
    public string? TeamInclusiveHealth_19817 { get; set; }
    public string? TeamInclusiveHealth2_19818 { get; set; }
    public string? WereyouinavehicleIfsoselect_20571 { get; set; }
    public int? WereyouinavehicleIfsoselect_20571_ResponseChoiceID { get; set; }
    public int? WithwhichProviderdidyouliaisecoordinateoradvocateSA2_20970 { get; set; }
    public int? WithwhichProviderdidyouliaisecoordinateoradvocateSA3_20971 { get; set; }
    public int? WithwhichProviderdidyouliaisecoordinateoradvocateSA4_20972 { get; set; }
    public string? InclusiveHealthReferralMade_21843 { get; set; }
    public int? InclusiveHealthReferralMade_21843_ResponseChoiceID { get; set; }
    public string? InclusiveHealthReferralMade_21844 { get; set; }
    public int? InclusiveHealthReferralMade_21844_ResponseChoiceID { get; set; }
    public string? HealthVanRequired_22454 { get; set; }
    public string? HealthVanRequired_22455 { get; set; }
    public int? DateWDYNClosed_23231 { get; set; }
    public string? DateWDYNClosed_23231_DisplayStr { get; set; }
    public decimal? IfanoutstandingDebtwasreducedbyhowmuch_23273 { get; set; }
    public decimal? Ifonetimeincomewasobtainedhowmuch_23274 { get; set; }
    public decimal? IFrecurringincomewasobtainedwhatismonthlyamount_23275 { get; set; }
    public string? WereyouinavehicleIfsoselect_23525 { get; set; }
    public int? WereyouinavehicleIfsoselect_23525_ResponseChoiceID { get; set; }
    public string? InclusiveHealthReferralMade_23549 { get; set; }
    public int? InclusiveHealthReferralMade_23549_ResponseChoiceID { get; set; }
    public int? PostCode_23550 { get; set; }
    public int? PostcodeofServiceDelivery_23551 { get; set; }
    public int? VisitSiteHealth_23976 { get; set; }
    public int? InclusiveHealthReferralSource_23992 { get; set; }
    public int? InclusiveHealthReferralMade_23993 { get; set; }
    public int? InclusiveHealthReferralMade_24031 { get; set; }
    public int? InclusiveHealthReferralMade_24032 { get; set; }
    public string? IgnoreThis_24086 { get; set; }
    public int? IgnoreThis_24086_ResponseChoiceID { get; set; }
    public int? HealthReferralMade_24481 { get; set; }
    public decimal? Temprature_26012 { get; set; }
    public string? BloodPressuremmHg_26013 { get; set; }
    public decimal? HeartRatebeastperminute_26014 { get; set; }
    public string? HeartRateregularity_26015 { get; set; }
    public int? HeartRateregularity_26015_ResponseChoiceID { get; set; }
    public decimal? Respirationsperminute_26016 { get; set; }
    public decimal? Oxygensaturation_26017 { get; set; }
    public decimal? BloodSugarmmollitre_26018 { get; set; }
    public decimal? PeakFlow_26019 { get; set; }
    public decimal? Weightkilograms_26020 { get; set; }
    public decimal? Heightcentimeters_26021 { get; set; }
    public decimal? BMI_26022 { get; set; }
    public string? Urinalysis_26023 { get; set; }
    public string? Areyourecordingclinicalobservations_26024 { get; set; }
    public int? Areyourecordingclinicalobservations_26024_ResponseChoiceID { get; set; }
    public string? Iamhere_28395 { get; set; }
    public string? Iamhere_28396 { get; set; }
    public string? Didyouadministermedication_28401 { get; set; }
    public int? Didyouadministermedication_28401_ResponseChoiceID { get; set; }
    public string? Didyoucallemergencyservicesaspartofthisengagement_28405 { get; set; }
    public int? Didyoucallemergencyservicesaspartofthisengagement_28405_ResponseChoiceID { get; set; }
    public string? Ifyeswhichoneshavebeencalled_28406 { get; set; }
    public int? Ifyeswhichoneshavebeencalled_28406_ResponseChoiceID { get; set; }
    public int? Whichgoalwasthisfor_29378 { get; set; }
    public int? Whichgoalwasthisfor_29378_SourceFormID { get; set; }
    public string? Whichgoalwasthisfor_29378_DisplayStr { get; set; }
    public int? Whichgoalwasthisfor_29381 { get; set; }
    public int? Whichgoalwasthisfor_29381_SourceFormID { get; set; }
    public string? Whichgoalwasthisfor_29381_DisplayStr { get; set; }
    public int? _2ndactivitiyWhichgoalwasthisfor_29496 { get; set; }
    public int? _2ndactivitiyWhichgoalwasthisfor_29496_SourceFormID { get; set; }
    public string? _2ndactivitiyWhichgoalwasthisfor_29496_DisplayStr { get; set; }
    public int? _3AWhichgoalwasthisfor_29497 { get; set; }
    public int? _3AWhichgoalwasthisfor_29497_SourceFormID { get; set; }
    public string? _3AWhichgoalwasthisfor_29497_DisplayStr { get; set; }
    public int? _4AWhichgoalwasthisfor_29498 { get; set; }
    public int? _4AWhichgoalwasthisfor_29498_SourceFormID { get; set; }
    public string? _4AWhichgoalwasthisfor_29498_DisplayStr { get; set; }
    public string? UserName_29499 { get; set; }
    public string? Whatkindofentryisthis_29502 { get; set; }
    public int? Whatkindofentryisthis_29502_ResponseChoiceID { get; set; }
    public string? Isthisahighlevelcheckin_31616 { get; set; }
    public int? Isthisahighlevelcheckin_31616_ResponseChoiceID { get; set; }
    public string? IsthistheFIRSThighlevelcheckin_31618 { get; set; }
    public int? IsthistheFIRSThighlevelcheckin_31618_ResponseChoiceID { get; set; }
    public string? Aresupportservicesinplaceandstillmeetingtheirneeds_31619 { get; set; }
    public int? Aresupportservicesinplaceandstillmeetingtheirneeds_31619_ResponseChoiceID { get; set; }
    public string? Dotheyneedsupportfromcarefinder_31623 { get; set; }
    public int? Dotheyneedsupportfromcarefinder_31623_ResponseChoiceID { get; set; }
    public string? Reasonsfornotstayingconnectedtoservices_31628 { get; set; }
    public int? Reasonsfornotstayingconnectedtoservices_31628_ResponseChoiceID { get; set; }
    public string? Isthereachronichealthcondition_32752 { get; set; }
    public int? Isthereachronichealthcondition_32752_ResponseChoiceID { get; set; }
    public string? Howwouldyouratethenursingcareprovidedtoyou_32939 { get; set; }
    public int? Howwouldyouratethenursingcareprovidedtoyou_32939_ResponseChoiceID { get; set; }
    public string? ClaimType_33234 { get; set; }
    public int? ClaimType_33234_ResponseChoiceID { get; set; }
    public string? GSTCode_33235 { get; set; }
    public int? GSTCode_33235_ResponseChoiceID { get; set; }
    public string? Isthisascheduledsupport_33236 { get; set; }
    public int? Isthisascheduledsupport_33236_ResponseChoiceID { get; set; }
    public string? ReasonforCancellationatShortNotice_33237 { get; set; }
    public int? ReasonforCancellationatShortNotice_33237_ResponseChoiceID { get; set; }
    public DateTime? TransactionDate_33294 { get; set; }
    public decimal? TransactionAmount_33296 { get; set; }
    public string? PaymentforAIHW_33297 { get; set; }
    public int? PaymentforAIHW_33297_ResponseChoiceID { get; set; }
    public DateTime? DateSafetyUpgradeCompleted_33299 { get; set; }
    public string? IfanymonitoringoreffortiswasrequiredtocompleteSafetyUpgradepleasedescribe_33300 { get; set; }
    public string? ServiceUserDFVOonlyOusterCondition_33301 { get; set; }
    public int? ServiceUserDFVOonlyOusterCondition_33301_ResponseChoiceID { get; set; }
    public string? IstheServiceUsercurrentlylivinginthehome_33302 { get; set; }
    public int? IstheServiceUsercurrentlylivinginthehome_33302_ResponseChoiceID { get; set; }
    public int? NumberofChildrenlivingwiththeServiceUserinhome_33303 { get; set; }
    public int? TransportofParticipanttofromApptorActivitySA1_33304 { get; set; }
    public int? TransportofParticipanttofromApptorActivitySA2_33305 { get; set; }
    public int? TimespenttravellingTransportofParticipanttofromApptorActivitySA3_33306 { get; set; }
    public int? TimespenttravellingTransportofParticipanttofromApptorActivitySA4_33307 { get; set; }
    public int? TimespenttravellingTransportofParticipanttofromApptorActivity_33308 { get; set; }
    public int? TotaltimespenttravellingTransportofParticipanttofromApptorActivity_33309 { get; set; }
    public int? Financeprojectcode_33310 { get; set; }
    public string? Brieftransactiondescription_33311 { get; set; }
    public int? Supplierprovider_33312 { get; set; }
    public string? Ifotherprovidesupplierbusinessname_33313 { get; set; }
    public string? Howwaspaymentmade_33314 { get; set; }
    public int? Howwaspaymentmade_33314_ResponseChoiceID { get; set; }
    public int? Authorisedby_33315 { get; set; }
    public string? Isanyportionofthistransactionrecoverable_33316 { get; set; }
    public int? Isanyportionofthistransactionrecoverable_33316_ResponseChoiceID { get; set; }
    public string? Recoveryinvoicename_33317 { get; set; }
    public decimal? Amountrecoverablefromthissource_33318 { get; set; }
    public string? Recoveryinvoicecontactname_33319 { get; set; }
    public string? Recoveryinvoicecontactemail_33320 { get; set; }
    public string? Haspaymentalreadybeenmadeordoesfinancestillneedtopay_33321 { get; set; }
    public int? Haspaymentalreadybeenmadeordoesfinancestillneedtopay_33321_ResponseChoiceID { get; set; }
    public string? IsthistransactionrelatedtoHousingandSafetyUpgrades_33322 { get; set; }
    public int? IsthistransactionrelatedtoHousingandSafetyUpgrades_33322_ResponseChoiceID { get; set; }
    public string? Wasbrokeragedoneforthisactivity_33325 { get; set; }
    public int? Wasbrokeragedoneforthisactivity_33325_ResponseChoiceID { get; set; }
    public string? Purpose_33327 { get; set; }
    public int? Purpose_33327_ResponseChoiceID { get; set; }
    public string? WasNaloxone_33329 { get; set; }
    public int? WasNaloxone_33329_ResponseChoiceID { get; set; }
    public int? UploadDocument_33331 { get; set; }
    public string? TESTDONOTCOMPLETEWhichtypeofdwellingdoesthisindividualcurrentlyresideinFOROUTREACHNURSEONLY_33332 { get; set; }
    public int? TESTDONOTCOMPLETEWhichtypeofdwellingdoesthisindividualcurrentlyresideinFOROUTREACHNURSEONLY_33332_ResponseChoiceID { get; set; }
    public string? TESTDONOTCOMPLETEIstheparticipantcurrentlyresidinginastableresidentialdwellingForoutreachnursi_33333 { get; set; }
    public int? TESTDONOTCOMPLETEIstheparticipantcurrentlyresidinginastableresidentialdwellingForoutreachnursi_33333_ResponseChoiceID { get; set; }
    public int? Whichstaffmembersbusinesscardwasused_33337 { get; set; }
    public int? Whichstaffmemberistobereimbursed_33338 { get; set; }
    // Staff details (common admin fields)
    public int? StaffID { get; set; }
    public string? FName { get; set; }
    public string? MiddleInitial { get; set; }
    public string? LName { get; set; }
    public int? SiteID { get; set; }
    public int? RoleId { get; set; }
    public string? Disabled { get; set; }
    public int? PrefixId { get; set; }
    public int? SuffixID { get; set; }
    public string? WorkPhone { get; set; }
    public string? WorkPhoneExtension { get; set; }
    public string? CellPhone { get; set; }
    public string? Pager { get; set; }
    public string? Email { get; set; }
    public string? UserName { get; set; }
    public string? OneClickAccepted { get; set; }
    public int? AuditStaffID { get; set; }
    public DateTime? AuditDate { get; set; }
    public string? SSN { get; set; }
    public string? Billable { get; set; }
    public string? Fingerprinted { get; set; }
    public string? StaffZipCode { get; set; }
    public string? MyRoleInMyOrganization { get; set; }
    public string? MyRoleInMyOrganizationOthers { get; set; }
    public string? ExperienceWithETO { get; set; }
    public string? ForceChangePassword { get; set; }
    public string? EncryptionAlgorithm { get; set; }
    public string? Password { get; set; }
    public string? AutoCollapseNavBar { get; set; }
    public string? IntegrationID { get; set; }
    public int? StaffID_Source { get; set; }
    public string? BOUser { get; set; }
    public string? BOPassword { get; set; }
    public int? ReportingRoleID { get; set; }
    public string? OnlyShowDeidentifiedData { get; set; }
    public string? BOUserGuid { get; set; }
    public string? LoginID { get; set; }
    public int? TimeZoneID { get; set; }
    public string? CaseloadSecurityEnabled { get; set; }
    public string? SelfService { get; set; }
    public DateTime? DateOfPasswordChange { get; set; }
    public int? TypeId { get; set; }
    public string? DefaultCultureName { get; set; }
    public string? OptOut { get; set; }
    public string? DisableQuickSearchDropdown { get; set; }
}
