namespace EtoApi.Models
{
    public class Wdyn
    {
        public int? FormResponseID { get; set; }
        public string? FormIdentifier { get; set; }
        public int? SubjectID { get; set; }
        public int? GroupID { get; set; }
        public int? FamilyID { get; set; }
        public int? ResponseSetID { get; set; }
        public int? FormID { get; set; }
        public int? CollectionTypeID { get; set; }
        public int? SubjectTypeID { get; set; }
        public int? CollectionID { get; set; }
        public DateTime? ResponseCreatedDate { get; set; }
        public string? ProgramID { get; set; }
        public int? AuditStaffID { get; set; }
        public DateTime? AuditDate { get; set; }
        public int? DataEnteredByID { get; set; }
        public DateTime? DraftSavedOn { get; set; }
        public DateTime? RemovedDate { get; set; }
        public string? ScopeOfGoal_15196 { get; set; }
        public int? ScopeOfGoal_15196_ResponseChoiceID { get; set; }
        public string? WhatIsTheCurrentStatusOfThisGoal_15197 { get; set; }
        public int? WhatIsTheCurrentStatusOfThisGoal_15197_ResponseChoiceID { get; set; }
        public string? OtherGoalNotListedAbove_15200 { get; set; }
        public string? Comments_15201 { get; set; }
        public string? OverallOutcomesAtGoalAchievementEndDate_15202 { get; set; }
        public DateTime? DateGoalClosed_15203 { get; set; }
        public string? ParticipantLevelOfMotivationForThisGoal_15206 { get; set; }
        public int? ParticipantLevelOfMotivationForThisGoal_15206_ResponseChoiceID { get; set; }
        public decimal? DontChangeMe_15216 { get; set; }
        public string? GoalLongerTerm_15220 { get; set; }
        public int? GoalLongerTerm_15220_ResponseChoiceID { get; set; }
        public string? DomainChooseOne_15221 { get; set; }
        public int? DomainChooseOne_15221_ResponseChoiceID { get; set; }
        public string? GoalCrisis_15222 { get; set; }
        public int? GoalCrisis_15222_ResponseChoiceID { get; set; }
        public string? Isthisgoalfor_15243 { get; set; }
        public int? Isthisgoalfor_15243_ResponseChoiceID { get; set; }
        public int? YouindicatedthatthisisforachildofthisparentPleaseselectthechild_15244 { get; set; }
        public string? SHSTypeOfServiceActivityTxt_15300 { get; set; }
        public int? Selectyourname_15404 { get; set; }
        public string? Start_15486 { get; set; }
        public string? Endoptional_15487 { get; set; }
        public decimal? HowmanystaffdidthistogetherAtmost4_15489 { get; set; }
        public int? Selectthe2ndstaffperson_15491 { get; set; }
        public int? Whatotherteamassisted_15492 { get; set; }
        public string? WasthisaPATpersonalvisit_15493 { get; set; }
        public int? WasthisaPATpersonalvisit_15493_ResponseChoiceID { get; set; }
        public int? TimespentonbehalfofparticipantPerstaffmember_15494 { get; set; }
        public int? TimespentwithparticipantPerstaffmember_15496 { get; set; }
        public int? Totaltimespentonbehalfofparticipant_15497 { get; set; }
        public int? Totaltimespenttravelling_15498 { get; set; }
        public int? Totaltimespentwithparticipant_15499 { get; set; }
        public string? ContactMethod_15501 { get; set; }
        public int? ContactMethod_15501_ResponseChoiceID { get; set; }
        public string? ContactLocation_15502 { get; set; }
        public int? ContactLocation_15502_ResponseChoiceID { get; set; }
        public string? Ifcontactlocationisotherpleasespecify_15503 { get; set; }
        public string? PhoneContactType_15504 { get; set; }
        public int? PhoneContactType_15504_ResponseChoiceID { get; set; }
        public int? Totalefforttimeforparticipant_15587 { get; set; }
        public string? SHSTypeOfServiceActivityNum_16066 { get; set; }
        public string? MicahTeam_16083 { get; set; }
        public int? TimespenttravellingNotwithparticipantPerstaffmember_16086 { get; set; }
        public string? PlanType_16365 { get; set; }
        public int? PlanType_16365_ResponseChoiceID { get; set; }
        public string? TypeofCrisis_16587 { get; set; }
        public int? TypeofCrisis_16587_ResponseChoiceID { get; set; }
        public string? Hasthispersonfamilybeenpermanentlyhoused_16951 { get; set; }
        public int? Hasthispersonfamilybeenpermanentlyhoused_16951_ResponseChoiceID { get; set; }
        public DateTime? Whatdateweretheyhoused_16952 { get; set; }
        public int? Throughwhichprovider_16954 { get; set; }
        public decimal? Ifaleaseisinplacewhatisthedurationoftheleaseinmonths_16956 { get; set; }
        public DateTime? Ifaleaseinplacewhatistherenewaldate_16957 { get; set; }
        public string? Areautorentpaymentsinplace_16958 { get; set; }
        public int? Areautorentpaymentsinplace_16958_ResponseChoiceID { get; set; }
        public string? WDYNStatus_23093 { get; set; }
        public int? WDYNStatus_23093_ResponseChoiceID { get; set; }
        public string? HasEnddate_23283 { get; set; }
        public int? HasEnddate_23283_ResponseChoiceID { get; set; }
        public string? Whattypeofhousingisit_28334 { get; set; }
        public int? Whattypeofhousingisit_28334_ResponseChoiceID { get; set; }
        public string? Istheparticipantfamilysleepingroughatthispresentation_28911 { get; set; }
        public int? Istheparticipantfamilysleepingroughatthispresentation_28911_ResponseChoiceID { get; set; }
        public string? fName { get; set;}
        public string? lName { get; set;}
    }
}
